CameraGlobal[0] = TextDrawCreate(21.0000, 21.1250, "Box"); // пусто
TextDrawLetterSize(CameraGlobal[0], 0.0000, 9.4497);
TextDrawTextSize(CameraGlobal[0], 24.0000, 0.0000);
TextDrawAlignment(CameraGlobal[0], 1);
TextDrawColor(CameraGlobal[0], -1);
TextDrawUseBox(CameraGlobal[0], 1);
TextDrawBoxColor(CameraGlobal[0], -1);
TextDrawBackgroundColor(CameraGlobal[0], 255);
TextDrawFont(CameraGlobal[0], 1);
TextDrawSetProportional(CameraGlobal[0], 1);
TextDrawSetShadow(CameraGlobal[0], 0);

CameraGlobal[1] = TextDrawCreate(27.5000, 21.1250, "Box"); // пусто
TextDrawLetterSize(CameraGlobal[1], 0.0000, 0.3998);
TextDrawTextSize(CameraGlobal[1], 104.4100, 0.0000);
TextDrawAlignment(CameraGlobal[1], 1);
TextDrawColor(CameraGlobal[1], -1);
TextDrawUseBox(CameraGlobal[1], 1);
TextDrawBoxColor(CameraGlobal[1], -1);
TextDrawBackgroundColor(CameraGlobal[1], 255);
TextDrawFont(CameraGlobal[1], 1);
TextDrawSetProportional(CameraGlobal[1], 1);
TextDrawSetShadow(CameraGlobal[1], 0);

CameraGlobal[2] = TextDrawCreate(47.0000, 57.0000, "LD_BEAT:CHIT"); // пусто
TextDrawTextSize(CameraGlobal[2], 21.0000, 23.0000);
TextDrawAlignment(CameraGlobal[2], 1);
TextDrawColor(CameraGlobal[2], -1523963137);
TextDrawBackgroundColor(CameraGlobal[2], 255);
TextDrawFont(CameraGlobal[2], 4);
TextDrawSetProportional(CameraGlobal[2], 0);
TextDrawSetShadow(CameraGlobal[2], 0);

CameraGlobal[3] = TextDrawCreate(69.5000, 58.7500, "REC"); // пусто
TextDrawLetterSize(CameraGlobal[3], 0.4478, 1.9148);
TextDrawAlignment(CameraGlobal[3], 1);
TextDrawColor(CameraGlobal[3], -1);
TextDrawBackgroundColor(CameraGlobal[3], 255);
TextDrawFont(CameraGlobal[3], 1);
TextDrawSetProportional(CameraGlobal[3], 1);
TextDrawSetShadow(CameraGlobal[3], 0);

CameraGlobal[4] = TextDrawCreate(608.4970, 30.9624, "Box"); // пусто
TextDrawLetterSize(CameraGlobal[4], 0.0000, 9.2999);
TextDrawTextSize(CameraGlobal[4], 612.3972, 0.0000);
TextDrawAlignment(CameraGlobal[4], 1);
TextDrawColor(CameraGlobal[4], -1);
TextDrawUseBox(CameraGlobal[4], 1);
TextDrawBoxColor(CameraGlobal[4], -1);
TextDrawBackgroundColor(CameraGlobal[4], 255);
TextDrawFont(CameraGlobal[4], 1);
TextDrawSetProportional(CameraGlobal[4], 1);
TextDrawSetShadow(CameraGlobal[4], 0);

CameraGlobal[5] = TextDrawCreate(616.3953, 23.1623, "Box"); // пусто
TextDrawLetterSize(CameraGlobal[5], 0.0000, 0.4999);
TextDrawTextSize(CameraGlobal[5], 530.3999, 0.0000);
TextDrawAlignment(CameraGlobal[5], 1);
TextDrawColor(CameraGlobal[5], -1);
TextDrawUseBox(CameraGlobal[5], 1);
TextDrawBoxColor(CameraGlobal[5], -1);
TextDrawBackgroundColor(CameraGlobal[5], 255);
TextDrawFont(CameraGlobal[5], 1);
TextDrawSetProportional(CameraGlobal[5], 1);
TextDrawSetShadow(CameraGlobal[5], 0);

CameraGlobal[6] = TextDrawCreate(19.8999, 342.6744, "Box"); // пусто
TextDrawLetterSize(CameraGlobal[6], 0.0000, 9.5000);
TextDrawTextSize(CameraGlobal[6], 24.3999, 0.0000);
TextDrawAlignment(CameraGlobal[6], 1);
TextDrawColor(CameraGlobal[6], -1);
TextDrawUseBox(CameraGlobal[6], 1);
TextDrawBoxColor(CameraGlobal[6], -1);
TextDrawBackgroundColor(CameraGlobal[6], 255);
TextDrawFont(CameraGlobal[6], 1);
TextDrawSetProportional(CameraGlobal[6], 1);
TextDrawSetShadow(CameraGlobal[6], 0);

CameraGlobal[7] = TextDrawCreate(27.3999, 423.7492, "Box"); // пусто
TextDrawLetterSize(CameraGlobal[7], 0.0000, 0.5217);
TextDrawTextSize(CameraGlobal[7], 103.0000, 0.0000);
TextDrawAlignment(CameraGlobal[7], 1);
TextDrawColor(CameraGlobal[7], -1);
TextDrawUseBox(CameraGlobal[7], 1);
TextDrawBoxColor(CameraGlobal[7], -1);
TextDrawBackgroundColor(CameraGlobal[7], 255);
TextDrawFont(CameraGlobal[7], 1);
TextDrawSetProportional(CameraGlobal[7], 1);
TextDrawSetShadow(CameraGlobal[7], 0);

CameraGlobal[8] = TextDrawCreate(606.0944, 423.3623, "Box"); // пусто
TextDrawLetterSize(CameraGlobal[8], 0.0000, 0.7889);
TextDrawTextSize(CameraGlobal[8], 525.9992, 0.0000);
TextDrawAlignment(CameraGlobal[8], 1);
TextDrawColor(CameraGlobal[8], -1);
TextDrawUseBox(CameraGlobal[8], 1);
TextDrawBoxColor(CameraGlobal[8], -1);
TextDrawBackgroundColor(CameraGlobal[8], 255);
TextDrawFont(CameraGlobal[8], 1);
TextDrawSetProportional(CameraGlobal[8], 1);
TextDrawSetShadow(CameraGlobal[8], 0);

CameraGlobal[9] = TextDrawCreate(605.8922, 346.3373, "Box"); // пусто
TextDrawLetterSize(CameraGlobal[9], 0.0000, 9.3499);
TextDrawTextSize(CameraGlobal[9], 611.2968, 0.0000);
TextDrawAlignment(CameraGlobal[9], 1);
TextDrawColor(CameraGlobal[9], -1);
TextDrawUseBox(CameraGlobal[9], 1);
TextDrawBoxColor(CameraGlobal[9], -1);
TextDrawBackgroundColor(CameraGlobal[9], 255);
TextDrawFont(CameraGlobal[9], 1);
TextDrawSetProportional(CameraGlobal[9], 1);
TextDrawSetShadow(CameraGlobal[9], 0);