ChooseSpawn_TD[0] = TextDrawCreate(259.5000, 144.6374, "Box"); // пусто
TextDrawLetterSize(ChooseSpawn_TD[0], 0.0000, 2.5000);
TextDrawTextSize(ChooseSpawn_TD[0], 391.0000, 0.0000);
TextDrawAlignment(ChooseSpawn_TD[0], 1);
TextDrawColor(ChooseSpawn_TD[0], -1);
TextDrawUseBox(ChooseSpawn_TD[0], 1);
TextDrawBoxColor(ChooseSpawn_TD[0], -1523963137);
TextDrawBackgroundColor(ChooseSpawn_TD[0], 255);
TextDrawFont(ChooseSpawn_TD[0], 1);
TextDrawSetProportional(ChooseSpawn_TD[0], 1);
TextDrawSetShadow(ChooseSpawn_TD[0], 0);

ChooseSpawn_TD[1] = TextDrawCreate(242.4999, 136.9749, "LD_BEAT:CHIT"); // пусто
TextDrawTextSize(ChooseSpawn_TD[1], 28.0000, 37.8398);
TextDrawAlignment(ChooseSpawn_TD[1], 1);
TextDrawColor(ChooseSpawn_TD[1], -1523963137);
TextDrawBackgroundColor(ChooseSpawn_TD[1], 255);
TextDrawFont(ChooseSpawn_TD[1], 4);
TextDrawSetProportional(ChooseSpawn_TD[1], 0);
TextDrawSetShadow(ChooseSpawn_TD[1], 0);

ChooseSpawn_TD[2] = TextDrawCreate(378.9999, 136.9749, "LD_BEAT:CHIT"); // пусто
TextDrawTextSize(ChooseSpawn_TD[2], 28.0000, 37.8398);
TextDrawAlignment(ChooseSpawn_TD[2], 1);
TextDrawColor(ChooseSpawn_TD[2], -1523963137);
TextDrawBackgroundColor(ChooseSpawn_TD[2], 255);
TextDrawFont(ChooseSpawn_TD[2], 4);
TextDrawSetProportional(ChooseSpawn_TD[2], 0);
TextDrawSetShadow(ChooseSpawn_TD[2], 0);

ChooseSpawn_TD[3] = TextDrawCreate(272.9999, 148.4375, "GENUINE_ROLE_PLAY"); // пусто
TextDrawLetterSize(ChooseSpawn_TD[3], 0.2724, 1.3712);
TextDrawAlignment(ChooseSpawn_TD[3], 1);
TextDrawColor(ChooseSpawn_TD[3], -1);
TextDrawBackgroundColor(ChooseSpawn_TD[3], 255);
TextDrawFont(ChooseSpawn_TD[3], 2);
TextDrawSetProportional(ChooseSpawn_TD[3], 1);
TextDrawSetShadow(ChooseSpawn_TD[3], 1);

ChooseSpawn_TD[4] = TextDrawCreate(294.9001, 204.5265, "LD_SPAC:white"); // пусто
TextDrawTextSize(ChooseSpawn_TD[4], 55.0000, 15.0000);
TextDrawAlignment(ChooseSpawn_TD[4], 1);
TextDrawColor(ChooseSpawn_TD[4], -1523963137);
TextDrawBackgroundColor(ChooseSpawn_TD[4], 255);
TextDrawFont(ChooseSpawn_TD[4], 4);
TextDrawSetProportional(ChooseSpawn_TD[4], 0);
TextDrawSetShadow(ChooseSpawn_TD[4], 0);
TextDrawSetSelectable(ChooseSpawn_TD[4], true);

ChooseSpawn_TD[5] = TextDrawCreate(294.6002, 179.9375, "LD_SPAC:white"); // пусто
TextDrawTextSize(ChooseSpawn_TD[5], 55.0000, 15.0000);
TextDrawAlignment(ChooseSpawn_TD[5], 1);
TextDrawColor(ChooseSpawn_TD[5], -1523963137);
TextDrawBackgroundColor(ChooseSpawn_TD[5], 255);
TextDrawFont(ChooseSpawn_TD[5], 4);
TextDrawSetProportional(ChooseSpawn_TD[5], 0);
TextDrawSetShadow(ChooseSpawn_TD[5], 0);
TextDrawSetSelectable(ChooseSpawn_TD[5], true);

ChooseSpawn_TD[6] = TextDrawCreate(294.7002, 229.5405, "LD_SPAC:white"); // пусто
TextDrawTextSize(ChooseSpawn_TD[6], 55.0000, 15.0000);
TextDrawAlignment(ChooseSpawn_TD[6], 1);
TextDrawColor(ChooseSpawn_TD[6], -1523963137);
TextDrawBackgroundColor(ChooseSpawn_TD[6], 255);
TextDrawFont(ChooseSpawn_TD[6], 4);
TextDrawSetProportional(ChooseSpawn_TD[6], 0);
TextDrawSetShadow(ChooseSpawn_TD[6], 0);
TextDrawSetSelectable(ChooseSpawn_TD[6], true);

ChooseSpawn_TD[7] = TextDrawCreate(294.9002, 255.2420, "LD_SPAC:white"); // пусто
TextDrawTextSize(ChooseSpawn_TD[7], 55.0000, 15.0000);
TextDrawAlignment(ChooseSpawn_TD[7], 1);
TextDrawColor(ChooseSpawn_TD[7], -1523963137);
TextDrawBackgroundColor(ChooseSpawn_TD[7], 255);
TextDrawFont(ChooseSpawn_TD[7], 4);
TextDrawSetProportional(ChooseSpawn_TD[7], 0);
TextDrawSetShadow(ChooseSpawn_TD[7], 0);
TextDrawSetSelectable(ChooseSpawn_TD[7], true);

ChooseSpawn_TD[8] = TextDrawCreate(301.0000, 182.2624, "HOUSE_SPAWN"); // пусто
TextDrawLetterSize(ChooseSpawn_TD[8], 0.1505, 1.0268);
TextDrawAlignment(ChooseSpawn_TD[8], 1);
TextDrawColor(ChooseSpawn_TD[8], -1);
TextDrawBackgroundColor(ChooseSpawn_TD[8], 255);
TextDrawFont(ChooseSpawn_TD[8], 2);
TextDrawSetProportional(ChooseSpawn_TD[8], 1);
TextDrawSetShadow(ChooseSpawn_TD[8], 0);

ChooseSpawn_TD[9] = TextDrawCreate(297.0997, 206.8639, "FRACTION_SPAWN"); // пусто
TextDrawLetterSize(ChooseSpawn_TD[9], 0.1505, 1.0268);
TextDrawAlignment(ChooseSpawn_TD[9], 1);
TextDrawColor(ChooseSpawn_TD[9], -1);
TextDrawBackgroundColor(ChooseSpawn_TD[9], 255);
TextDrawFont(ChooseSpawn_TD[9], 2);
TextDrawSetProportional(ChooseSpawn_TD[9], 1);
TextDrawSetShadow(ChooseSpawn_TD[9], 0);

ChooseSpawn_TD[10] = TextDrawCreate(299.0998, 231.4654, "SERVER_SPAWN"); // пусто
TextDrawLetterSize(ChooseSpawn_TD[10], 0.1505, 1.0268);
TextDrawAlignment(ChooseSpawn_TD[10], 1);
TextDrawColor(ChooseSpawn_TD[10], -1);
TextDrawBackgroundColor(ChooseSpawn_TD[10], 255);
TextDrawFont(ChooseSpawn_TD[10], 2);
TextDrawSetProportional(ChooseSpawn_TD[10], 1);
TextDrawSetShadow(ChooseSpawn_TD[10], 0);

ChooseSpawn_TD[11] = TextDrawCreate(299.4999, 256.8670, "GASVLIS_ADGILI"); // пусто
TextDrawLetterSize(ChooseSpawn_TD[11], 0.1505, 1.0268);
TextDrawAlignment(ChooseSpawn_TD[11], 1);
TextDrawColor(ChooseSpawn_TD[11], -1);
TextDrawBackgroundColor(ChooseSpawn_TD[11], 255);
TextDrawFont(ChooseSpawn_TD[11], 2);
TextDrawSetProportional(ChooseSpawn_TD[11], 1);
TextDrawSetShadow(ChooseSpawn_TD[11], 0);