ContainerGlobal[0] = TextDrawCreate(209.5000, 178.3633, "Box"); // пусто
TextDrawLetterSize(ContainerGlobal[0], 0.0000, 1.7779);
TextDrawTextSize(ContainerGlobal[0], 428.0000, 0.0000);
TextDrawAlignment(ContainerGlobal[0], 1);
TextDrawColor(ContainerGlobal[0], -1);
TextDrawUseBox(ContainerGlobal[0], 1);
TextDrawBoxColor(ContainerGlobal[0], 674248703);
TextDrawBackgroundColor(ContainerGlobal[0], 255);
TextDrawFont(ContainerGlobal[0], 1);
TextDrawSetProportional(ContainerGlobal[0], 1);
TextDrawSetShadow(ContainerGlobal[0], 0);

ContainerGlobal[1] = TextDrawCreate(209.6999, 203.2271, "Box"); // пусто
TextDrawLetterSize(ContainerGlobal[1], 0.0000, 11.8139);
TextDrawTextSize(ContainerGlobal[1], 314.0000, 0.0000);
TextDrawAlignment(ContainerGlobal[1], 1);
TextDrawColor(ContainerGlobal[1], -1);
TextDrawUseBox(ContainerGlobal[1], 1);
TextDrawBoxColor(ContainerGlobal[1], 674248703);
TextDrawBackgroundColor(ContainerGlobal[1], 255);
TextDrawFont(ContainerGlobal[1], 1);
TextDrawSetProportional(ContainerGlobal[1], 1);
TextDrawSetShadow(ContainerGlobal[1], 0);

ContainerGlobal[2] = TextDrawCreate(324.7055, 203.1896, "Box"); // пусто
TextDrawLetterSize(ContainerGlobal[2], 0.0000, 11.8129);
TextDrawTextSize(ContainerGlobal[2], 427.8321, 0.0000);
TextDrawAlignment(ContainerGlobal[2], 1);
TextDrawColor(ContainerGlobal[2], -1);
TextDrawUseBox(ContainerGlobal[2], 1);
TextDrawBoxColor(ContainerGlobal[2], 674248703);
TextDrawBackgroundColor(ContainerGlobal[2], 255);
TextDrawFont(ContainerGlobal[2], 1);
TextDrawSetProportional(ContainerGlobal[2], 1);
TextDrawSetShadow(ContainerGlobal[2], 0);

ContainerGlobal[3] = TextDrawCreate(239.0000, 305.6374, "LD_SPAC:white"); // пусто
TextDrawTextSize(ContainerGlobal[3], 47.0000, 13.0000);
TextDrawAlignment(ContainerGlobal[3], 1);
TextDrawColor(ContainerGlobal[3], 192535039);
TextDrawBackgroundColor(ContainerGlobal[3], 255);
TextDrawFont(ContainerGlobal[3], 4);
TextDrawSetProportional(ContainerGlobal[3], 0);
TextDrawSetShadow(ContainerGlobal[3], 0);
TextDrawSetSelectable(ContainerGlobal[3], true);

ContainerGlobal[4] = TextDrawCreate(351.9053, 305.5000, "LD_SPAC:white"); // пусто
TextDrawTextSize(ContainerGlobal[4], 47.0000, 13.0000);
TextDrawAlignment(ContainerGlobal[4], 1);
TextDrawColor(ContainerGlobal[4], 192535039);
TextDrawBackgroundColor(ContainerGlobal[4], 255);
TextDrawFont(ContainerGlobal[4], 4);
TextDrawSetProportional(ContainerGlobal[4], 0);
TextDrawSetShadow(ContainerGlobal[4], 0);
TextDrawSetSelectable(ContainerGlobal[4], true);

ContainerGlobal[5] = TextDrawCreate(250.4999, 305.5625, "OPEN"); // пусто
TextDrawLetterSize(ContainerGlobal[5], 0.2394, 1.2762);
TextDrawAlignment(ContainerGlobal[5], 1);
TextDrawColor(ContainerGlobal[5], -1378294017);
TextDrawBackgroundColor(ContainerGlobal[5], 255);
TextDrawFont(ContainerGlobal[5], 2);
TextDrawSetProportional(ContainerGlobal[5], 1);
TextDrawSetShadow(ContainerGlobal[5], 0);

ContainerGlobal[6] = TextDrawCreate(364.9053, 305.5000, "EXIT"); // пусто
TextDrawLetterSize(ContainerGlobal[6], 0.2394, 1.2762);
TextDrawAlignment(ContainerGlobal[6], 1);
TextDrawColor(ContainerGlobal[6], -1378294017);
TextDrawBackgroundColor(ContainerGlobal[6], 255);
TextDrawFont(ContainerGlobal[6], 2);
TextDrawSetProportional(ContainerGlobal[6], 1);
TextDrawSetShadow(ContainerGlobal[6], 0);

ContainerGlobal[7] = TextDrawCreate(209.2998, 207.1625, ""); // пусто
TextDrawTextSize(ContainerGlobal[7], 106.0000, 99.0000);
TextDrawAlignment(ContainerGlobal[7], 1);
TextDrawColor(ContainerGlobal[7], -1);
TextDrawFont(ContainerGlobal[7], 5);
TextDrawSetProportional(ContainerGlobal[7], 0);
TextDrawSetShadow(ContainerGlobal[7], 0);
TextDrawBoxColor(ContainerGlobal[7], 0x00000000);
TextDrawBackgroundColor(ContainerGlobal[7], 0x00000000);
TextDrawSetPreviewModel(ContainerGlobal[7], 19321);
TextDrawSetPreviewRot(ContainerGlobal[7], 180.0000, 0.0000, 0.0000, 1.0000);

ContainerGlobal[8] = TextDrawCreate(318.0000, 203.1873, ""); // пусто
TextDrawTextSize(ContainerGlobal[8], 114.0000, 109.0000);
TextDrawAlignment(ContainerGlobal[8], 1);
TextDrawColor(ContainerGlobal[8], -1);
TextDrawFont(ContainerGlobal[8], 5);
TextDrawSetProportional(ContainerGlobal[8], 0);
TextDrawSetShadow(ContainerGlobal[8], 0);
TextDrawBoxColor(ContainerGlobal[8], 0x00000000);
TextDrawBackgroundColor(ContainerGlobal[8], 0x00000000);
TextDrawSetPreviewModel(ContainerGlobal[8], 19321);
TextDrawSetPreviewRot(ContainerGlobal[8], 0.0000, 0.0000, 0.0000, 1.0000);

ContainerGlobal[9] = TextDrawCreate(188.1997, 225.4375, ""); // пусто
TextDrawTextSize(ContainerGlobal[9], 66.0000, 63.0000);
TextDrawAlignment(ContainerGlobal[9], 1);
TextDrawColor(ContainerGlobal[9], -1);
TextDrawFont(ContainerGlobal[9], 5);
TextDrawSetProportional(ContainerGlobal[9], 0);
TextDrawSetShadow(ContainerGlobal[9], 0);
TextDrawBoxColor(ContainerGlobal[9], 0x00000000);
TextDrawBackgroundColor(ContainerGlobal[9], 0x00000000);
TextDrawSetPreviewModel(ContainerGlobal[9], 3062);
TextDrawSetPreviewRot(ContainerGlobal[9], 0.0000, 0.0000, 50.0000, 1.0000);

ContainerGlobal[10] = TextDrawCreate(243.1997, 225.4375, ""); // пусто
TextDrawTextSize(ContainerGlobal[10], 66.0000, 63.0000);
TextDrawAlignment(ContainerGlobal[10], 1);
TextDrawColor(ContainerGlobal[10], -1);
TextDrawFont(ContainerGlobal[10], 5);
TextDrawSetProportional(ContainerGlobal[10], 0);
TextDrawSetShadow(ContainerGlobal[10], 0);
TextDrawBoxColor(ContainerGlobal[10], 0x00000000);
TextDrawBackgroundColor(ContainerGlobal[10], 0x00000000);
TextDrawSetPreviewModel(ContainerGlobal[10], 3062);
TextDrawSetPreviewRot(ContainerGlobal[10], 0.0000, 0.0000, 115.0000, 1.0000);

ContainerGlobal[11] = TextDrawCreate(361.7001, 268.7500, "/"); // пусто
TextDrawLetterSize(ContainerGlobal[11], 0.7099, 2.6543);
TextDrawAlignment(ContainerGlobal[11], 1);
TextDrawColor(ContainerGlobal[11], -16776961);
TextDrawBackgroundColor(ContainerGlobal[11], 255);
TextDrawFont(ContainerGlobal[11], 1);
TextDrawSetProportional(ContainerGlobal[11], 1);
TextDrawSetShadow(ContainerGlobal[11], 0);

ContainerGlobal[12] = TextDrawCreate(366.2004, 254.1491, "/"); // пусто
TextDrawLetterSize(ContainerGlobal[12], 0.7099, 2.6543);
TextDrawAlignment(ContainerGlobal[12], 1);
TextDrawColor(ContainerGlobal[12], -16776961);
TextDrawBackgroundColor(ContainerGlobal[12], 255);
TextDrawFont(ContainerGlobal[12], 1);
TextDrawSetProportional(ContainerGlobal[12], 1);
TextDrawSetShadow(ContainerGlobal[12], 0);

ContainerGlobal[13] = TextDrawCreate(370.7007, 238.8481, "/"); // пусто
TextDrawLetterSize(ContainerGlobal[13], 0.7099, 2.6543);
TextDrawAlignment(ContainerGlobal[13], 1);
TextDrawColor(ContainerGlobal[13], -16776961);
TextDrawBackgroundColor(ContainerGlobal[13], 255);
TextDrawFont(ContainerGlobal[13], 1);
TextDrawSetProportional(ContainerGlobal[13], 1);
TextDrawSetShadow(ContainerGlobal[13], 0);

ContainerGlobal[14] = TextDrawCreate(375.4007, 224.2856, "/"); // пусто
TextDrawLetterSize(ContainerGlobal[14], 0.7099, 2.6543);
TextDrawAlignment(ContainerGlobal[14], 1);
TextDrawColor(ContainerGlobal[14], -16776961);
TextDrawBackgroundColor(ContainerGlobal[14], 255);
TextDrawFont(ContainerGlobal[14], 1);
TextDrawSetProportional(ContainerGlobal[14], 1);
TextDrawSetShadow(ContainerGlobal[14], 0);

ContainerGlobal[15] = TextDrawCreate(377.6008, 217.7852, "/"); // пусто
TextDrawLetterSize(ContainerGlobal[15], 0.7099, 2.6543);
TextDrawAlignment(ContainerGlobal[15], 1);
TextDrawColor(ContainerGlobal[15], -16776961);
TextDrawBackgroundColor(ContainerGlobal[15], 255);
TextDrawFont(ContainerGlobal[15], 1);
TextDrawSetProportional(ContainerGlobal[15], 1);
TextDrawSetShadow(ContainerGlobal[15], 0);

ContainerGlobal[16] = TextDrawCreate(224.5000, 206.6250, ""); // пусто
TextDrawTextSize(ContainerGlobal[16], 38.0000, 44.0000);
TextDrawAlignment(ContainerGlobal[16], 1);
TextDrawColor(ContainerGlobal[16], -1);
TextDrawFont(ContainerGlobal[16], 5);
TextDrawSetProportional(ContainerGlobal[16], 0);
TextDrawSetShadow(ContainerGlobal[16], 0);
TextDrawBoxColor(ContainerGlobal[16], 0x00000000);
TextDrawBackgroundColor(ContainerGlobal[16], 0x00000000);
TextDrawSetPreviewModel(ContainerGlobal[16], 19336);
TextDrawSetPreviewRot(ContainerGlobal[16], 0.0000, 0.0000, 0.0000, 1.0000);

ContainerGlobal[17] = TextDrawCreate(225.9999, 218.2374, ""); // пусто
TextDrawTextSize(ContainerGlobal[17], 74.0000, 97.0000);
TextDrawAlignment(ContainerGlobal[17], 1);
TextDrawColor(ContainerGlobal[17], -1);
TextDrawFont(ContainerGlobal[17], 5);
TextDrawSetProportional(ContainerGlobal[17], 0);
TextDrawSetShadow(ContainerGlobal[17], 0);
TextDrawSetPreviewModel(ContainerGlobal[17], 560);
TextDrawBoxColor(ContainerGlobal[17], 0x00000000);
TextDrawBackgroundColor(ContainerGlobal[17], 0x00000000);
TextDrawSetPreviewRot(ContainerGlobal[17], 0.0000, 0.0000, 0.0000, 1.0000);
TextDrawSetPreviewVehCol(ContainerGlobal[17], 3, 1);

ContainerGlobal[18] = TextDrawCreate(212.4999, 248.8624, ""); // пусто
TextDrawTextSize(ContainerGlobal[18], 49.0000, 34.0000);
TextDrawAlignment(ContainerGlobal[18], 1);
TextDrawColor(ContainerGlobal[18], -1);
TextDrawFont(ContainerGlobal[18], 5);
TextDrawSetProportional(ContainerGlobal[18], 0);
TextDrawSetShadow(ContainerGlobal[18], 0);
TextDrawBoxColor(ContainerGlobal[18], 0x00000000);
TextDrawBackgroundColor(ContainerGlobal[18], 0x00000000);
TextDrawSetPreviewModel(ContainerGlobal[18], 203);
TextDrawSetPreviewRot(ContainerGlobal[18], 0.0000, 0.0000, 30.0000, 1.0000);

ContainerGlobal[19] = TextDrawCreate(262.4999, 248.8624, ""); // пусто
TextDrawTextSize(ContainerGlobal[19], 49.0000, 34.0000);
TextDrawAlignment(ContainerGlobal[19], 1);
TextDrawColor(ContainerGlobal[19], -1);
TextDrawFont(ContainerGlobal[19], 5);
TextDrawSetProportional(ContainerGlobal[19], 0);
TextDrawSetShadow(ContainerGlobal[19], 0);
TextDrawBoxColor(ContainerGlobal[19], 0x00000000);
TextDrawBackgroundColor(ContainerGlobal[19], 0x00000000);
TextDrawSetPreviewModel(ContainerGlobal[19], 271);
TextDrawSetPreviewRot(ContainerGlobal[19], 0.0000, 0.0000, 320.0000, 1.0000);

ContainerGlobal[20] = TextDrawCreate(205.4000, 168.1374, "LD_BEAT:CHIT"); // пусто
TextDrawTextSize(ContainerGlobal[20], 15.0000, 17.0000);
TextDrawAlignment(ContainerGlobal[20], 1);
TextDrawColor(ContainerGlobal[20], 674248703);
TextDrawBackgroundColor(ContainerGlobal[20], 255);
TextDrawFont(ContainerGlobal[20], 4);
TextDrawSetProportional(ContainerGlobal[20], 0);
TextDrawSetShadow(ContainerGlobal[20], 0);

ContainerGlobal[21] = TextDrawCreate(417.3008, 168.1999, "LD_BEAT:CHIT"); // пусто
TextDrawTextSize(ContainerGlobal[21], 15.0000, 17.0000);
TextDrawAlignment(ContainerGlobal[21], 1);
TextDrawColor(ContainerGlobal[21], 674248703);
TextDrawBackgroundColor(ContainerGlobal[21], 255);
TextDrawFont(ContainerGlobal[21], 4);
TextDrawSetProportional(ContainerGlobal[21], 0);
TextDrawSetShadow(ContainerGlobal[21], 0);

ContainerGlobal[22] = TextDrawCreate(215.3000, 172.4757, "Box"); // пусто
TextDrawLetterSize(ContainerGlobal[22], 0.0000, 1.5779);
TextDrawTextSize(ContainerGlobal[22], 423.0000, 0.0000);
TextDrawAlignment(ContainerGlobal[22], 1);
TextDrawColor(ContainerGlobal[22], -1);
TextDrawUseBox(ContainerGlobal[22], 1);
TextDrawBoxColor(ContainerGlobal[22], 674248703);
TextDrawBackgroundColor(ContainerGlobal[22], 255);
TextDrawFont(ContainerGlobal[22], 1);
TextDrawSetProportional(ContainerGlobal[22], 1);
TextDrawSetShadow(ContainerGlobal[22], 0);

ContainerGlobal[23] = TextDrawCreate(295.0001, 170.4874, "GENUINE_"); // пусто
TextDrawLetterSize(ContainerGlobal[23], 0.3115, 1.3725);
TextDrawAlignment(ContainerGlobal[23], 1);
TextDrawColor(ContainerGlobal[23], -1378294017);
TextDrawBackgroundColor(ContainerGlobal[23], 255);
TextDrawFont(ContainerGlobal[23], 2);
TextDrawSetProportional(ContainerGlobal[23], 1);
TextDrawSetShadow(ContainerGlobal[23], 0);

ContainerGlobal[24] = TextDrawCreate(288.1001, 181.3506, "CONTAINER"); // пусто
TextDrawLetterSize(ContainerGlobal[24], 0.2935, 1.3112);
TextDrawAlignment(ContainerGlobal[24], 1);
TextDrawColor(ContainerGlobal[24], -2139062017);
TextDrawBackgroundColor(ContainerGlobal[24], 255);
TextDrawFont(ContainerGlobal[24], 2);
TextDrawSetProportional(ContainerGlobal[24], 1);
TextDrawSetShadow(ContainerGlobal[24], 0);