GenuineResourse_TD[0] = TextDrawCreate(186.2500, 324.7500, "LD_BEAT:chit"); // ?????
TextDrawTextSize(GenuineResourse_TD[0], 77.0000, 75.0000);
TextDrawAlignment(GenuineResourse_TD[0], 1);
TextDrawColor(GenuineResourse_TD[0], -1523963137);
TextDrawBackgroundColor(GenuineResourse_TD[0], 255);
TextDrawFont(GenuineResourse_TD[0], 4);
TextDrawSetProportional(GenuineResourse_TD[0], 0);
TextDrawSetShadow(GenuineResourse_TD[0], 0);

GenuineResourse_TD[1] = TextDrawCreate(226.2500, 338.7499, "Box"); // ?????
TextDrawLetterSize(GenuineResourse_TD[1], 0.0000, 5.1875);
TextDrawTextSize(GenuineResourse_TD[1], 386.0000, 0.0000);
TextDrawAlignment(GenuineResourse_TD[1], 1);
TextDrawColor(GenuineResourse_TD[1], -1523963137);
TextDrawUseBox(GenuineResourse_TD[1], 1);
TextDrawBoxColor(GenuineResourse_TD[1], -1523963137);
TextDrawBackgroundColor(GenuineResourse_TD[1], 255);
TextDrawFont(GenuineResourse_TD[1], 1);
TextDrawSetProportional(GenuineResourse_TD[1], 1);
TextDrawSetShadow(GenuineResourse_TD[1], 0);

GenuineResourse_TD[2] = TextDrawCreate(350.0000, 324.7499, "LD_BEAT:chit"); // ?????
TextDrawTextSize(GenuineResourse_TD[2], 77.0000, 75.0000);
TextDrawAlignment(GenuineResourse_TD[2], 1);
TextDrawColor(GenuineResourse_TD[2], -1523963137);
TextDrawBackgroundColor(GenuineResourse_TD[2], 255);
TextDrawFont(GenuineResourse_TD[2], 4);
TextDrawSetProportional(GenuineResourse_TD[2], 0);
TextDrawSetShadow(GenuineResourse_TD[2], 0);

GenuineResourse_TD[3] = TextDrawCreate(190.0000, 327.6665, "LD_BEAT:chit"); // ?????
TextDrawTextSize(GenuineResourse_TD[3], 68.0000, 69.0000);
TextDrawAlignment(GenuineResourse_TD[3], 1);
TextDrawColor(GenuineResourse_TD[3], 1044333055);
TextDrawBackgroundColor(GenuineResourse_TD[3], 255);
TextDrawFont(GenuineResourse_TD[3], 4);
TextDrawSetProportional(GenuineResourse_TD[3], 0);
TextDrawSetShadow(GenuineResourse_TD[3], 0);

GenuineResourse_TD[4] = TextDrawCreate(229.3750, 341.0830, "Box"); // ?????
TextDrawLetterSize(GenuineResourse_TD[4], 0.0000, 4.6250);
TextDrawTextSize(GenuineResourse_TD[4], 389.0000, 0.0000);
TextDrawAlignment(GenuineResourse_TD[4], 1);
TextDrawColor(GenuineResourse_TD[4], -2139062017);
TextDrawUseBox(GenuineResourse_TD[4], 1);
TextDrawBoxColor(GenuineResourse_TD[4], 1044333055);
TextDrawBackgroundColor(GenuineResourse_TD[4], 255);
TextDrawFont(GenuineResourse_TD[4], 1);
TextDrawSetProportional(GenuineResourse_TD[4], 1);
TextDrawSetShadow(GenuineResourse_TD[4], 0);

GenuineResourse_TD[5] = TextDrawCreate(355.6250, 327.6665, "LD_BEAT:chit"); // ?????
TextDrawTextSize(GenuineResourse_TD[5], 68.0000, 69.0000);
TextDrawAlignment(GenuineResourse_TD[5], 1);
TextDrawColor(GenuineResourse_TD[5], 1044333055);
TextDrawBackgroundColor(GenuineResourse_TD[5], 255);
TextDrawFont(GenuineResourse_TD[5], 4);
TextDrawSetProportional(GenuineResourse_TD[5], 0);
TextDrawSetShadow(GenuineResourse_TD[5], 0);

GenuineResourse_TD[6] = TextDrawCreate(207.5000, 327.6665, ""); // ?????
TextDrawTextSize(GenuineResourse_TD[6], 51.0000, 48.0000);
TextDrawAlignment(GenuineResourse_TD[6], 1);
TextDrawColor(GenuineResourse_TD[6], -1);
TextDrawFont(GenuineResourse_TD[6], 5);
TextDrawSetProportional(GenuineResourse_TD[6], 0);
TextDrawSetShadow(GenuineResourse_TD[6], 0);
TextDrawBoxColor(GenuineResourse_TD[6], 0x00000000);
TextDrawBackgroundColor(GenuineResourse_TD[6], 0x00000000);
TextDrawSetSelectable(GenuineResourse_TD[6], true);
TextDrawSetPreviewModel(GenuineResourse_TD[6], 1212);
TextDrawSetPreviewRot(GenuineResourse_TD[6], 50.0000, 0.0000, 0.0000, 1.0000);

GenuineResourse_TD[7] = TextDrawCreate(217.5000, 365.5834, "MONEY"); // ?????
TextDrawLetterSize(GenuineResourse_TD[7], 0.2574, 1.0923);
TextDrawAlignment(GenuineResourse_TD[7], 1);
TextDrawColor(GenuineResourse_TD[7], -6749953);
TextDrawBackgroundColor(GenuineResourse_TD[7], 255);
TextDrawFont(GenuineResourse_TD[7], 1);
TextDrawSetProportional(GenuineResourse_TD[7], 1);
TextDrawSetShadow(GenuineResourse_TD[7], 0);

GenuineResourse_TD[8] = TextDrawCreate(261.2500, 337.5834, ""); // ?????
TextDrawTextSize(GenuineResourse_TD[8], 35.0000, 32.0000);
TextDrawAlignment(GenuineResourse_TD[8], 1);
TextDrawColor(GenuineResourse_TD[8], -1);
TextDrawFont(GenuineResourse_TD[8], 5);
TextDrawSetProportional(GenuineResourse_TD[8], 0);
TextDrawSetShadow(GenuineResourse_TD[8], 0);
TextDrawBoxColor(GenuineResourse_TD[8], 0x00000000);
TextDrawBackgroundColor(GenuineResourse_TD[8], 0x00000000);
TextDrawSetSelectable(GenuineResourse_TD[8], true);
TextDrawSetPreviewModel(GenuineResourse_TD[8], 1240);
TextDrawSetPreviewRot(GenuineResourse_TD[8], 0.0000, 0.0000, 0.0000, 1.0000);

GenuineResourse_TD[9] = TextDrawCreate(266.2500, 365.5833, "MEDIC"); // ?????
TextDrawLetterSize(GenuineResourse_TD[9], 0.2673, 1.1741);
TextDrawAlignment(GenuineResourse_TD[9], 1);
TextDrawColor(GenuineResourse_TD[9], -6749953);
TextDrawBackgroundColor(GenuineResourse_TD[9], 255);
TextDrawFont(GenuineResourse_TD[9], 1);
TextDrawSetProportional(GenuineResourse_TD[9], 1);
TextDrawSetShadow(GenuineResourse_TD[9], 0);

GenuineResourse_TD[10] = TextDrawCreate(301.9749, 332.7765, ""); // ?????
TextDrawTextSize(GenuineResourse_TD[10], 43.0000, 36.0000);
TextDrawAlignment(GenuineResourse_TD[10], 1);
TextDrawColor(GenuineResourse_TD[10], -1);
TextDrawFont(GenuineResourse_TD[10], 5);
TextDrawSetProportional(GenuineResourse_TD[10], 0);
TextDrawSetShadow(GenuineResourse_TD[10], 0);
TextDrawBoxColor(GenuineResourse_TD[10], 0x00000000);
TextDrawBackgroundColor(GenuineResourse_TD[10], 0x00000000);
TextDrawSetSelectable(GenuineResourse_TD[10], true);
TextDrawSetPreviewModel(GenuineResourse_TD[10], 1580);
TextDrawSetPreviewRot(GenuineResourse_TD[10], 90.0000, 0.0000, 0.0000, 1.0000);

GenuineResourse_TD[11] = TextDrawCreate(310.6250, 364.9999, "DRUGS"); // ?????
TextDrawLetterSize(GenuineResourse_TD[11], 0.2673, 1.1741);
TextDrawAlignment(GenuineResourse_TD[11], 1);
TextDrawColor(GenuineResourse_TD[11], -6749953);
TextDrawBackgroundColor(GenuineResourse_TD[11], 255);
TextDrawFont(GenuineResourse_TD[11], 1);
TextDrawSetProportional(GenuineResourse_TD[11], 1);
TextDrawSetShadow(GenuineResourse_TD[11], 0);

GenuineResourse_TD[12] = TextDrawCreate(330.6250, 308.4165, ""); // ?????
TextDrawTextSize(GenuineResourse_TD[12], 90.0000, 90.0000);
TextDrawAlignment(GenuineResourse_TD[12], 1);
TextDrawColor(GenuineResourse_TD[12], -1);
TextDrawFont(GenuineResourse_TD[12], 5);
TextDrawSetProportional(GenuineResourse_TD[12], 0);
TextDrawSetShadow(GenuineResourse_TD[12], 0);
TextDrawBoxColor(GenuineResourse_TD[12], 0x00000000);
TextDrawBackgroundColor(GenuineResourse_TD[12], 0x00000000);
TextDrawSetSelectable(GenuineResourse_TD[12], true);
TextDrawSetPreviewModel(GenuineResourse_TD[12], 11746);
TextDrawSetPreviewRot(GenuineResourse_TD[12], 0.0000, 0.0000, 0.0000, 1.0000);

GenuineResourse_TD[13] = TextDrawCreate(359.3750, 364.9999, "CAR_KEY"); // ?????
TextDrawLetterSize(GenuineResourse_TD[13], 0.2673, 1.1741);
TextDrawAlignment(GenuineResourse_TD[13], 1);
TextDrawColor(GenuineResourse_TD[13], -6749953);
TextDrawBackgroundColor(GenuineResourse_TD[13], 255);
TextDrawFont(GenuineResourse_TD[13], 1);
TextDrawSetProportional(GenuineResourse_TD[13], 1);
TextDrawSetShadow(GenuineResourse_TD[13], 0);

GenuineResourse_TD[14] = TextDrawCreate(282.5000, 297.9165, "LD_BEAT:chit"); // ?????
TextDrawTextSize(GenuineResourse_TD[14], 47.0000, 41.0000);
TextDrawAlignment(GenuineResourse_TD[14], 1);
TextDrawColor(GenuineResourse_TD[14], -6749953);
TextDrawBackgroundColor(GenuineResourse_TD[14], 255);
TextDrawFont(GenuineResourse_TD[14], 4);
TextDrawSetProportional(GenuineResourse_TD[14], 0);
TextDrawSetShadow(GenuineResourse_TD[14], 0);

GenuineResourse_TD[15] = TextDrawCreate(294.0000, 310.8959, "CHOOSE~n~ACTION"); // ?????
TextDrawLetterSize(GenuineResourse_TD[15], 0.2018, 0.7774);
TextDrawAlignment(GenuineResourse_TD[15], 1);
TextDrawColor(GenuineResourse_TD[15], -1523963137);
TextDrawBackgroundColor(GenuineResourse_TD[15], 255);
TextDrawFont(GenuineResourse_TD[15], 1);
TextDrawSetProportional(GenuineResourse_TD[15], 1);
TextDrawSetShadow(GenuineResourse_TD[15], 0);