GreenZone[0] = TextDrawCreate(62.7672, 311.9165, "Box"); // ?????
TextDrawLetterSize(GreenZone[0], 0.0000, 1.8473);
TextDrawTextSize(GreenZone[0], 116.0000, 0.0000);
TextDrawAlignment(GreenZone[0], 1);
TextDrawColor(GreenZone[0], -1);
TextDrawUseBox(GreenZone[0], 1);
TextDrawBoxColor(GreenZone[0], 2042031103);
TextDrawBackgroundColor(GreenZone[0], 255);
TextDrawFont(GreenZone[0], 1);
TextDrawSetProportional(GreenZone[0], 1);
TextDrawSetShadow(GreenZone[0], 0);

GreenZone[1] = TextDrawCreate(55.5079, 306.7500, "LD_BEAT:chit"); // ?????
TextDrawTextSize(GreenZone[1], 14.0000, 16.0000);
TextDrawAlignment(GreenZone[1], 1);
TextDrawColor(GreenZone[1], 2042031103);
TextDrawBackgroundColor(GreenZone[1], 255);
TextDrawFont(GreenZone[1], 4);
TextDrawSetProportional(GreenZone[1], 0);
TextDrawSetShadow(GreenZone[1], 0);

GreenZone[2] = TextDrawCreate(106.5139, 306.2290, "LD_BEAT:chit"); // ?????
TextDrawTextSize(GreenZone[2], 17.0000, 16.0000);
TextDrawAlignment(GreenZone[2], 1);
TextDrawColor(GreenZone[2], 2042031103);
TextDrawBackgroundColor(GreenZone[2], 255);
TextDrawFont(GreenZone[2], 4);
TextDrawSetProportional(GreenZone[2], 0);
TextDrawSetShadow(GreenZone[2], 0);

GreenZone[3] = TextDrawCreate(64.2779, 310.2666, "Box"); // ?????
TextDrawLetterSize(GreenZone[3], 0.0000, 1.5197);
TextDrawTextSize(GreenZone[3], 112.0000, 0.0000);
TextDrawAlignment(GreenZone[3], 1);
TextDrawColor(GreenZone[3], -1);
TextDrawUseBox(GreenZone[3], 1);
TextDrawBoxColor(GreenZone[3], 2042031103);
TextDrawBackgroundColor(GreenZone[3], 255);
TextDrawFont(GreenZone[3], 1);
TextDrawSetProportional(GreenZone[3], 1);
TextDrawSetShadow(GreenZone[3], 0);

GreenZone[4] = TextDrawCreate(59.5931, 317.2666, "Box"); // ?????
TextDrawLetterSize(GreenZone[4], 0.0000, 1.2855);
TextDrawTextSize(GreenZone[4], 105.0000, 0.0000);
TextDrawAlignment(GreenZone[4], 1);
TextDrawColor(GreenZone[4], -1);
TextDrawUseBox(GreenZone[4], 1);
TextDrawBoxColor(GreenZone[4], 2042031103);
TextDrawBackgroundColor(GreenZone[4], 255);
TextDrawFont(GreenZone[4], 1);
TextDrawSetProportional(GreenZone[4], 1);
TextDrawSetShadow(GreenZone[4], 0);

GreenZone[5] = TextDrawCreate(75.7543, 316.3330, "Box"); // ?????
TextDrawLetterSize(GreenZone[5], 0.0000, 1.3789);
TextDrawTextSize(GreenZone[5], 119.0000, 0.0000);
TextDrawAlignment(GreenZone[5], 1);
TextDrawColor(GreenZone[5], -1);
TextDrawUseBox(GreenZone[5], 1);
TextDrawBoxColor(GreenZone[5], 2042031103);
TextDrawBackgroundColor(GreenZone[5], 255);
TextDrawFont(GreenZone[5], 1);
TextDrawSetProportional(GreenZone[5], 1);
TextDrawSetShadow(GreenZone[5], 0);

GreenZone[6] = TextDrawCreate(58.5998, 294.6997, "LD_SPAC:layer"); // ?????
TextDrawTextSize(GreenZone[6], 65.0000, 48.0000);
TextDrawAlignment(GreenZone[6], 1);
TextDrawColor(GreenZone[6], -1);
TextDrawBackgroundColor(GreenZone[6], 255);
TextDrawFont(GreenZone[6], 4);
TextDrawSetProportional(GreenZone[6], 0);
TextDrawSetShadow(GreenZone[6], 0);

GreenZone[7] = TextDrawCreate(54.5998, 287.4999, "particle:lamp_shad_64"); // ?????
TextDrawTextSize(GreenZone[7], 71.0000, 42.0000);
TextDrawAlignment(GreenZone[7], 1);
TextDrawColor(GreenZone[7], -190);
TextDrawBackgroundColor(GreenZone[7], 255);
TextDrawFont(GreenZone[7], 4);
TextDrawSetProportional(GreenZone[7], 0);
TextDrawSetShadow(GreenZone[7], 0);

GreenZone[8] = TextDrawCreate(62.4999, 313.0747, "GREEN_ZONE"); // ?????
TextDrawLetterSize(GreenZone[8], 0.2945, 1.2540);
TextDrawAlignment(GreenZone[8], 1);
TextDrawColor(GreenZone[8], -1);
TextDrawBackgroundColor(GreenZone[8], 255);
TextDrawFont(GreenZone[8], 1);
TextDrawSetProportional(GreenZone[8], 1);
TextDrawSetShadow(GreenZone[8], 0);
