GunWFood_TD[0] = TextDrawCreate(333.6729, 135.7837, ""); // ?????
TextDrawTextSize(GunWFood_TD[0], 90.0000, 74.1100);
TextDrawAlignment(GunWFood_TD[0], 1);
TextDrawColor(GunWFood_TD[0], -1);
TextDrawFont(GunWFood_TD[0], 5);
TextDrawSetProportional(GunWFood_TD[0], 0);
TextDrawSetShadow(GunWFood_TD[0], 0);
TextDrawSetPreviewModel(GunWFood_TD[0], 356);
TextDrawSetPreviewRot(GunWFood_TD[0], 0.0000, 360.0000, 195.0000, 1.8988);

GunWFood_TD[1] = TextDrawCreate(332.7847, 167.5330, ""); // ?????
TextDrawTextSize(GunWFood_TD[1], 57.0000, 55.0000);
TextDrawAlignment(GunWFood_TD[1], 1);
TextDrawColor(GunWFood_TD[1], -1);
TextDrawBackgroundColor(GunWFood_TD[1], 268435456);
TextDrawFont(GunWFood_TD[1], 5);
TextDrawSetProportional(GunWFood_TD[1], 0);
TextDrawSetShadow(GunWFood_TD[1], 0);
TextDrawSetPreviewModel(GunWFood_TD[1], 348);
TextDrawSetPreviewRot(GunWFood_TD[1], 0.0000, 360.0000, 188.0000, 1.0000);

GunWFood_TD[2] = TextDrawCreate(373.0190, 176.0332, ""); // ?????
TextDrawTextSize(GunWFood_TD[2], 45.0000, 42.0000);
TextDrawAlignment(GunWFood_TD[2], 1);
TextDrawColor(GunWFood_TD[2], -1);
TextDrawBackgroundColor(GunWFood_TD[2], 268435456);
TextDrawFont(GunWFood_TD[2], 5);
TextDrawSetProportional(GunWFood_TD[2], 0);
TextDrawSetShadow(GunWFood_TD[2], 0);
TextDrawSetPreviewModel(GunWFood_TD[2], 353);
TextDrawSetPreviewRot(GunWFood_TD[2], 0.0000, 360.0000, 188.0000, 1.0000);

GunWFood_TD[3] = TextDrawCreate(353.8818, 187.1999, ""); // ?????
TextDrawTextSize(GunWFood_TD[3], 42.0000, 57.0000);
TextDrawAlignment(GunWFood_TD[3], 1);
TextDrawColor(GunWFood_TD[3], -1);
TextDrawFont(GunWFood_TD[3], 5);
TextDrawSetProportional(GunWFood_TD[3], 0);
TextDrawSetShadow(GunWFood_TD[3], 0);
TextDrawSetPreviewModel(GunWFood_TD[3], 2768);
TextDrawSetPreviewRot(GunWFood_TD[3], 0.0000, 360.0000, 118.0000, 1.0000);

GunWFood_TD[4] = TextDrawCreate(388.7525, 201.3999, ""); // ?????
TextDrawTextSize(GunWFood_TD[4], 40.0000, 29.0000);
TextDrawAlignment(GunWFood_TD[4], 1);
TextDrawColor(GunWFood_TD[4], -1);
TextDrawFont(GunWFood_TD[4], 5);
TextDrawSetProportional(GunWFood_TD[4], 0);
TextDrawSetShadow(GunWFood_TD[4], 0);
TextDrawSetPreviewModel(GunWFood_TD[4], 19563);
TextDrawSetPreviewRot(GunWFood_TD[4], 0.0000, 360.0000, 0.0000, 1.0000);
