JetX_Info[0] = TextDrawCreate(223.484634, 130.083343, "LD_SPAC:white");
TextDrawLetterSize(JetX_Info[0], 0.000000, 0.000000);
TextDrawTextSize(JetX_Info[0], 186.939987, 227.499969);
TextDrawAlignment(JetX_Info[0], 1);
TextDrawColor(JetX_Info[0], 589505535);
TextDrawSetShadow(JetX_Info[0], 0);
TextDrawSetOutline(JetX_Info[0], 0);
TextDrawFont(JetX_Info[0], 4);

JetX_Info[1] = TextDrawCreate(296.574188, 130.666702, "JetX");
TextDrawLetterSize(JetX_Info[1], 0.449999, 1.600000);
TextDrawAlignment(JetX_Info[1], 1);
TextDrawColor(JetX_Info[1], -5963521);
TextDrawSetShadow(JetX_Info[1], 1);
TextDrawSetOutline(JetX_Info[1], 0);
TextDrawBackgroundColor(JetX_Info[1], 51);
TextDrawFont(JetX_Info[1], 1);
TextDrawSetProportional(JetX_Info[1], 1);

JetX_Info[2] = TextDrawCreate(278.301544, 225.750000, "LD_SPAC:white");
TextDrawLetterSize(JetX_Info[2], 0.000000, 0.000000);
TextDrawTextSize(JetX_Info[2], 73.557830, 34.416656);
TextDrawAlignment(JetX_Info[2], 1);
TextDrawColor(JetX_Info[2], 1515871519);
TextDrawSetShadow(JetX_Info[2], 0);
TextDrawSetOutline(JetX_Info[2], 0);
TextDrawFont(JetX_Info[2], 4);

JetX_Info[3] = TextDrawCreate(280.644348, 149.333343, "Genuine RolePlay");
TextDrawLetterSize(JetX_Info[3], 0.163265, 0.940831);
TextDrawAlignment(JetX_Info[3], 1);
TextDrawColor(JetX_Info[3], -1);
TextDrawSetShadow(JetX_Info[3], 1);
TextDrawSetOutline(JetX_Info[3], 0);
TextDrawBackgroundColor(JetX_Info[3], 51);
TextDrawFont(JetX_Info[3], 2);
TextDrawSetProportional(JetX_Info[3], 1);

JetX_Info[4] = TextDrawCreate(300.686645, 156.333328, "");
TextDrawLetterSize(JetX_Info[4], 0.151551, 1.010832);
TextDrawAlignment(JetX_Info[4], 1);
TextDrawColor(JetX_Info[4], -5963521);
TextDrawSetShadow(JetX_Info[4], 1);
TextDrawSetOutline(JetX_Info[4], 0);
TextDrawBackgroundColor(JetX_Info[4], 51);
TextDrawFont(JetX_Info[4], 2);
TextDrawSetProportional(JetX_Info[4], 1);

JetX_Info[5] = TextDrawCreate(230.512374, 173.249984, "DADET FSONI TAMASHIS DACKEBAMDE DA MOXSENIT TANXA");
TextDrawLetterSize(JetX_Info[5], 0.141713, 0.894166);
TextDrawAlignment(JetX_Info[5], 1);
TextDrawColor(JetX_Info[5], -1);
TextDrawSetShadow(JetX_Info[5], 1);
TextDrawSetOutline(JetX_Info[5], 0);
TextDrawBackgroundColor(JetX_Info[5], 51);
TextDrawFont(JetX_Info[5], 2);
TextDrawSetProportional(JetX_Info[5], 1);

JetX_Info[6] = TextDrawCreate(230.043838, 182.000000, "AFETQEBAMDE, FSONI UNDA IYOS 100$'dan 500.000'mde");
TextDrawLetterSize(JetX_Info[6], 0.147335, 0.911666);
TextDrawAlignment(JetX_Info[6], 1);
TextDrawColor(JetX_Info[6], -1);
TextDrawSetShadow(JetX_Info[6], 1);
TextDrawSetOutline(JetX_Info[6], 0);
TextDrawBackgroundColor(JetX_Info[6], 51);
TextDrawFont(JetX_Info[6], 2);
TextDrawSetProportional(JetX_Info[6], 1);

JetX_Info[7] = TextDrawCreate(315.315002, 211.166656, "MIMDINAREOBS FSONEBIS MIGEBA");
TextDrawLetterSize(JetX_Info[7], 0.262123, 1.308333);
TextDrawAlignment(JetX_Info[7], 2);
TextDrawColor(JetX_Info[7], -5963521);
TextDrawSetShadow(JetX_Info[7], 0);
TextDrawSetOutline(JetX_Info[7], 1);
TextDrawBackgroundColor(JetX_Info[7], 51);
TextDrawFont(JetX_Info[7], 3);
TextDrawSetProportional(JetX_Info[7], 1);

JetX_Info[8] = TextDrawCreate(314.377868, 231.583358, "~r~5.12 X");
TextDrawLetterSize(JetX_Info[8], 0.523558, 2.078332);
TextDrawAlignment(JetX_Info[8], 2);
TextDrawColor(JetX_Info[8], 8388863);
TextDrawSetShadow(JetX_Info[8], 1);
TextDrawSetOutline(JetX_Info[8], 0);
TextDrawBackgroundColor(JetX_Info[8], 51);
TextDrawFont(JetX_Info[8], 3);
TextDrawSetProportional(JetX_Info[8], 1);

JetX_Info[9] = TextDrawCreate(225.827239, 269.500000, "LD_SPAC:white");
TextDrawLetterSize(JetX_Info[9], 0.000000, 0.000000);
TextDrawTextSize(JetX_Info[9], 182.723297, 12.833312);
TextDrawAlignment(JetX_Info[9], 1);
TextDrawColor(JetX_Info[9], 1515871519);
TextDrawSetShadow(JetX_Info[9], 0);
TextDrawSetOutline(JetX_Info[9], 0);
TextDrawFont(JetX_Info[9], 4);

JetX_Info[10] = TextDrawCreate(226.295761, 270.666687, "LD_SPAC:white");
TextDrawLetterSize(JetX_Info[10], 0.000000, 0.000000);
TextDrawTextSize(JetX_Info[10], 181.00000, 10.500000);
TextDrawAlignment(JetX_Info[10], 1);
TextDrawColor(JetX_Info[10], 8388863);
TextDrawSetShadow(JetX_Info[10], 0);
TextDrawSetOutline(JetX_Info[10], 0);
TextDrawFont(JetX_Info[10], 4);

JetX_Info[11] = TextDrawCreate(291.420227, 340.083312, "LD_SPAC:white");
TextDrawLetterSize(JetX_Info[11], 0.000000, 0.000000);
TextDrawTextSize(JetX_Info[11], 50.600280, 14.000000);
TextDrawAlignment(JetX_Info[11], 1);
TextDrawColor(JetX_Info[11],1515871519);
TextDrawSetShadow(JetX_Info[11], 0);
TextDrawSetOutline(JetX_Info[11], 0);
TextDrawFont(JetX_Info[11], 4);
TextDrawSetSelectable(JetX_Info[11], true);

JetX_Info[12] = TextDrawCreate(297.979827, 342.416809, "GATISHVA");
TextDrawLetterSize(JetX_Info[12], 0.181068, 0.888333);
TextDrawAlignment(JetX_Info[12], 1);
TextDrawColor(JetX_Info[12], -5963521);
TextDrawUseBox(JetX_Info[12], true);
TextDrawBoxColor(JetX_Info[12], 0);
TextDrawSetShadow(JetX_Info[12], 1);
TextDrawSetOutline(JetX_Info[12], 0);
TextDrawBackgroundColor(JetX_Info[12], 51);
TextDrawFont(JetX_Info[12], 2);
TextDrawSetProportional(JetX_Info[12], 1);