	Lugage_TD[0] = TextDrawCreate(442.7377, 302.0000, "Box"); // ?????
	TextDrawLetterSize(Lugage_TD[0], 0.0000, -0.1668);
	TextDrawTextSize(Lugage_TD[0], 506.0000, 0.0000);
	TextDrawAlignment(Lugage_TD[0], 1);
	TextDrawColor(Lugage_TD[0], -1);
	TextDrawUseBox(Lugage_TD[0], 1);
	TextDrawBoxColor(Lugage_TD[0], -1023398401);
	TextDrawBackgroundColor(Lugage_TD[0], 255);
	TextDrawFont(Lugage_TD[0], 1);
	TextDrawSetProportional(Lugage_TD[0], 1);
	TextDrawSetShadow(Lugage_TD[0], 0);

	Lugage_TD[1] = TextDrawCreate(436.6466, 285.0833, "Box"); // ?????
	TextDrawLetterSize(Lugage_TD[1], 0.0000, 12.2957);
	TextDrawTextSize(Lugage_TD[1], 618.0000, 0.0000);
	TextDrawAlignment(Lugage_TD[1], 1);
	TextDrawColor(Lugage_TD[1], -1);
	TextDrawUseBox(Lugage_TD[1], 1);
	TextDrawBoxColor(Lugage_TD[1], 4607);
	TextDrawBackgroundColor(Lugage_TD[1], 255);
	TextDrawFont(Lugage_TD[1], 1);
	TextDrawSetProportional(Lugage_TD[1], 1);
	TextDrawSetShadow(Lugage_TD[1], 0);

	Lugage_TD[2] = TextDrawCreate(436.4153, 296.1665, "Box"); // ?????
	TextDrawLetterSize(Lugage_TD[2], 0.0000, -0.6424);
	TextDrawTextSize(Lugage_TD[2], 618.2791, 0.0000);
	TextDrawAlignment(Lugage_TD[2], 1);
	TextDrawColor(Lugage_TD[2], -1);
	TextDrawUseBox(Lugage_TD[2], 1);
	TextDrawBoxColor(Lugage_TD[2], -1023398401);
	TextDrawBackgroundColor(Lugage_TD[2], 255);
	TextDrawFont(Lugage_TD[2], 1);
	TextDrawSetProportional(Lugage_TD[2], 1);
	TextDrawSetShadow(Lugage_TD[2], 0);

	Lugage_TD[3] = TextDrawCreate(436.4154, 285.9664, "Box"); // ?????
	TextDrawLetterSize(Lugage_TD[3], 0.0000, -0.6424);
	TextDrawTextSize(Lugage_TD[3], 618.3391, 0.0000);
	TextDrawAlignment(Lugage_TD[3], 1);
	TextDrawColor(Lugage_TD[3], -1);
	TextDrawUseBox(Lugage_TD[3], 1);
	TextDrawBoxColor(Lugage_TD[3], -1023398401);
	TextDrawBackgroundColor(Lugage_TD[3], 255);
	TextDrawFont(Lugage_TD[3], 1);
	TextDrawSetProportional(Lugage_TD[3], 1);
	TextDrawSetShadow(Lugage_TD[3], 0);

	Lugage_TD[4] = TextDrawCreate(436.4154, 285.9664, "Box"); // ?????
	TextDrawLetterSize(Lugage_TD[4], 0.0000, 12.1948);
	TextDrawTextSize(Lugage_TD[4], 434.0000, 0.0000);
	TextDrawAlignment(Lugage_TD[4], 1);
	TextDrawColor(Lugage_TD[4], -1);
	TextDrawUseBox(Lugage_TD[4], 1);
	TextDrawBoxColor(Lugage_TD[4], -1023398401);
	TextDrawBackgroundColor(Lugage_TD[4], 255);
	TextDrawFont(Lugage_TD[4], 1);
	TextDrawSetProportional(Lugage_TD[4], 1);
	TextDrawSetShadow(Lugage_TD[4], 0);

	Lugage_TD[5] = TextDrawCreate(436.8840, 398.9165, "Box"); // ?????
	TextDrawLetterSize(Lugage_TD[5], 0.0000, -0.3355);
	TextDrawTextSize(Lugage_TD[5], 618.2492, 0.0000);
	TextDrawAlignment(Lugage_TD[5], 1);
	TextDrawColor(Lugage_TD[5], -1);
	TextDrawUseBox(Lugage_TD[5], 1);
	TextDrawBoxColor(Lugage_TD[5], -1023398401);
	TextDrawBackgroundColor(Lugage_TD[5], 255);
	TextDrawFont(Lugage_TD[5], 1);
	TextDrawSetProportional(Lugage_TD[5], 1);
	TextDrawSetShadow(Lugage_TD[5], 0);

	Lugage_TD[6] = TextDrawCreate(622.3128, 284.9666, "Box"); // ?????
	TextDrawLetterSize(Lugage_TD[6], 0.0000, 12.3254);
	TextDrawTextSize(Lugage_TD[6], 617.2996, 0.0000);
	TextDrawAlignment(Lugage_TD[6], 1);
	TextDrawColor(Lugage_TD[6], -1);
	TextDrawUseBox(Lugage_TD[6], 1);
	TextDrawBoxColor(Lugage_TD[6], -1023398401);
	TextDrawBackgroundColor(Lugage_TD[6], 255);
	TextDrawFont(Lugage_TD[6], 1);
	TextDrawSetProportional(Lugage_TD[6], 1);
	TextDrawSetShadow(Lugage_TD[6], 0);

	Lugage_TD[7] = TextDrawCreate(572.6494, 285.5498, "Box"); // ?????
	TextDrawLetterSize(Lugage_TD[7], 0.0000, 0.6596);
	TextDrawTextSize(Lugage_TD[7], 484.0000, 0.0000);
	TextDrawAlignment(Lugage_TD[7], 1);
	TextDrawColor(Lugage_TD[7], -1);
	TextDrawUseBox(Lugage_TD[7], 1);
	TextDrawBoxColor(Lugage_TD[7], -1023398401);
	TextDrawBackgroundColor(Lugage_TD[7], 255);
	TextDrawFont(Lugage_TD[7], 2);
	TextDrawSetProportional(Lugage_TD[7], 1);
	TextDrawSetShadow(Lugage_TD[7], 0);

	Lugage_TD[8] = TextDrawCreate(501.4194, 282.6333, "VEHICLE_LUGGAGE"); // ?????
	TextDrawLetterSize(Lugage_TD[8], 0.1492, 1.0108);
	TextDrawAlignment(Lugage_TD[8], 1);
	TextDrawColor(Lugage_TD[8], -1);
	TextDrawBackgroundColor(Lugage_TD[8], 255);
	TextDrawFont(Lugage_TD[8], 2);
	TextDrawSetProportional(Lugage_TD[8], 1);
	TextDrawSetShadow(Lugage_TD[8], 0);

	Lugage_TD[9] = TextDrawCreate(513.1469, 321.7167, "Box"); // ?????
	TextDrawLetterSize(Lugage_TD[9], 0.0000, 7.7810);
	TextDrawTextSize(Lugage_TD[9], 436.0000, 0.0000);
	TextDrawAlignment(Lugage_TD[9], 1);
	TextDrawColor(Lugage_TD[9], -1);
	TextDrawUseBox(Lugage_TD[9], 1);
	TextDrawBoxColor(Lugage_TD[9], -1023398401);
	TextDrawBackgroundColor(Lugage_TD[9], 255);
	TextDrawFont(Lugage_TD[9], 2);
	TextDrawSetProportional(Lugage_TD[9], 1);
	TextDrawSetShadow(Lugage_TD[9], 0);

	Lugage_TD[10] = TextDrawCreate(515.0150, 295.4666, "Box"); // ?????
	TextDrawLetterSize(Lugage_TD[10], 0.0000, 11.0607);
	TextDrawTextSize(Lugage_TD[10], 513.3994, 0.0000);
	TextDrawAlignment(Lugage_TD[10], 1);
	TextDrawColor(Lugage_TD[10], -1);
	TextDrawUseBox(Lugage_TD[10], 1);
	TextDrawBoxColor(Lugage_TD[10], -1023398401);
	TextDrawBackgroundColor(Lugage_TD[10], 255);
	TextDrawFont(Lugage_TD[10], 2);
	TextDrawSetProportional(Lugage_TD[10], 1);
	TextDrawSetShadow(Lugage_TD[10], 0);

	Lugage_TD[11] = TextDrawCreate(517.0645, 295.4833, "LD_SPAC:white"); // ?????
	TextDrawTextSize(Lugage_TD[11], 34.1096, 28.0699);
	TextDrawAlignment(Lugage_TD[11], 1);
	TextDrawColor(Lugage_TD[11], -905957121);
	TextDrawBackgroundColor(Lugage_TD[11], 255);
	TextDrawFont(Lugage_TD[11], 4);
	TextDrawSetProportional(Lugage_TD[11], 0);
	TextDrawSetShadow(Lugage_TD[11], 0);
	TextDrawSetSelectable(Lugage_TD[11], true);

	Lugage_TD[12] = TextDrawCreate(552.6483, 295.5834, "LD_SPAC:white"); // ?????
	TextDrawTextSize(Lugage_TD[12], 65.0000, 28.0000);
	TextDrawAlignment(Lugage_TD[12], 1);
	TextDrawColor(Lugage_TD[12], -905957633);
	TextDrawBackgroundColor(Lugage_TD[12], 255);
	TextDrawFont(Lugage_TD[12], 4);
	TextDrawSetProportional(Lugage_TD[12], 0);
	TextDrawSetShadow(Lugage_TD[12], 0);
	TextDrawSetSelectable(Lugage_TD[12], true);

	Lugage_TD[13] = TextDrawCreate(517.0645, 325.0332, "LD_SPAC:white"); // ?????
	TextDrawTextSize(Lugage_TD[13], 100.0000, 25.0000);
	TextDrawAlignment(Lugage_TD[13], 1);
	TextDrawColor(Lugage_TD[13], -905957633);
	TextDrawBackgroundColor(Lugage_TD[13], 255);
	TextDrawFont(Lugage_TD[13], 4);
	TextDrawSetProportional(Lugage_TD[13], 0);
	TextDrawSetShadow(Lugage_TD[13], 0);
	TextDrawSetSelectable(Lugage_TD[13], true);

	Lugage_TD[14] = TextDrawCreate(491.2958, 302.0000, ""); // ?????
	TextDrawTextSize(Lugage_TD[14], 151.0000, 80.0000);
	TextDrawAlignment(Lugage_TD[14], 1);
	TextDrawColor(Lugage_TD[14], -1);
	TextDrawBackgroundColor(Lugage_TD[14], 0x00000000);
	TextDrawFont(Lugage_TD[14], 5);
	TextDrawSetProportional(Lugage_TD[14], 0);
	TextDrawSetShadow(Lugage_TD[14], 0);
	TextDrawSetPreviewModel(Lugage_TD[14], 19921);
	TextDrawSetPreviewRot(Lugage_TD[14], 153.0000, 0.0000, 0.0000, 1.6641);

	Lugage_TD[15] = TextDrawCreate(512.4423, 290.3832, ""); // ?????
	TextDrawTextSize(Lugage_TD[15], 36.0000, 36.0000);
	TextDrawAlignment(Lugage_TD[15], 1);
	TextDrawColor(Lugage_TD[15], -1);
	TextDrawBackgroundColor(Lugage_TD[15], 0x00000000);
	TextDrawFont(Lugage_TD[15], 5);
	TextDrawSetProportional(Lugage_TD[15], 0);
	TextDrawSetShadow(Lugage_TD[15], 0);
	TextDrawSetPreviewModel(Lugage_TD[15], 1650);
	TextDrawSetPreviewRot(Lugage_TD[15], 0.0000, 0.0000, 0.0000, 1.0000);

	Lugage_TD[16] = TextDrawCreate(517.1956, 352.1665, "LD_SPAC:white"); // ?????
	TextDrawTextSize(Lugage_TD[16], 33.0000, 32.0000);
	TextDrawAlignment(Lugage_TD[16], 1);
	TextDrawColor(Lugage_TD[16], -905957633);
	TextDrawBackgroundColor(Lugage_TD[16], 255);
	TextDrawFont(Lugage_TD[16], 4);
	TextDrawSetProportional(Lugage_TD[16], 0);
	TextDrawSetShadow(Lugage_TD[16], 0);
	TextDrawSetSelectable(Lugage_TD[16], true);

	Lugage_TD[17] = TextDrawCreate(552.2661, 352.1665, "LD_SPAC:white"); // ?????
	TextDrawTextSize(Lugage_TD[17], 33.0000, 32.0000);
	TextDrawAlignment(Lugage_TD[17], 1);
	TextDrawColor(Lugage_TD[17], -905957633);
	TextDrawBackgroundColor(Lugage_TD[17], 255);
	TextDrawFont(Lugage_TD[17], 4);
	TextDrawSetProportional(Lugage_TD[17], 0);
	TextDrawSetShadow(Lugage_TD[17], 0);
	TextDrawSetSelectable(Lugage_TD[17], true);

	Lugage_TD[18] = TextDrawCreate(587.3619, 352.0498, "LD_SPAC:white"); // ?????
	TextDrawTextSize(Lugage_TD[18], 30.2700, 32.0000);
	TextDrawAlignment(Lugage_TD[18], 1);
	TextDrawColor(Lugage_TD[18], -905957633);
	TextDrawBackgroundColor(Lugage_TD[18], 255);
	TextDrawFont(Lugage_TD[18], 4);
	TextDrawSetProportional(Lugage_TD[18], 0);
	TextDrawSetShadow(Lugage_TD[18], 0);
	TextDrawSetSelectable(Lugage_TD[18], true);

	Lugage_TD[19] = TextDrawCreate(586.2930, 391.1333, "Box"); // ?????
	TextDrawLetterSize(Lugage_TD[19], 0.0000, 0.4253);
	TextDrawTextSize(Lugage_TD[19], 550.3994, 0.0000);
	TextDrawAlignment(Lugage_TD[19], 1);
	TextDrawColor(Lugage_TD[19], -1);
	TextDrawUseBox(Lugage_TD[19], 1);
	TextDrawBoxColor(Lugage_TD[19], -1023398401);
	TextDrawBackgroundColor(Lugage_TD[19], 255);
	TextDrawFont(Lugage_TD[19], 2);
	TextDrawSetProportional(Lugage_TD[19], 1);
	TextDrawSetShadow(Lugage_TD[19], 0);

	Lugage_TD[20] = TextDrawCreate(515.0211, 389.3833, "Box"); // ?????
	TextDrawLetterSize(Lugage_TD[20], 0.0000, -0.6521);
	TextDrawTextSize(Lugage_TD[20], 618.0000, 0.0000);
	TextDrawAlignment(Lugage_TD[20], 1);
	TextDrawColor(Lugage_TD[20], -1);
	TextDrawUseBox(Lugage_TD[20], 1);
	TextDrawBoxColor(Lugage_TD[20], -1023398401);
	TextDrawBackgroundColor(Lugage_TD[20], 255);
	TextDrawFont(Lugage_TD[20], 2);
	TextDrawSetProportional(Lugage_TD[20], 1);
	TextDrawSetShadow(Lugage_TD[20], 0);

	Lugage_TD[21] = TextDrawCreate(556.1198, 387.1665, "ITEMS"); // ?????
	TextDrawLetterSize(Lugage_TD[21], 0.1932, 1.0865);
	TextDrawAlignment(Lugage_TD[21], 1);
	TextDrawColor(Lugage_TD[21], -1);
	TextDrawBackgroundColor(Lugage_TD[21], 255);
	TextDrawFont(Lugage_TD[21], 2);
	TextDrawSetProportional(Lugage_TD[21], 1);
	TextDrawSetShadow(Lugage_TD[21], 0);

	Lugage_TD[22] = TextDrawCreate(528.8342, 267.0000, ""); // ?????
	TextDrawTextSize(Lugage_TD[22], 90.0000, 90.0000);
	TextDrawAlignment(Lugage_TD[22], 1);
	TextDrawColor(Lugage_TD[22], -1);
	TextDrawBackgroundColor(Lugage_TD[22], 0x00000000);
	TextDrawFont(Lugage_TD[22], 5);
	TextDrawSetProportional(Lugage_TD[22], 0);
	TextDrawSetShadow(Lugage_TD[22], 0);
	TextDrawSetPreviewModel(Lugage_TD[22], 356);
	TextDrawSetPreviewRot(Lugage_TD[22], 0.0000, 0.0000, 189.0000, 1.9648);

	Lugage_TD[23] = TextDrawCreate(491.2955, 330.5834, ""); // ?????
	TextDrawTextSize(Lugage_TD[23], 84.0000, 68.0000);
	TextDrawAlignment(Lugage_TD[23], 1);
	TextDrawColor(Lugage_TD[23], -1);
	TextDrawBackgroundColor(Lugage_TD[23], 0x00000000);
	TextDrawFont(Lugage_TD[23], 5);
	TextDrawSetProportional(Lugage_TD[23], 0);
	TextDrawSetShadow(Lugage_TD[23], 0);
	TextDrawSetPreviewModel(Lugage_TD[23], 1550);
	TextDrawSetPreviewRot(Lugage_TD[23], 331.0000, 0.0000, 0.0000, 1.7302);

	Lugage_TD[24] = TextDrawCreate(533.1195, 346.4002, ""); // ?????
	TextDrawTextSize(Lugage_TD[24], 69.0000, 41.0000);
	TextDrawAlignment(Lugage_TD[24], 1);
	TextDrawColor(Lugage_TD[24], -5327873);
	TextDrawBackgroundColor(Lugage_TD[24], 0x00000000);
	TextDrawFont(Lugage_TD[24], 5);
	TextDrawSetProportional(Lugage_TD[24], 0);
	TextDrawSetShadow(Lugage_TD[24], 0);
	TextDrawSetPreviewModel(Lugage_TD[24], 1654);
	TextDrawSetPreviewRot(Lugage_TD[24], 0.0000, 0.0000, 180.0000, 1.0000);

	Lugage_TD[25] = TextDrawCreate(586.8742, 339.9165, ""); // ?????
	TextDrawTextSize(Lugage_TD[25], 32.0000, 42.3698);
	TextDrawAlignment(Lugage_TD[25], 1);
	TextDrawColor(Lugage_TD[25], -1);
	TextDrawBackgroundColor(Lugage_TD[25], 0x00000000);
	TextDrawFont(Lugage_TD[25], 5);
	TextDrawSetProportional(Lugage_TD[25], 0);
	TextDrawSetShadow(Lugage_TD[25], 0);
	TextDrawSetPreviewModel(Lugage_TD[25], 1575);
	TextDrawSetPreviewRot(Lugage_TD[25], 277.0000, 355.0000, 0.0000, 1.0000);