	NAVIGATION_TD[0] = TextDrawCreate(156.5000, 366.7500, "LD_BEAT:CHIT"); // ?????
	TextDrawTextSize(NAVIGATION_TD[0], 31.0000, 33.0000);
	TextDrawAlignment(NAVIGATION_TD[0], 1);
	TextDrawColor(NAVIGATION_TD[0], -29422081);
	TextDrawBackgroundColor(NAVIGATION_TD[0], 255);
	TextDrawFont(NAVIGATION_TD[0], 4);
	TextDrawSetProportional(NAVIGATION_TD[0], 0);
	TextDrawSetShadow(NAVIGATION_TD[0], 0);

	NAVIGATION_TD[1] = TextDrawCreate(173.9998, 373.5499, "Box"); // ?????
	TextDrawLetterSize(NAVIGATION_TD[1], 0.0000, 2.1209);
	TextDrawTextSize(NAVIGATION_TD[1], 233.0000, 0.0000);
	TextDrawAlignment(NAVIGATION_TD[1], 1);
	TextDrawColor(NAVIGATION_TD[1], -29422081);
	TextDrawUseBox(NAVIGATION_TD[1], 1);
	TextDrawBoxColor(NAVIGATION_TD[1], -29422081);
	TextDrawBackgroundColor(NAVIGATION_TD[1], 255);
	TextDrawFont(NAVIGATION_TD[1], 1);
	TextDrawSetProportional(NAVIGATION_TD[1], 1);
	TextDrawSetShadow(NAVIGATION_TD[1], 0);

	NAVIGATION_TD[2] = TextDrawCreate(220.3009, 366.5499, "LD_BEAT:CHIT"); // ?????
	TextDrawTextSize(NAVIGATION_TD[2], 31.0000, 33.0000);
	TextDrawAlignment(NAVIGATION_TD[2], 1);
	TextDrawColor(NAVIGATION_TD[2], -29422081);
	TextDrawBackgroundColor(NAVIGATION_TD[2], 255);
	TextDrawFont(NAVIGATION_TD[2], 4);
	TextDrawSetProportional(NAVIGATION_TD[2], 0);
	TextDrawSetShadow(NAVIGATION_TD[2], 0);

	NAVIGATION_TD[3] = TextDrawCreate(163.0000, 373.7500, "hud:radar_waypoint"); // ?????
	TextDrawTextSize(NAVIGATION_TD[3], 19.0000, 19.0000);
	TextDrawAlignment(NAVIGATION_TD[3], 1);
	TextDrawColor(NAVIGATION_TD[3], -16776961);
	TextDrawBackgroundColor(NAVIGATION_TD[3], 255);
	TextDrawFont(NAVIGATION_TD[3], 4);
	TextDrawSetProportional(NAVIGATION_TD[3], 0);
	TextDrawSetShadow(NAVIGATION_TD[3], 0);
	// betx
	BetX_Info[0] = TextDrawCreate(223.484634, 130.083343, "LD_SPAC:white");
	TextDrawLetterSize(BetX_Info[0], 0.000000, 0.000000);
	TextDrawTextSize(BetX_Info[0], 186.939987, 227.499969);
	TextDrawAlignment(BetX_Info[0], 1);
	TextDrawColor(BetX_Info[0], 589505535);
	TextDrawSetShadow(BetX_Info[0], 0);
	TextDrawSetOutline(BetX_Info[0], 0);
	TextDrawFont(BetX_Info[0], 4);

	BetX_Info[1] = TextDrawCreate(296.574188, 130.666702, "JET X");
	TextDrawLetterSize(BetX_Info[1], 0.449999, 1.600000);
	TextDrawAlignment(BetX_Info[1], 1);
	TextDrawColor(BetX_Info[1], -5963521);
	TextDrawSetShadow(BetX_Info[1], 1);
	TextDrawSetOutline(BetX_Info[1], 0);
	TextDrawBackgroundColor(BetX_Info[1], 51);
	TextDrawFont(BetX_Info[1], 1);
	TextDrawSetProportional(BetX_Info[1], 1);

	BetX_Info[2] = TextDrawCreate(278.301544, 225.750000, "LD_SPAC:white");
	TextDrawLetterSize(BetX_Info[2], 0.000000, 0.000000);
	TextDrawTextSize(BetX_Info[2], 73.557830, 34.416656);
	TextDrawAlignment(BetX_Info[2], 1);
	TextDrawColor(BetX_Info[2], 1515871519);
	TextDrawSetShadow(BetX_Info[2], 0);
	TextDrawSetOutline(BetX_Info[2], 0);
	TextDrawFont(BetX_Info[2], 4);

	BetX_Info[3] = TextDrawCreate(280.644348, 149.333343, " ");
	TextDrawLetterSize(BetX_Info[3], 0.163265, 0.940831);
	TextDrawAlignment(BetX_Info[3], 1);
	TextDrawColor(BetX_Info[3], -1);
	TextDrawSetShadow(BetX_Info[3], 1);
	TextDrawSetOutline(BetX_Info[3], 0);
	TextDrawBackgroundColor(BetX_Info[3], 51);
	TextDrawFont(BetX_Info[3], 2);
	TextDrawSetProportional(BetX_Info[3], 1);

	BetX_Info[4] = TextDrawCreate(257.686645, 156.333328, " ");
	TextDrawLetterSize(BetX_Info[4], 0.151551, 1.010832);
	TextDrawAlignment(BetX_Info[4], 1);
	TextDrawColor(BetX_Info[4], -5963521);
	TextDrawSetShadow(BetX_Info[4], 1);
	TextDrawSetOutline(BetX_Info[4], 0);
	TextDrawBackgroundColor(BetX_Info[4], 51);
	TextDrawFont(BetX_Info[4], 2);
	TextDrawSetProportional(BetX_Info[4], 1);

	BetX_Info[5] = TextDrawCreate(230.512374, 173.249984, "DADET FSONI TAMASHIS DACKEBAMDE DA MOXSENIT TANXA");
	TextDrawLetterSize(BetX_Info[5], 0.141713, 0.894166);
	TextDrawAlignment(BetX_Info[5], 1);
	TextDrawColor(BetX_Info[5], -1);
	TextDrawSetShadow(BetX_Info[5], 1);
	TextDrawSetOutline(BetX_Info[5], 0);
	TextDrawBackgroundColor(BetX_Info[5], 51);
	TextDrawFont(BetX_Info[5], 2);
	TextDrawSetProportional(BetX_Info[5], 1);

	BetX_Info[6] = TextDrawCreate(230.043838, 182.000000, "AFETQEBAMDE, FSONI UNDA IYOS 100$'dan 5.000.000$'mde");
	TextDrawLetterSize(BetX_Info[6], 0.147335, 0.911666);
	TextDrawAlignment(BetX_Info[6], 1);
	TextDrawColor(BetX_Info[6], -1);
	TextDrawSetShadow(BetX_Info[6], 1);
	TextDrawSetOutline(BetX_Info[6], 0);
	TextDrawBackgroundColor(BetX_Info[6], 51);
	TextDrawFont(BetX_Info[6], 2);
	TextDrawSetProportional(BetX_Info[6], 1);

	BetX_Info[7] = TextDrawCreate(315.315002, 211.166656, "MIMDINAREOBS FSONEBIS MIGEBA");
	TextDrawLetterSize(BetX_Info[7], 0.262123, 1.308333);
	TextDrawAlignment(BetX_Info[7], 2);
	TextDrawColor(BetX_Info[7], -5963521);
	TextDrawSetShadow(BetX_Info[7], 0);
	TextDrawSetOutline(BetX_Info[7], 1);
	TextDrawBackgroundColor(BetX_Info[7], 51);
	TextDrawFont(BetX_Info[7], 3);
	TextDrawSetProportional(BetX_Info[7], 1);

	BetX_Info[8] = TextDrawCreate(314.377868, 231.583358, "~r~5.12 X");
	TextDrawLetterSize(BetX_Info[8], 0.523558, 2.078332);
	TextDrawAlignment(BetX_Info[8], 2);
	TextDrawColor(BetX_Info[8], 8388863);
	TextDrawSetShadow(BetX_Info[8], 1);
	TextDrawSetOutline(BetX_Info[8], 0);
	TextDrawBackgroundColor(BetX_Info[8], 51);
	TextDrawFont(BetX_Info[8], 3);
	TextDrawSetProportional(BetX_Info[8], 1);

	BetX_Info[9] = TextDrawCreate(225.827239, 269.500000, "LD_SPAC:white");
	TextDrawLetterSize(BetX_Info[9], 0.000000, 0.000000);
	TextDrawTextSize(BetX_Info[9], 182.723297, 12.833312);
	TextDrawAlignment(BetX_Info[9], 1);
	TextDrawColor(BetX_Info[9], 1515871519);
	TextDrawSetShadow(BetX_Info[9], 0);
	TextDrawSetOutline(BetX_Info[9], 0);
	TextDrawFont(BetX_Info[9], 4);

	BetX_Info[10] = TextDrawCreate(226.295761, 270.666687, "LD_SPAC:white");
	TextDrawLetterSize(BetX_Info[10], 0.000000, 0.000000);
	TextDrawTextSize(BetX_Info[10], 181.00000, 10.500000);
	TextDrawAlignment(BetX_Info[10], 1);
	TextDrawColor(BetX_Info[10], 8388863);
	TextDrawSetShadow(BetX_Info[10], 0);
	TextDrawSetOutline(BetX_Info[10], 0);
	TextDrawFont(BetX_Info[10], 4);

	BetX_Info[11] = TextDrawCreate(291.420227, 340.083312, "LD_SPAC:white");
	TextDrawLetterSize(BetX_Info[11], 0.000000, 0.000000);
	TextDrawTextSize(BetX_Info[11], 50.600280, 14.000000);
	TextDrawAlignment(BetX_Info[11], 1);
	TextDrawColor(BetX_Info[11],1515871519);
	TextDrawSetShadow(BetX_Info[11], 0);
	TextDrawSetOutline(BetX_Info[11], 0);
	TextDrawFont(BetX_Info[11], 4);
	TextDrawSetSelectable(BetX_Info[11], true);

	BetX_Info[12] = TextDrawCreate(297.979827, 342.416809, "GATISHVA");
	TextDrawLetterSize(BetX_Info[12], 0.181068, 0.888333);
	TextDrawAlignment(BetX_Info[12], 1);
	TextDrawColor(BetX_Info[12], -5963521);
	TextDrawUseBox(BetX_Info[12], true);
	TextDrawBoxColor(BetX_Info[12], 0);
	TextDrawSetShadow(BetX_Info[12], 1);
	TextDrawSetOutline(BetX_Info[12], 0);
	TextDrawBackgroundColor(BetX_Info[12], 51);
	TextDrawFont(BetX_Info[12], 2);
	TextDrawSetProportional(BetX_Info[12], 1);
