	NewPosTD_TD[0] = TextDrawCreate(244.5532, 180.0832, "Box"); // ?????
	TextDrawLetterSize(NewPosTD_TD[0], 0.0000, 7.4229);
	TextDrawTextSize(NewPosTD_TD[0], 406.0000, 0.0000);
	TextDrawAlignment(NewPosTD_TD[0], 1);
	TextDrawColor(NewPosTD_TD[0], -1);
	TextDrawUseBox(NewPosTD_TD[0], 1);
	TextDrawBoxColor(NewPosTD_TD[0], -12237313);
	TextDrawBackgroundColor(NewPosTD_TD[0], 255);
	TextDrawFont(NewPosTD_TD[0], 1);
	TextDrawSetProportional(NewPosTD_TD[0], 1);
	TextDrawSetShadow(NewPosTD_TD[0], 0);

	NewPosTD_TD[1] = TextDrawCreate(235.3459, 155.9833, "GENUINE_ROLE_PLAY"); // ?????
	TextDrawLetterSize(NewPosTD_TD[1], 0.3882, 1.7806);
	TextDrawAlignment(NewPosTD_TD[1], 1);
	TextDrawColor(NewPosTD_TD[1], -1);
	TextDrawBackgroundColor(NewPosTD_TD[1], 255);
	TextDrawFont(NewPosTD_TD[1], 2);
	TextDrawSetProportional(NewPosTD_TD[1], 1);
	TextDrawSetShadow(NewPosTD_TD[1], 0);

	NewPosTD_TD[2] = TextDrawCreate(209.4569, 174.0832, "LD_BEAT:chit"); // ?????
	TextDrawTextSize(NewPosTD_TD[2], 20.0000, 18.0000);
	TextDrawAlignment(NewPosTD_TD[2], 1);
	TextDrawColor(NewPosTD_TD[2], -12237313);
	TextDrawBackgroundColor(NewPosTD_TD[2], 255);
	TextDrawFont(NewPosTD_TD[2], 4);
	TextDrawSetProportional(NewPosTD_TD[2], 0);
	TextDrawSetShadow(NewPosTD_TD[2], 0);

	NewPosTD_TD[3] = TextDrawCreate(220.5000, 178.6250, "Box"); // ?????
	TextDrawLetterSize(NewPosTD_TD[3], 0.0000, 0.6000);
	TextDrawTextSize(NewPosTD_TD[3], 405.0000, 0.0000);
	TextDrawAlignment(NewPosTD_TD[3], 1);
	TextDrawColor(NewPosTD_TD[3], -1);
	TextDrawUseBox(NewPosTD_TD[3], 1);
	TextDrawBoxColor(NewPosTD_TD[3], -12237313);
	TextDrawBackgroundColor(NewPosTD_TD[3], 255);
	TextDrawFont(NewPosTD_TD[3], 1);
	TextDrawSetProportional(NewPosTD_TD[3], 1);
	TextDrawSetShadow(NewPosTD_TD[3], 0);

	NewPosTD_TD[4] = TextDrawCreate(397.4859, 173.9501, "LD_BEAT:chit"); // ?????
	TextDrawTextSize(NewPosTD_TD[4], 15.0000, 18.0000);
	TextDrawAlignment(NewPosTD_TD[4], 1);
	TextDrawColor(NewPosTD_TD[4], -12237313);
	TextDrawBackgroundColor(NewPosTD_TD[4], 255);
	TextDrawFont(NewPosTD_TD[4], 4);
	TextDrawSetProportional(NewPosTD_TD[4], 0);
	TextDrawSetShadow(NewPosTD_TD[4], 0);

	NewPosTD_TD[5] = TextDrawCreate(249.7070, 178.9832, "Box"); // ?????
	TextDrawLetterSize(NewPosTD_TD[5], 0.0000, 3.7218);
	TextDrawTextSize(NewPosTD_TD[5], 403.0000, 0.0000);
	TextDrawAlignment(NewPosTD_TD[5], 1);
	TextDrawColor(NewPosTD_TD[5], -1);
	TextDrawUseBox(NewPosTD_TD[5], 1);
	TextDrawBoxColor(NewPosTD_TD[5], -12237313);
	TextDrawBackgroundColor(NewPosTD_TD[5], 255);
	TextDrawFont(NewPosTD_TD[5], 1);
	TextDrawSetProportional(NewPosTD_TD[5], 1);
	TextDrawSetShadow(NewPosTD_TD[5], 0);

	NewPosTD_TD[6] = TextDrawCreate(243.0106, 184.8164, "Box"); // ?????
	TextDrawLetterSize(NewPosTD_TD[6], 0.0000, 6.4390);
	TextDrawTextSize(NewPosTD_TD[6], 397.0000, 0.0000);
	TextDrawAlignment(NewPosTD_TD[6], 1);
	TextDrawColor(NewPosTD_TD[6], -1);
	TextDrawUseBox(NewPosTD_TD[6], 1);
	TextDrawBoxColor(NewPosTD_TD[6], -12237313);
	TextDrawBackgroundColor(NewPosTD_TD[6], 255);
	TextDrawFont(NewPosTD_TD[6], 1);
	TextDrawSetProportional(NewPosTD_TD[6], 1);
	TextDrawSetShadow(NewPosTD_TD[6], 0);

	NewPosTD_TD[7] = TextDrawCreate(249.5700, 190.8665, "Box"); // ?????
	TextDrawLetterSize(NewPosTD_TD[7], 0.0000, 6.4390);
	TextDrawTextSize(NewPosTD_TD[7], 401.0000, 0.0000);
	TextDrawAlignment(NewPosTD_TD[7], 1);
	TextDrawColor(NewPosTD_TD[7], -1);
	TextDrawUseBox(NewPosTD_TD[7], 1);
	TextDrawBoxColor(NewPosTD_TD[7], -12237313);
	TextDrawBackgroundColor(NewPosTD_TD[7], 255);
	TextDrawFont(NewPosTD_TD[7], 1);
	TextDrawSetProportional(NewPosTD_TD[7], 1);
	TextDrawSetShadow(NewPosTD_TD[7], 0);

	NewPosTD_TD[8] = TextDrawCreate(249.1013, 185.5832, "Box"); // ?????
	TextDrawLetterSize(NewPosTD_TD[8], 0.0000, 6.2518);
	TextDrawTextSize(NewPosTD_TD[8], 408.0000, 0.0000);
	TextDrawAlignment(NewPosTD_TD[8], 1);
	TextDrawColor(NewPosTD_TD[8], -1);
	TextDrawUseBox(NewPosTD_TD[8], 1);
	TextDrawBoxColor(NewPosTD_TD[8], -12237313);
	TextDrawBackgroundColor(NewPosTD_TD[8], 255);
	TextDrawFont(NewPosTD_TD[8], 1);
	TextDrawSetProportional(NewPosTD_TD[8], 1);
	TextDrawSetShadow(NewPosTD_TD[8], 0);

	NewPosTD_TD[9] = TextDrawCreate(219.7738, 181.5500, "Box"); // ?????
	TextDrawLetterSize(NewPosTD_TD[9], 0.0000, 7.2357);
	TextDrawTextSize(NewPosTD_TD[9], 270.0000, 0.0000);
	TextDrawAlignment(NewPosTD_TD[9], 1);
	TextDrawColor(NewPosTD_TD[9], -1);
	TextDrawUseBox(NewPosTD_TD[9], 1);
	TextDrawBoxColor(NewPosTD_TD[9], -12237313);
	TextDrawBackgroundColor(NewPosTD_TD[9], 255);
	TextDrawFont(NewPosTD_TD[9], 1);
	TextDrawSetProportional(NewPosTD_TD[9], 1);
	TextDrawSetShadow(NewPosTD_TD[9], 0);

	NewPosTD_TD[10] = TextDrawCreate(221.5957, 178.8336, "Box"); // ?????
	TextDrawLetterSize(NewPosTD_TD[10], 0.0000, 0.2079);
	TextDrawTextSize(NewPosTD_TD[10], 296.0000, 0.0000);
	TextDrawAlignment(NewPosTD_TD[10], 1);
	TextDrawColor(NewPosTD_TD[10], -1);
	TextDrawUseBox(NewPosTD_TD[10], 1);
	TextDrawBoxColor(NewPosTD_TD[10], -12237313);
	TextDrawBackgroundColor(NewPosTD_TD[10], 255);
	TextDrawFont(NewPosTD_TD[10], 1);
	TextDrawSetProportional(NewPosTD_TD[10], 1);
	TextDrawSetShadow(NewPosTD_TD[10], 0);

	NewPosTD_TD[11] = TextDrawCreate(218.3161, 251.0001, "Box"); // ?????
	TextDrawLetterSize(NewPosTD_TD[11], 0.0000, -0.2135);
	TextDrawTextSize(NewPosTD_TD[11], 295.0000, 0.0000);
	TextDrawAlignment(NewPosTD_TD[11], 1);
	TextDrawColor(NewPosTD_TD[11], -1);
	TextDrawUseBox(NewPosTD_TD[11], 1);
	TextDrawBoxColor(NewPosTD_TD[11], -12237313);
	TextDrawBackgroundColor(NewPosTD_TD[11], 255);
	TextDrawFont(NewPosTD_TD[11], 1);
	TextDrawSetProportional(NewPosTD_TD[11], 1);
	TextDrawSetShadow(NewPosTD_TD[11], 0);

	NewPosTD_TD[12] = TextDrawCreate(214.8049, 185.9165, "Box"); // ?????
	TextDrawLetterSize(NewPosTD_TD[12], 0.0000, 5.8301);
	TextDrawTextSize(NewPosTD_TD[12], 273.0000, 0.0000);
	TextDrawAlignment(NewPosTD_TD[12], 1);
	TextDrawColor(NewPosTD_TD[12], -1);
	TextDrawUseBox(NewPosTD_TD[12], 1);
	TextDrawBoxColor(NewPosTD_TD[12], -12237313);
	TextDrawBackgroundColor(NewPosTD_TD[12], 255);
	TextDrawFont(NewPosTD_TD[12], 1);
	TextDrawSetProportional(NewPosTD_TD[12], 1);
	TextDrawSetShadow(NewPosTD_TD[12], 0);

	NewPosTD_TD[13] = TextDrawCreate(215.2366, 182.9665, ""); // ?????
	TextDrawTextSize(NewPosTD_TD[13], 48.0000, 45.0000);
	TextDrawAlignment(NewPosTD_TD[13], 1);
	TextDrawColor(NewPosTD_TD[13], -1);
	TextDrawBackgroundColor(NewPosTD_TD[13], -256);
	TextDrawFont(NewPosTD_TD[13], 5);
	TextDrawSetProportional(NewPosTD_TD[13], 0);
	TextDrawSetShadow(NewPosTD_TD[13], 0);
	TextDrawSetSelectable(NewPosTD_TD[13], true);
	TextDrawSetPreviewModel(NewPosTD_TD[13], 1273);
	TextDrawSetPreviewRot(NewPosTD_TD[13], 0.0000, 0.0000, 0.0000, 1.0000);

	NewPosTD_TD[14] = TextDrawCreate(269.2427, 170.2330, ""); // ?????
	TextDrawTextSize(NewPosTD_TD[14], 46.0000, 67.0000);
	TextDrawAlignment(NewPosTD_TD[14], 1);
	TextDrawColor(NewPosTD_TD[14], -1);
	TextDrawBackgroundColor(NewPosTD_TD[14], -256);
	TextDrawFont(NewPosTD_TD[14], 5);
	TextDrawSetProportional(NewPosTD_TD[14], 0);
	TextDrawSetShadow(NewPosTD_TD[14], 0);
	TextDrawSetSelectable(NewPosTD_TD[14], true);
	TextDrawSetPreviewModel(NewPosTD_TD[14], 1210);
	TextDrawSetPreviewRot(NewPosTD_TD[14], 0.0000, 0.0000, 0.0000, 1.0000);

	NewPosTD_TD[15] = TextDrawCreate(316.4002, 183.9828, ""); // ?????
	TextDrawTextSize(NewPosTD_TD[15], 48.0000, 42.0000);
	TextDrawAlignment(NewPosTD_TD[15], 1);
	TextDrawColor(NewPosTD_TD[15], -1);
	TextDrawBackgroundColor(NewPosTD_TD[15], -256);
	TextDrawFont(NewPosTD_TD[15], 5);
	TextDrawSetProportional(NewPosTD_TD[15], 0);
	TextDrawSetShadow(NewPosTD_TD[15], 0);
	TextDrawSetSelectable(NewPosTD_TD[15], true);
	TextDrawSetPreviewModel(NewPosTD_TD[15], 1314);
	TextDrawSetPreviewRot(NewPosTD_TD[15], 0.0000, 360.0000, 182.0000, 1.0000);

	NewPosTD_TD[16] = TextDrawCreate(366.0638, 179.3327, ""); // ?????
	TextDrawTextSize(NewPosTD_TD[16], 44.0000, 50.0000);
	TextDrawAlignment(NewPosTD_TD[16], 1);
	TextDrawColor(NewPosTD_TD[16], -1);
	TextDrawBackgroundColor(NewPosTD_TD[16], -256);
	TextDrawFont(NewPosTD_TD[16], 5);
	TextDrawSetProportional(NewPosTD_TD[16], 0);
	TextDrawSetShadow(NewPosTD_TD[16], 0);
	TextDrawSetSelectable(NewPosTD_TD[16], true);
	TextDrawSetPreviewModel(NewPosTD_TD[16], 1277);
	TextDrawSetPreviewRot(NewPosTD_TD[16], 0.0000, 360.0000, 182.0000, 1.0000);

	NewPosTD_TD[17] = TextDrawCreate(214.7364, 232.2540, "Box"); // ?????
	TextDrawLetterSize(NewPosTD_TD[17], 0.0000, 1.1480);
	TextDrawTextSize(NewPosTD_TD[17], 408.0000, 0.0000);
	TextDrawAlignment(NewPosTD_TD[17], 1);
	TextDrawColor(NewPosTD_TD[17], -1);
	TextDrawUseBox(NewPosTD_TD[17], 1);
	TextDrawBoxColor(NewPosTD_TD[17], 255);
	TextDrawBackgroundColor(NewPosTD_TD[17], 255);
	TextDrawFont(NewPosTD_TD[17], 1);
	TextDrawSetProportional(NewPosTD_TD[17], 1);
	TextDrawSetShadow(NewPosTD_TD[17], 0);

	NewPosTD_TD[18] = TextDrawCreate(227.6864, 229.6665, "HOUSE"); // ?????
	TextDrawLetterSize(NewPosTD_TD[18], 0.1730, 1.2848);
	TextDrawAlignment(NewPosTD_TD[18], 1);
	TextDrawColor(NewPosTD_TD[18], -1);
	TextDrawBackgroundColor(NewPosTD_TD[18], 255);
	TextDrawFont(NewPosTD_TD[18], 2);
	TextDrawSetProportional(NewPosTD_TD[18], 1);
	TextDrawSetShadow(NewPosTD_TD[18], 0);

	NewPosTD_TD[19] = TextDrawCreate(221.4479, 144.3999, ""); // ?????
	TextDrawTextSize(NewPosTD_TD[19], 30.0000, 33.0000);
	TextDrawAlignment(NewPosTD_TD[19], 1);
	TextDrawColor(NewPosTD_TD[19], -1);
	TextDrawBackgroundColor(NewPosTD_TD[19], 0x00000000);
	TextDrawFont(NewPosTD_TD[19], 5);
	TextDrawSetProportional(NewPosTD_TD[19], 0);
	TextDrawSetShadow(NewPosTD_TD[19], 0);
	TextDrawSetPreviewModel(NewPosTD_TD[19], 19475);
	TextDrawSetPreviewRot(NewPosTD_TD[19], 0.0000, 0.0000, 213.0000, 1.0000);

	NewPosTD_TD[20] = TextDrawCreate(275.6921, 229.3833, "FRACTION"); // ?????
	TextDrawLetterSize(NewPosTD_TD[20], 0.1730, 1.2848);
	TextDrawAlignment(NewPosTD_TD[20], 1);
	TextDrawColor(NewPosTD_TD[20], -1);
	TextDrawBackgroundColor(NewPosTD_TD[20], 255);
	TextDrawFont(NewPosTD_TD[20], 2);
	TextDrawSetProportional(NewPosTD_TD[20], 1);
	TextDrawSetShadow(NewPosTD_TD[20], 0);

	NewPosTD_TD[21] = TextDrawCreate(330.3558, 229.2498, "SPAWN"); // ?????
	TextDrawLetterSize(NewPosTD_TD[21], 0.1730, 1.2848);
	TextDrawAlignment(NewPosTD_TD[21], 1);
	TextDrawColor(NewPosTD_TD[21], -1);
	TextDrawBackgroundColor(NewPosTD_TD[21], 255);
	TextDrawFont(NewPosTD_TD[21], 2);
	TextDrawSetProportional(NewPosTD_TD[21], 1);
	TextDrawSetShadow(NewPosTD_TD[21], 0);

	NewPosTD_TD[22] = TextDrawCreate(371.4490, 229.2666, "LAST_POS"); // ?????
	TextDrawLetterSize(NewPosTD_TD[22], 0.1720, 1.2548);
	TextDrawAlignment(NewPosTD_TD[22], 1);
	TextDrawColor(NewPosTD_TD[22], -1);
	TextDrawBackgroundColor(NewPosTD_TD[22], 255);
	TextDrawFont(NewPosTD_TD[22], 2);
	TextDrawSetProportional(NewPosTD_TD[22], 1);
	TextDrawSetShadow(NewPosTD_TD[22], 0);

	NewPosTD_TD[23] = TextDrawCreate(214.6000, 244.6875, "Box"); // ?????
	TextDrawLetterSize(NewPosTD_TD[23], 0.0000, 0.6000);
	TextDrawTextSize(NewPosTD_TD[23], 408.0000, 0.0000);
	TextDrawAlignment(NewPosTD_TD[23], 1);
	TextDrawColor(NewPosTD_TD[23], -1);
	TextDrawUseBox(NewPosTD_TD[23], 1);
	TextDrawBoxColor(NewPosTD_TD[23], -12237313);
	TextDrawBackgroundColor(NewPosTD_TD[23], 255);
	TextDrawFont(NewPosTD_TD[23], 1);
	TextDrawSetProportional(NewPosTD_TD[23], 1);
	TextDrawSetShadow(NewPosTD_TD[23], 0);
