	payment_td[0] = TextDrawCreate(17.4999, 188.1851, "LD_SPAC:white"); // ?????
	TextDrawTextSize(payment_td[0], 79.8482, 17.0000);
	TextDrawAlignment(payment_td[0], 1);
	TextDrawColor(payment_td[0], 255);
	TextDrawBackgroundColor(payment_td[0], 255);
	TextDrawFont(payment_td[0], 4);
	TextDrawSetProportional(payment_td[0], 0);
	TextDrawSetShadow(payment_td[0], 0);

	payment_td[1] = TextDrawCreate(87.3666, 184.2924, "LD_BEAT:chit"); // ?????
	TextDrawTextSize(payment_td[1], 23.5000, 24.7098);
	TextDrawAlignment(payment_td[1], 1);
	TextDrawColor(payment_td[1], 0xFFE100FF);
	TextDrawBackgroundColor(payment_td[1], 255);
	TextDrawFont(payment_td[1], 4);
	TextDrawSetProportional(payment_td[1], 0);
	TextDrawSetShadow(payment_td[1], 0);

	payment_td[2] = TextDrawCreate(3.9674, 184.2924, "LD_BEAT:chit"); // ?????
	TextDrawTextSize(payment_td[2], 23.5000, 24.7098);
	TextDrawAlignment(payment_td[2], 1);
	TextDrawColor(payment_td[2], 0xFFE100FF);
	TextDrawBackgroundColor(payment_td[2], 255);
	TextDrawFont(payment_td[2], 4);
	TextDrawSetProportional(payment_td[2], 0);
	TextDrawSetShadow(payment_td[2], 0);

	payment_td[3] = TextDrawCreate(85.0668, 184.2924, "LD_BEAT:chit"); // ?????
	TextDrawTextSize(payment_td[3], 23.5000, 24.7098);
	TextDrawAlignment(payment_td[3], 1);
	TextDrawColor(payment_td[3], 255);
	TextDrawBackgroundColor(payment_td[3], 255);
	TextDrawFont(payment_td[3], 4);
	TextDrawSetProportional(payment_td[3], 0);
	TextDrawSetShadow(payment_td[3], 0);

	payment_td[4] = TextDrawCreate(6.2673, 184.3925, "LD_BEAT:chit"); // ?????
	TextDrawTextSize(payment_td[4], 23.5000, 24.7098);
	TextDrawAlignment(payment_td[4], 1);
	TextDrawColor(payment_td[4], 255);
	TextDrawBackgroundColor(payment_td[4], 255);
	TextDrawFont(payment_td[4], 4);
	TextDrawSetProportional(payment_td[4], 0);
	TextDrawSetShadow(payment_td[4], 0);
