ReportTXT[0] = TextDrawCreate(0.000000, 207.812500, "Ld_beat:chit");
TextDrawLetterSize(ReportTXT[0], 0.000000, 0.000000);
TextDrawTextSize(ReportTXT[0], 34.000000, 25.375000);
TextDrawAlignment(ReportTXT[0], 1);
TextDrawColor(ReportTXT[0], 0xE20D94FF);
TextDrawSetShadow(ReportTXT[0], 0);
TextDrawSetOutline(ReportTXT[0], 0);
TextDrawFont(ReportTXT[0], 4);

ReportTXT[1] = TextDrawCreate(17.500000, 213.937500, "20");
TextDrawLetterSize(ReportTXT[1], 0.336999, 1.249999);
TextDrawAlignment(ReportTXT[1], 2);
TextDrawColor(ReportTXT[1], -1);
TextDrawSetShadow(ReportTXT[1], 0);
TextDrawSetOutline(ReportTXT[1], 1);
TextDrawBackgroundColor(ReportTXT[1], 51);
TextDrawFont(ReportTXT[1], 3);
TextDrawSetProportional(ReportTXT[1], 1);

ReportTXT[2] = TextDrawCreate(3.000000, 230.562500, "REPORT");
TextDrawLetterSize(ReportTXT[2], 0.185499, 1.013749);
TextDrawAlignment(ReportTXT[2], 1);
TextDrawColor(ReportTXT[2], -1);
TextDrawSetShadow(ReportTXT[2], 0);
TextDrawSetOutline(ReportTXT[2], 1);
TextDrawBackgroundColor(ReportTXT[2], 51);
TextDrawFont(ReportTXT[2], 2);
TextDrawSetProportional(ReportTXT[2], 1);
