    Mofsma_TD[0] = TextDrawCreate(-7.5109, 438.4999, "Box"); // ?????
	TextDrawLetterSize(Mofsma_TD[0], 0.0000, 1.1918);
	TextDrawTextSize(Mofsma_TD[0], 646.0000, 0.0000);
	TextDrawAlignment(Mofsma_TD[0], 1);
	TextDrawColor(Mofsma_TD[0], -1);
	TextDrawUseBox(Mofsma_TD[0], 1);
	TextDrawBoxColor(Mofsma_TD[0], 218959359);
	TextDrawBackgroundColor(Mofsma_TD[0], 255);
	TextDrawFont(Mofsma_TD[0], 1);
	TextDrawSetProportional(Mofsma_TD[0], 1);
	TextDrawSetShadow(Mofsma_TD[0], 0);

	Mofsma_TD[1] = TextDrawCreate(275.9443, 416.3333, "PISSING....."); // ?????
	TextDrawLetterSize(Mofsma_TD[1], 0.4023, 1.7925);
	TextDrawAlignment(Mofsma_TD[1], 1);
	TextDrawColor(Mofsma_TD[1], -1);
	TextDrawBackgroundColor(Mofsma_TD[1], 255);
	TextDrawFont(Mofsma_TD[1], 2);
	TextDrawSetProportional(Mofsma_TD[1], 1);
	TextDrawSetShadow(Mofsma_TD[1], 0);