/* =================== << [ Aksesuarebis TextDraw ] >> ================== */
 	GenuineBar[playerid][0] = CreatePlayerTextDraw(playerid, 524.000000, 304.962493, "box");
	PlayerTextDrawLetterSize(playerid, GenuineBar[playerid][0], 0.000000, 0.922999);
	PlayerTextDrawTextSize(playerid, GenuineBar[playerid][0], 620.849853, 0.000000);
	PlayerTextDrawAlignment(playerid, GenuineBar[playerid][0], 1);
	PlayerTextDrawColor(playerid, GenuineBar[playerid][0], -1);
	PlayerTextDrawUseBox(playerid, GenuineBar[playerid][0], 1);
	PlayerTextDrawBoxColor(playerid, GenuineBar[playerid][0], 48);
	PlayerTextDrawSetShadow(playerid, GenuineBar[playerid][0], 0);
	PlayerTextDrawBackgroundColor(playerid, GenuineBar[playerid][0], 255);
	PlayerTextDrawFont(playerid, GenuineBar[playerid][0], 1);
	PlayerTextDrawSetProportional(playerid, GenuineBar[playerid][0], 1);

	GenuineBar[playerid][1] = CreatePlayerTextDraw(playerid, 522.500244, 303.724945, "LD_SPAC:white");
	PlayerTextDrawTextSize(playerid, GenuineBar[playerid][1], 100.000000, 11.039978);
	PlayerTextDrawAlignment(playerid, GenuineBar[playerid][1], 1);
	PlayerTextDrawColor(playerid, GenuineBar[playerid][1], -231196417);
	PlayerTextDrawSetShadow(playerid, GenuineBar[playerid][1], 0);
	PlayerTextDrawBackgroundColor(playerid, GenuineBar[playerid][1], 255);
	PlayerTextDrawFont(playerid, GenuineBar[playerid][1], 4);
	PlayerTextDrawSetProportional(playerid, GenuineBar[playerid][1], 0);

	GenuineBar[playerid][2] = CreatePlayerTextDraw(playerid, 524.000000, 319.163360, "box");
	PlayerTextDrawLetterSize(playerid, GenuineBar[playerid][2], 0.000000, 0.922999);
	PlayerTextDrawTextSize(playerid, GenuineBar[playerid][2], 620.849853, 0.000000);
	PlayerTextDrawAlignment(playerid, GenuineBar[playerid][2], 1);
	PlayerTextDrawColor(playerid, GenuineBar[playerid][2], -1);
	PlayerTextDrawUseBox(playerid, GenuineBar[playerid][2], 1);
	PlayerTextDrawBoxColor(playerid, GenuineBar[playerid][2], 48);
	PlayerTextDrawSetShadow(playerid, GenuineBar[playerid][2], 0);
	PlayerTextDrawBackgroundColor(playerid, GenuineBar[playerid][2], 255);
	PlayerTextDrawFont(playerid, GenuineBar[playerid][2], 1);
	PlayerTextDrawSetProportional(playerid, GenuineBar[playerid][2], 1);

	GenuineBar[playerid][3] = CreatePlayerTextDraw(playerid, 522.500244, 317.725799, "LD_SPAC:white");
	PlayerTextDrawTextSize(playerid, GenuineBar[playerid][3], 100.000000, 11.039978);
	PlayerTextDrawAlignment(playerid, GenuineBar[playerid][3], 1);
	PlayerTextDrawColor(playerid, GenuineBar[playerid][3], -562552833);
	PlayerTextDrawSetShadow(playerid, GenuineBar[playerid][3], 0);
	PlayerTextDrawBackgroundColor(playerid, GenuineBar[playerid][3], 255);
	PlayerTextDrawFont(playerid, GenuineBar[playerid][3], 4);
	PlayerTextDrawSetProportional(playerid, GenuineBar[playerid][3], 0);

	GenuineBar[playerid][4] = CreatePlayerTextDraw(playerid, 524.000000, 333.264221, "box");
	PlayerTextDrawLetterSize(playerid, GenuineBar[playerid][4], 0.000000, 0.922999);
	PlayerTextDrawTextSize(playerid, GenuineBar[playerid][4], 620.849853, 0.000000);
	PlayerTextDrawAlignment(playerid, GenuineBar[playerid][4], 1);
	PlayerTextDrawColor(playerid, GenuineBar[playerid][4], -1);
	PlayerTextDrawUseBox(playerid, GenuineBar[playerid][4], 1);
	PlayerTextDrawBoxColor(playerid, GenuineBar[playerid][4], 48);
	PlayerTextDrawSetShadow(playerid, GenuineBar[playerid][4], 0);
	PlayerTextDrawBackgroundColor(playerid, GenuineBar[playerid][4], 255);
	PlayerTextDrawFont(playerid, GenuineBar[playerid][4], 1);
	PlayerTextDrawSetProportional(playerid, GenuineBar[playerid][4], 1);

	GenuineBar[playerid][5] = CreatePlayerTextDraw(playerid, 522.400390, 331.826660, "LD_SPAC:white");
	PlayerTextDrawTextSize(playerid, GenuineBar[playerid][5], 100.000000, 11.039978);
	PlayerTextDrawAlignment(playerid, GenuineBar[playerid][5], 1);
	PlayerTextDrawColor(playerid, GenuineBar[playerid][5], 715907327);
	PlayerTextDrawSetShadow(playerid, GenuineBar[playerid][5], 0);
	PlayerTextDrawBackgroundColor(playerid, GenuineBar[playerid][5], 255);
	PlayerTextDrawFont(playerid, GenuineBar[playerid][5], 4);
	PlayerTextDrawSetProportional(playerid, GenuineBar[playerid][5], 0);

	GenuineBar[playerid][6] = CreatePlayerTextDraw(playerid, 561.599365, 304.300140, "55/100");
	PlayerTextDrawLetterSize(playerid, GenuineBar[playerid][6], 0.191500, 0.996251);
	PlayerTextDrawAlignment(playerid, GenuineBar[playerid][6], 1);
	PlayerTextDrawColor(playerid, GenuineBar[playerid][6], -1);
	PlayerTextDrawSetShadow(playerid, GenuineBar[playerid][6], 0);
	PlayerTextDrawBackgroundColor(playerid, GenuineBar[playerid][6], 255);
	PlayerTextDrawFont(playerid, GenuineBar[playerid][6], 2);
	PlayerTextDrawSetProportional(playerid, GenuineBar[playerid][6], 1);

	GenuineBar[playerid][7] = CreatePlayerTextDraw(playerid, 561.599365, 318.300994, "55/100");
	PlayerTextDrawLetterSize(playerid, GenuineBar[playerid][7], 0.191500, 0.996251);
	PlayerTextDrawAlignment(playerid, GenuineBar[playerid][7], 1);
	PlayerTextDrawColor(playerid, GenuineBar[playerid][7], -1);
	PlayerTextDrawSetShadow(playerid, GenuineBar[playerid][7], 0);
	PlayerTextDrawBackgroundColor(playerid, GenuineBar[playerid][7], 255);
	PlayerTextDrawFont(playerid, GenuineBar[playerid][7], 2);
	PlayerTextDrawSetProportional(playerid, GenuineBar[playerid][7], 1);

	GenuineBar[playerid][8] = CreatePlayerTextDraw(playerid, 561.599365, 332.001831, "55/100");
	PlayerTextDrawLetterSize(playerid, GenuineBar[playerid][8], 0.191500, 0.996251);
	PlayerTextDrawAlignment(playerid, GenuineBar[playerid][8], 1);
	PlayerTextDrawColor(playerid, GenuineBar[playerid][8], -1);
	PlayerTextDrawSetShadow(playerid, GenuineBar[playerid][8], 0);
	PlayerTextDrawBackgroundColor(playerid, GenuineBar[playerid][8], 255);
	PlayerTextDrawFont(playerid, GenuineBar[playerid][8], 2);
	PlayerTextDrawSetProportional(playerid, GenuineBar[playerid][8], 1);
