InventoryTD[playerid][0] = CreatePlayerTextDraw(playerid, 435.0000, 124.8125, "Box"); // ?????
	PlayerTextDrawLetterSize(playerid, InventoryTD[playerid][0], 0.0000, 21.9500);
	PlayerTextDrawTextSize(playerid, InventoryTD[playerid][0], 617.8671, 0.0000);
	PlayerTextDrawAlignment(playerid, InventoryTD[playerid][0], 1);
	PlayerTextDrawColor(playerid, InventoryTD[playerid][0], -1);
	PlayerTextDrawUseBox(playerid, InventoryTD[playerid][0], 1);
	PlayerTextDrawBoxColor(playerid, InventoryTD[playerid][0], 387917311);
	PlayerTextDrawBackgroundColor(playerid, InventoryTD[playerid][0], 255);
	PlayerTextDrawFont(playerid, InventoryTD[playerid][0], 1);
	PlayerTextDrawSetProportional(playerid, InventoryTD[playerid][0], 1);
	PlayerTextDrawSetShadow(playerid, InventoryTD[playerid][0], 0);

	InventoryTD[playerid][1] = CreatePlayerTextDraw(playerid, 325.3998, 140.1250, "Box"); // ?????
	PlayerTextDrawLetterSize(playerid, InventoryTD[playerid][1], 0.0000, 18.6499);
	PlayerTextDrawTextSize(playerid, InventoryTD[playerid][1], 432.3998, 0.0000);
	PlayerTextDrawAlignment(playerid, InventoryTD[playerid][1], 1);
	PlayerTextDrawColor(playerid, InventoryTD[playerid][1], -1);
	PlayerTextDrawUseBox(playerid, InventoryTD[playerid][1], 1);
	PlayerTextDrawBoxColor(playerid, InventoryTD[playerid][1], 387917311);
	PlayerTextDrawBackgroundColor(playerid, InventoryTD[playerid][1], 255);
	PlayerTextDrawFont(playerid, InventoryTD[playerid][1], 1);
	PlayerTextDrawSetProportional(playerid, InventoryTD[playerid][1], 1);
	PlayerTextDrawSetShadow(playerid, InventoryTD[playerid][1], 0);

	InventoryTD[playerid][2] = CreatePlayerTextDraw(playerid, 569.5996, 124.9123, "Box"); // ?????
	PlayerTextDrawLetterSize(playerid, InventoryTD[playerid][2], 0.0000, 1.3500);
	PlayerTextDrawTextSize(playerid, InventoryTD[playerid][2], 617.4702, 0.0000);
	PlayerTextDrawAlignment(playerid, InventoryTD[playerid][2], 1);
	PlayerTextDrawColor(playerid, InventoryTD[playerid][2], -1);
	PlayerTextDrawUseBox(playerid, InventoryTD[playerid][2], 1);
	PlayerTextDrawBoxColor(playerid, InventoryTD[playerid][2], 492341247);
	PlayerTextDrawBackgroundColor(playerid, InventoryTD[playerid][2], 255);
	PlayerTextDrawFont(playerid, InventoryTD[playerid][2], 1);
	PlayerTextDrawSetProportional(playerid, InventoryTD[playerid][2], 1);
	PlayerTextDrawSetShadow(playerid, InventoryTD[playerid][2], 0);

	InventoryTD[playerid][3] = CreatePlayerTextDraw(playerid, 422.4991, 140.0874, "Box"); // ?????
	PlayerTextDrawLetterSize(playerid, InventoryTD[playerid][3], 0.0000, -0.2495);
	PlayerTextDrawTextSize(playerid, InventoryTD[playerid][3], 617.6237, 0.0000);
	PlayerTextDrawAlignment(playerid, InventoryTD[playerid][3], 1);
	PlayerTextDrawColor(playerid, InventoryTD[playerid][3], -1);
	PlayerTextDrawUseBox(playerid, InventoryTD[playerid][3], 1);
	PlayerTextDrawBoxColor(playerid, InventoryTD[playerid][3], 492341247);
	PlayerTextDrawBackgroundColor(playerid, InventoryTD[playerid][3], 255);
	PlayerTextDrawFont(playerid, InventoryTD[playerid][3], 1);
	PlayerTextDrawSetProportional(playerid, InventoryTD[playerid][3], 1);
	PlayerTextDrawSetShadow(playerid, InventoryTD[playerid][3], 0);

	InventoryTD[playerid][4] = CreatePlayerTextDraw(playerid, 387.6997, 140.0623, "Box"); // ?????
	PlayerTextDrawLetterSize(playerid, InventoryTD[playerid][4], 0.0000, 1.2000);
	PlayerTextDrawTextSize(playerid, InventoryTD[playerid][4], 431.1000, 0.0000);
	PlayerTextDrawAlignment(playerid, InventoryTD[playerid][4], 1);
	PlayerTextDrawColor(playerid, InventoryTD[playerid][4], -1);
	PlayerTextDrawUseBox(playerid, InventoryTD[playerid][4], 1);
	PlayerTextDrawBoxColor(playerid, InventoryTD[playerid][4], 492341247);
	PlayerTextDrawBackgroundColor(playerid, InventoryTD[playerid][4], 255);
	PlayerTextDrawFont(playerid, InventoryTD[playerid][4], 1);
	PlayerTextDrawSetProportional(playerid, InventoryTD[playerid][4], 1);
	PlayerTextDrawSetShadow(playerid, InventoryTD[playerid][4], 0);

	InventoryTD[playerid][5] = CreatePlayerTextDraw(playerid, 325.5997, 153.0749, "Box"); // ?????
	PlayerTextDrawLetterSize(playerid, InventoryTD[playerid][5], 0.0000, -0.2266);
	PlayerTextDrawTextSize(playerid, InventoryTD[playerid][5], 430.5999, 0.0000);
	PlayerTextDrawAlignment(playerid, InventoryTD[playerid][5], 1);
	PlayerTextDrawColor(playerid, InventoryTD[playerid][5], -1);
	PlayerTextDrawUseBox(playerid, InventoryTD[playerid][5], 1);
	PlayerTextDrawBoxColor(playerid, InventoryTD[playerid][5], 492341247);
	PlayerTextDrawBackgroundColor(playerid, InventoryTD[playerid][5], 255);
	PlayerTextDrawFont(playerid, InventoryTD[playerid][5], 1);
	PlayerTextDrawSetProportional(playerid, InventoryTD[playerid][5], 1);
	PlayerTextDrawSetShadow(playerid, InventoryTD[playerid][5], 0);

	InventoryTD[playerid][6] = CreatePlayerTextDraw(playerid, 399.0000, 140.1250, "PLAYER"); // ?????
	PlayerTextDrawLetterSize(playerid, InventoryTD[playerid][6], 0.1509, 0.9700);
	PlayerTextDrawAlignment(playerid, InventoryTD[playerid][6], 1);
	PlayerTextDrawColor(playerid, InventoryTD[playerid][6], -1);
	PlayerTextDrawBackgroundColor(playerid, InventoryTD[playerid][6], 255);
	PlayerTextDrawFont(playerid, InventoryTD[playerid][6], 2);
	PlayerTextDrawSetProportional(playerid, InventoryTD[playerid][6], 1);
	PlayerTextDrawSetShadow(playerid, InventoryTD[playerid][6], 0);

	InventoryTD[playerid][7] = CreatePlayerTextDraw(playerid, 575.8015, 125.3871, "INVENTORY"); // ?????
	PlayerTextDrawLetterSize(playerid, InventoryTD[playerid][7], 0.1659, 1.1275);
	PlayerTextDrawAlignment(playerid, InventoryTD[playerid][7], 1);
	PlayerTextDrawColor(playerid, InventoryTD[playerid][7], -1);
	PlayerTextDrawBackgroundColor(playerid, InventoryTD[playerid][7], 255);
	PlayerTextDrawFont(playerid, InventoryTD[playerid][7], 2);
	PlayerTextDrawSetProportional(playerid, InventoryTD[playerid][7], 1);
	PlayerTextDrawSetShadow(playerid, InventoryTD[playerid][7], 0);

	InventoryTD[playerid][8] = CreatePlayerTextDraw(playerid, 435.0997, 140.2492, "Box"); // ?????
	PlayerTextDrawLetterSize(playerid, InventoryTD[playerid][8], 0.0000, 20.2229);
	PlayerTextDrawTextSize(playerid, InventoryTD[playerid][8], 432.0000, 0.0000);
	PlayerTextDrawAlignment(playerid, InventoryTD[playerid][8], 1);
	PlayerTextDrawColor(playerid, InventoryTD[playerid][8], -1);
	PlayerTextDrawUseBox(playerid, InventoryTD[playerid][8], 1);
	PlayerTextDrawBoxColor(playerid, InventoryTD[playerid][8], 492341247);
	PlayerTextDrawBackgroundColor(playerid, InventoryTD[playerid][8], 255);
	PlayerTextDrawFont(playerid, InventoryTD[playerid][8], 1);
	PlayerTextDrawSetProportional(playerid, InventoryTD[playerid][8], 1);
	PlayerTextDrawSetShadow(playerid, InventoryTD[playerid][8], 0);

	InventoryTD[playerid][9] = CreatePlayerTextDraw(playerid, 435.1997, 324.1365, "Box"); // ?????
	PlayerTextDrawLetterSize(playerid, InventoryTD[playerid][9], 0.0000, -0.2266);
	PlayerTextDrawTextSize(playerid, InventoryTD[playerid][9], 617.7479, 0.0000);
	PlayerTextDrawAlignment(playerid, InventoryTD[playerid][9], 1);
	PlayerTextDrawColor(playerid, InventoryTD[playerid][9], -1);
	PlayerTextDrawUseBox(playerid, InventoryTD[playerid][9], 1);
	PlayerTextDrawBoxColor(playerid, InventoryTD[playerid][9], 492341247);
	PlayerTextDrawBackgroundColor(playerid, InventoryTD[playerid][9], 255);
	PlayerTextDrawFont(playerid, InventoryTD[playerid][9], 1);
	PlayerTextDrawSetProportional(playerid, InventoryTD[playerid][9], 1);
	PlayerTextDrawSetShadow(playerid, InventoryTD[playerid][9], 0);

	InventoryTD[playerid][10] = CreatePlayerTextDraw(playerid, 325.5997, 309.5617, "Box"); // ?????
	PlayerTextDrawLetterSize(playerid, InventoryTD[playerid][10], 0.0000, -0.2266);
	PlayerTextDrawTextSize(playerid, InventoryTD[playerid][10], 432.0000, 0.0000);
	PlayerTextDrawAlignment(playerid, InventoryTD[playerid][10], 1);
	PlayerTextDrawColor(playerid, InventoryTD[playerid][10], -1);
	PlayerTextDrawUseBox(playerid, InventoryTD[playerid][10], 1);
	PlayerTextDrawBoxColor(playerid, InventoryTD[playerid][10], 492341247);
	PlayerTextDrawBackgroundColor(playerid, InventoryTD[playerid][10], 255);
	PlayerTextDrawFont(playerid, InventoryTD[playerid][10], 1);
	PlayerTextDrawSetProportional(playerid, InventoryTD[playerid][10], 1);
	PlayerTextDrawSetShadow(playerid, InventoryTD[playerid][10], 0);

	InventoryTD[playerid][11] = CreatePlayerTextDraw(playerid, 306.0000, 156.3125, ""); // ?????
	PlayerTextDrawTextSize(playerid, InventoryTD[playerid][11], 119.0000, 79.0000);
	PlayerTextDrawAlignment(playerid, InventoryTD[playerid][11], 1);
	PlayerTextDrawColor(playerid, InventoryTD[playerid][11], -1);
	PlayerTextDrawBackgroundColor(playerid, InventoryTD[playerid][11], 1090519040);
	PlayerTextDrawFont(playerid, InventoryTD[playerid][11], 5);
	PlayerTextDrawSetProportional(playerid, InventoryTD[playerid][11], 0);
	PlayerTextDrawSetShadow(playerid, InventoryTD[playerid][11], 0);
	PlayerTextDrawSetPreviewModel(playerid, InventoryTD[playerid][11], 0);
	PlayerTextDrawSetPreviewRot(playerid, InventoryTD[playerid][11], 0.0000, 0.0000, 0.0000, 1.0000);

	InventoryTD[playerid][12] = CreatePlayerTextDraw(playerid, 328.3999, 244.6875, "LD_SPAC:white"); // ?????
	PlayerTextDrawTextSize(playerid, InventoryTD[playerid][12], 47.0000, 16.0000);
	PlayerTextDrawAlignment(playerid, InventoryTD[playerid][12], 1);
	PlayerTextDrawColor(playerid, InventoryTD[playerid][12], 1216326655);
	PlayerTextDrawBackgroundColor(playerid, InventoryTD[playerid][12], 255);
	PlayerTextDrawFont(playerid, InventoryTD[playerid][12], 4);
	PlayerTextDrawSetProportional(playerid, InventoryTD[playerid][12], 0);
	PlayerTextDrawSetShadow(playerid, InventoryTD[playerid][12], 0);
	PlayerTextDrawSetSelectable(playerid, InventoryTD[playerid][12], true);

	InventoryTD[playerid][13] = CreatePlayerTextDraw(playerid, 380.3031, 244.6875, "LD_SPAC:white"); // ?????
	PlayerTextDrawTextSize(playerid, InventoryTD[playerid][13], 47.0000, 16.0000);
	PlayerTextDrawAlignment(playerid, InventoryTD[playerid][13], 1);
	PlayerTextDrawColor(playerid, InventoryTD[playerid][13], 1216326655);
	PlayerTextDrawBackgroundColor(playerid, InventoryTD[playerid][13], 255);
	PlayerTextDrawFont(playerid, InventoryTD[playerid][13], 4);
	PlayerTextDrawSetProportional(playerid, InventoryTD[playerid][13], 0);
	PlayerTextDrawSetShadow(playerid, InventoryTD[playerid][13], 0);
	PlayerTextDrawSetSelectable(playerid, InventoryTD[playerid][13], true);

	InventoryTD[playerid][14] = CreatePlayerTextDraw(playerid, 328.5032, 264.8125, "LD_SPAC:white"); // ?????
	PlayerTextDrawTextSize(playerid, InventoryTD[playerid][14], 47.0000, 16.0000);
	PlayerTextDrawAlignment(playerid, InventoryTD[playerid][14], 1);
	PlayerTextDrawColor(playerid, InventoryTD[playerid][14], 1013682431);
	PlayerTextDrawBackgroundColor(playerid, InventoryTD[playerid][14], 255);
	PlayerTextDrawFont(playerid, InventoryTD[playerid][14], 4);
	PlayerTextDrawSetProportional(playerid, InventoryTD[playerid][14], 0);
	PlayerTextDrawSetShadow(playerid, InventoryTD[playerid][14], 0);
	PlayerTextDrawSetSelectable(playerid, InventoryTD[playerid][14], true);

	InventoryTD[playerid][15] = CreatePlayerTextDraw(playerid, 380.2062, 264.8125, "LD_SPAC:white"); // ?????
	PlayerTextDrawTextSize(playerid, InventoryTD[playerid][15], 47.0000, 16.0000);
	PlayerTextDrawAlignment(playerid, InventoryTD[playerid][15], 1);
	PlayerTextDrawColor(playerid, InventoryTD[playerid][15], 1013682431);
	PlayerTextDrawBackgroundColor(playerid, InventoryTD[playerid][15], 255);
	PlayerTextDrawFont(playerid, InventoryTD[playerid][15], 4);
	PlayerTextDrawSetProportional(playerid, InventoryTD[playerid][15], 0);
	PlayerTextDrawSetShadow(playerid, InventoryTD[playerid][15], 0);
	PlayerTextDrawSetSelectable(playerid, InventoryTD[playerid][15], true);

	InventoryTD[playerid][16] = CreatePlayerTextDraw(playerid, 328.5032, 285.0137, "LD_SPAC:white"); // ?????
	PlayerTextDrawTextSize(playerid, InventoryTD[playerid][16], 47.0000, 16.0000);
	PlayerTextDrawAlignment(playerid, InventoryTD[playerid][16], 1);
	PlayerTextDrawColor(playerid, InventoryTD[playerid][16], 793931519);
	PlayerTextDrawBackgroundColor(playerid, InventoryTD[playerid][16], 255);
	PlayerTextDrawFont(playerid, InventoryTD[playerid][16], 4);
	PlayerTextDrawSetProportional(playerid, InventoryTD[playerid][16], 0);
	PlayerTextDrawSetShadow(playerid, InventoryTD[playerid][16], 0);
	PlayerTextDrawSetSelectable(playerid, InventoryTD[playerid][16], true);

	InventoryTD[playerid][17] = CreatePlayerTextDraw(playerid, 380.2062, 285.0137, "LD_SPAC:white"); // ?????
	PlayerTextDrawTextSize(playerid, InventoryTD[playerid][17], 47.0000, 16.0000);
	PlayerTextDrawAlignment(playerid, InventoryTD[playerid][17], 1);
	PlayerTextDrawColor(playerid, InventoryTD[playerid][17], 793931519);
	PlayerTextDrawBackgroundColor(playerid, InventoryTD[playerid][17], 255);
	PlayerTextDrawFont(playerid, InventoryTD[playerid][17], 4);
	PlayerTextDrawSetProportional(playerid, InventoryTD[playerid][17], 0);
	PlayerTextDrawSetShadow(playerid, InventoryTD[playerid][17], 0);
	PlayerTextDrawSetSelectable(playerid, InventoryTD[playerid][17], true);

	InventoryTD[playerid][18] = CreatePlayerTextDraw(playerid, 341.4996, 247.7500, "MENU"); // ?????
	PlayerTextDrawLetterSize(playerid, InventoryTD[playerid][18], 0.1700, 1.0398);
	PlayerTextDrawAlignment(playerid, InventoryTD[playerid][18], 1);
	PlayerTextDrawColor(playerid, InventoryTD[playerid][18], -1);
	PlayerTextDrawBackgroundColor(playerid, InventoryTD[playerid][18], 255);
	PlayerTextDrawFont(playerid, InventoryTD[playerid][18], 2);
	PlayerTextDrawSetProportional(playerid, InventoryTD[playerid][18], 1);
	PlayerTextDrawSetShadow(playerid, InventoryTD[playerid][18], 0);

	InventoryTD[playerid][19] = CreatePlayerTextDraw(playerid, 387.4996, 247.7500, "COMMAND"); // ?????
	PlayerTextDrawLetterSize(playerid, InventoryTD[playerid][19], 0.1700, 1.0398);
	PlayerTextDrawAlignment(playerid, InventoryTD[playerid][19], 1);
	PlayerTextDrawColor(playerid, InventoryTD[playerid][19], -1);
	PlayerTextDrawBackgroundColor(playerid, InventoryTD[playerid][19], 255);
	PlayerTextDrawFont(playerid, InventoryTD[playerid][19], 2);
	PlayerTextDrawSetProportional(playerid, InventoryTD[playerid][19], 1);
	PlayerTextDrawSetShadow(playerid, InventoryTD[playerid][19], 0);

	InventoryTD[playerid][20] = CreatePlayerTextDraw(playerid, 338.2998, 267.2124, "REPORT"); // ?????
	PlayerTextDrawLetterSize(playerid, InventoryTD[playerid][20], 0.1700, 1.0398);
	PlayerTextDrawAlignment(playerid, InventoryTD[playerid][20], 1);
	PlayerTextDrawColor(playerid, InventoryTD[playerid][20], -1);
	PlayerTextDrawBackgroundColor(playerid, InventoryTD[playerid][20], 255);
	PlayerTextDrawFont(playerid, InventoryTD[playerid][20], 2);
	PlayerTextDrawSetProportional(playerid, InventoryTD[playerid][20], 1);
	PlayerTextDrawSetShadow(playerid, InventoryTD[playerid][20], 0);

	InventoryTD[playerid][21] = CreatePlayerTextDraw(playerid, 387.8995, 267.4124, "SECURITY"); // ?????
	PlayerTextDrawLetterSize(playerid, InventoryTD[playerid][21], 0.1700, 1.0398);
	PlayerTextDrawAlignment(playerid, InventoryTD[playerid][21], 1);
	PlayerTextDrawColor(playerid, InventoryTD[playerid][21], -1);
	PlayerTextDrawBackgroundColor(playerid, InventoryTD[playerid][21], 255);
	PlayerTextDrawFont(playerid, InventoryTD[playerid][21], 2);
	PlayerTextDrawSetProportional(playerid, InventoryTD[playerid][21], 1);
	PlayerTextDrawSetShadow(playerid, InventoryTD[playerid][21], 0);

	InventoryTD[playerid][22] = CreatePlayerTextDraw(playerid, 337.6997, 287.5747, "DONATE"); // ?????
	PlayerTextDrawLetterSize(playerid, InventoryTD[playerid][22], 0.1700, 1.0398);
	PlayerTextDrawAlignment(playerid, InventoryTD[playerid][22], 1);
	PlayerTextDrawColor(playerid, InventoryTD[playerid][22], -1);
	PlayerTextDrawBackgroundColor(playerid, InventoryTD[playerid][22], 255);
	PlayerTextDrawFont(playerid, InventoryTD[playerid][22], 2);
	PlayerTextDrawSetProportional(playerid, InventoryTD[playerid][22], 1);
	PlayerTextDrawSetShadow(playerid, InventoryTD[playerid][22], 0);

	InventoryTD[playerid][23] = CreatePlayerTextDraw(playerid, 387.1994, 287.5747, "SETTINGS"); // ?????
	PlayerTextDrawLetterSize(playerid, InventoryTD[playerid][23], 0.1700, 1.0398);
	PlayerTextDrawAlignment(playerid, InventoryTD[playerid][23], 1);
	PlayerTextDrawColor(playerid, InventoryTD[playerid][23], -1);
	PlayerTextDrawBackgroundColor(playerid, InventoryTD[playerid][23], 255);
	PlayerTextDrawFont(playerid, InventoryTD[playerid][23], 2);
	PlayerTextDrawSetProportional(playerid, InventoryTD[playerid][23], 1);
	PlayerTextDrawSetShadow(playerid, InventoryTD[playerid][23], 0);

	InventoryTD[playerid][24] = CreatePlayerTextDraw(playerid, 330.5000, 140.5625, "HP_:_100"); // ?????
	PlayerTextDrawLetterSize(playerid, InventoryTD[playerid][24], 0.1298, 0.8866);
	PlayerTextDrawAlignment(playerid, InventoryTD[playerid][24], 1);
	PlayerTextDrawColor(playerid, InventoryTD[playerid][24], -1);
	PlayerTextDrawBackgroundColor(playerid, InventoryTD[playerid][24], 255);
	PlayerTextDrawFont(playerid, InventoryTD[playerid][24], 2);
	PlayerTextDrawSetProportional(playerid, InventoryTD[playerid][24], 1);
	PlayerTextDrawSetShadow(playerid, InventoryTD[playerid][24], 0);

	InventoryTD[playerid][25] = CreatePlayerTextDraw(playerid, 358.0000, 140.5625, "ARM_:_100"); // ?????
	PlayerTextDrawLetterSize(playerid, InventoryTD[playerid][25], 0.1298, 0.8866);
	PlayerTextDrawAlignment(playerid, InventoryTD[playerid][25], 1);
	PlayerTextDrawColor(playerid, InventoryTD[playerid][25], -1);
	PlayerTextDrawBackgroundColor(playerid, InventoryTD[playerid][25], 255);
	PlayerTextDrawFont(playerid, InventoryTD[playerid][25], 2);
	PlayerTextDrawSetProportional(playerid, InventoryTD[playerid][25], 1);
	PlayerTextDrawSetShadow(playerid, InventoryTD[playerid][25], 0);

	InventoryTD[playerid][26] = CreatePlayerTextDraw(playerid, 337.0997, 313.7496, "Box"); // ?????
	PlayerTextDrawLetterSize(playerid, InventoryTD[playerid][26], 0.0000, 1.5310);
	PlayerTextDrawTextSize(playerid, InventoryTD[playerid][26], 416.7066, 0.0000);
	PlayerTextDrawAlignment(playerid, InventoryTD[playerid][26], 1);
	PlayerTextDrawColor(playerid, InventoryTD[playerid][26], -1);
	PlayerTextDrawUseBox(playerid, InventoryTD[playerid][26], 1);
	PlayerTextDrawBoxColor(playerid, InventoryTD[playerid][26], 387917311);
	PlayerTextDrawBackgroundColor(playerid, InventoryTD[playerid][26], 255);
	PlayerTextDrawFont(playerid, InventoryTD[playerid][26], 1);
	PlayerTextDrawSetProportional(playerid, InventoryTD[playerid][26], 1);
	PlayerTextDrawSetShadow(playerid, InventoryTD[playerid][26], 0);

	InventoryTD[playerid][27] = CreatePlayerTextDraw(playerid, 336.6000, 313.7496, "LD_SPAC:white"); // ?????
	PlayerTextDrawTextSize(playerid, InventoryTD[playerid][27], 26.0000, 14.0000);
	PlayerTextDrawAlignment(playerid, InventoryTD[playerid][27], 1);
	PlayerTextDrawColor(playerid, InventoryTD[playerid][27], 1216326655);
	PlayerTextDrawBackgroundColor(playerid, InventoryTD[playerid][27], 255);
	PlayerTextDrawFont(playerid, InventoryTD[playerid][27], 4);
	PlayerTextDrawSetProportional(playerid, InventoryTD[playerid][27], 0);
	PlayerTextDrawSetShadow(playerid, InventoryTD[playerid][27], 0);
	PlayerTextDrawSetSelectable(playerid, InventoryTD[playerid][27], true);

	InventoryTD[playerid][28] = CreatePlayerTextDraw(playerid, 364.1018, 313.7496, "LD_SPAC:white"); // ?????
	PlayerTextDrawTextSize(playerid, InventoryTD[playerid][28], 26.0000, 14.0000);
	PlayerTextDrawAlignment(playerid, InventoryTD[playerid][28], 1);
	PlayerTextDrawColor(playerid, InventoryTD[playerid][28], 1216326655);
	PlayerTextDrawBackgroundColor(playerid, InventoryTD[playerid][28], 255);
	PlayerTextDrawFont(playerid, InventoryTD[playerid][28], 4);
	PlayerTextDrawSetProportional(playerid, InventoryTD[playerid][28], 0);
	PlayerTextDrawSetShadow(playerid, InventoryTD[playerid][28], 0);
	PlayerTextDrawSetSelectable(playerid, InventoryTD[playerid][28], true);

	InventoryTD[playerid][29] = CreatePlayerTextDraw(playerid, 391.4034, 313.7496, "LD_SPAC:white"); // ?????
	PlayerTextDrawTextSize(playerid, InventoryTD[playerid][29], 26.0000, 14.0000);
	PlayerTextDrawAlignment(playerid, InventoryTD[playerid][29], 1);
	PlayerTextDrawColor(playerid, InventoryTD[playerid][29], 1216326655);
	PlayerTextDrawBackgroundColor(playerid, InventoryTD[playerid][29], 255);
	PlayerTextDrawFont(playerid, InventoryTD[playerid][29], 4);
	PlayerTextDrawSetProportional(playerid, InventoryTD[playerid][29], 0);
	PlayerTextDrawSetShadow(playerid, InventoryTD[playerid][29], 0);
	PlayerTextDrawSetSelectable(playerid, InventoryTD[playerid][29], true);

	InventoryTD[playerid][30] = CreatePlayerTextDraw(playerid, 341.0000, 315.1250, "PUT"); // ?????
	PlayerTextDrawLetterSize(playerid, InventoryTD[playerid][30], 0.2105, 1.1187);
	PlayerTextDrawAlignment(playerid, InventoryTD[playerid][30], 1);
	PlayerTextDrawColor(playerid, InventoryTD[playerid][30], -1);
	PlayerTextDrawBackgroundColor(playerid, InventoryTD[playerid][30], 255);
	PlayerTextDrawFont(playerid, InventoryTD[playerid][30], 2);
	PlayerTextDrawSetProportional(playerid, InventoryTD[playerid][30], 1);
	PlayerTextDrawSetShadow(playerid, InventoryTD[playerid][30], 0);

	InventoryTD[playerid][31] = CreatePlayerTextDraw(playerid, 368.8999, 315.1499, "REM"); // ?????
	PlayerTextDrawLetterSize(playerid, InventoryTD[playerid][31], 0.2105, 1.1187);
	PlayerTextDrawTextSize(playerid, InventoryTD[playerid][31], 29.0000, 0.0000);
	PlayerTextDrawAlignment(playerid, InventoryTD[playerid][31], 1);
	PlayerTextDrawColor(playerid, InventoryTD[playerid][31], -1);
	PlayerTextDrawBackgroundColor(playerid, InventoryTD[playerid][31], 255);
	PlayerTextDrawFont(playerid, InventoryTD[playerid][31], 2);
	PlayerTextDrawSetProportional(playerid, InventoryTD[playerid][31], 1);
	PlayerTextDrawSetShadow(playerid, InventoryTD[playerid][31], 0);

	InventoryTD[playerid][32] = CreatePlayerTextDraw(playerid, 394.7998, 314.8500, "DEL"); // ?????
	PlayerTextDrawLetterSize(playerid, InventoryTD[playerid][32], 0.2105, 1.1187);
	PlayerTextDrawTextSize(playerid, InventoryTD[playerid][32], 29.0000, 0.0000);
	PlayerTextDrawAlignment(playerid, InventoryTD[playerid][32], 1);
	PlayerTextDrawColor(playerid, InventoryTD[playerid][32], -1);
	PlayerTextDrawBackgroundColor(playerid, InventoryTD[playerid][32], 255);
	PlayerTextDrawFont(playerid, InventoryTD[playerid][32], 2);
	PlayerTextDrawSetProportional(playerid, InventoryTD[playerid][32], 1);
	PlayerTextDrawSetShadow(playerid, InventoryTD[playerid][32], 0);
	//
	InventoryTD[playerid][33] = CreatePlayerTextDraw(playerid, 360.5270, 158.9568, "LD_SPAC:white"); // ?????
	PlayerTextDrawTextSize(playerid, InventoryTD[playerid][33], 65.0000, 21.0000);
	PlayerTextDrawAlignment(playerid, InventoryTD[playerid][33], 1);
	PlayerTextDrawColor(playerid, InventoryTD[playerid][33], 845713407);
	PlayerTextDrawBackgroundColor(playerid, InventoryTD[playerid][33], 255);
	PlayerTextDrawFont(playerid, InventoryTD[playerid][33], 4);
	PlayerTextDrawSetProportional(playerid, InventoryTD[playerid][33], 0);
	PlayerTextDrawSetShadow(playerid, InventoryTD[playerid][33], 0);
	PlayerTextDrawSetSelectable(playerid, InventoryTD[playerid][33], true);

	InventoryTD[playerid][34] = CreatePlayerTextDraw(playerid, 360.5270, 181.0581, "LD_SPAC:white"); // ?????
	PlayerTextDrawTextSize(playerid, InventoryTD[playerid][34], 27.5100, 21.8299);
	PlayerTextDrawAlignment(playerid, InventoryTD[playerid][34], 1);
	PlayerTextDrawColor(playerid, InventoryTD[playerid][34], 845713407);
	PlayerTextDrawBackgroundColor(playerid, InventoryTD[playerid][34], 255);
	PlayerTextDrawFont(playerid, InventoryTD[playerid][34], 4);
	PlayerTextDrawSetProportional(playerid, InventoryTD[playerid][34], 0);
	PlayerTextDrawSetShadow(playerid, InventoryTD[playerid][34], 0);
	PlayerTextDrawSetSelectable(playerid, InventoryTD[playerid][34], true);

	InventoryTD[playerid][35] = CreatePlayerTextDraw(playerid, 389.3287, 181.0581, "LD_SPAC:white"); // ?????
	PlayerTextDrawTextSize(playerid, InventoryTD[playerid][35], 36.1796, 21.4500);
	PlayerTextDrawAlignment(playerid, InventoryTD[playerid][35], 1);
	PlayerTextDrawColor(playerid, InventoryTD[playerid][35], 845713407);
	PlayerTextDrawBackgroundColor(playerid, InventoryTD[playerid][35], 255);
	PlayerTextDrawFont(playerid, InventoryTD[playerid][35], 4);
	PlayerTextDrawSetProportional(playerid, InventoryTD[playerid][35], 0);
	PlayerTextDrawSetShadow(playerid, InventoryTD[playerid][35], 0);
	PlayerTextDrawSetSelectable(playerid, InventoryTD[playerid][35], true);

	InventoryTD[playerid][36] = CreatePlayerTextDraw(playerid, 360.5856, 203.7415, "LD_SPAC:white"); // ?????
	PlayerTextDrawTextSize(playerid, InventoryTD[playerid][36], 32.6702, 23.8199);
	PlayerTextDrawAlignment(playerid, InventoryTD[playerid][36], 1);
	PlayerTextDrawColor(playerid, InventoryTD[playerid][36], 845713407);
	PlayerTextDrawBackgroundColor(playerid, InventoryTD[playerid][36], 255);
	PlayerTextDrawFont(playerid, InventoryTD[playerid][36], 4);
	PlayerTextDrawSetProportional(playerid, InventoryTD[playerid][36], 0);
	PlayerTextDrawSetShadow(playerid, InventoryTD[playerid][36], 0);
	PlayerTextDrawSetSelectable(playerid, InventoryTD[playerid][36], true);

	InventoryTD[playerid][37] = CreatePlayerTextDraw(playerid, 394.4877, 203.7415, "LD_SPAC:white"); // ?????
	PlayerTextDrawTextSize(playerid, InventoryTD[playerid][37], 31.1902, 23.8500);
	PlayerTextDrawAlignment(playerid, InventoryTD[playerid][37], 1);
	PlayerTextDrawColor(playerid, InventoryTD[playerid][37], 845713407);
 	PlayerTextDrawBackgroundColor(playerid, InventoryTD[playerid][37], 255);
	PlayerTextDrawFont(playerid, InventoryTD[playerid][37], 4);
	PlayerTextDrawSetProportional(playerid, InventoryTD[playerid][37], 0);
	PlayerTextDrawSetShadow(playerid, InventoryTD[playerid][37], 0);
	PlayerTextDrawSetSelectable(playerid, InventoryTD[playerid][37], true);

	InventoryTD[playerid][38] = CreatePlayerTextDraw(playerid, 333.6729, 135.7837, ""); // ?????
	PlayerTextDrawTextSize(playerid, InventoryTD[playerid][38], 90.0000, 74.1100);
	PlayerTextDrawAlignment(playerid, InventoryTD[playerid][38], 1);
	PlayerTextDrawColor(playerid, InventoryTD[playerid][38], -1);
	PlayerTextDrawBackgroundColor(playerid, InventoryTD[playerid][38], 0x00000000);
	PlayerTextDrawFont(playerid, InventoryTD[playerid][38], 5);
	PlayerTextDrawSetProportional(playerid, InventoryTD[playerid][38], 0);
	PlayerTextDrawSetShadow(playerid, InventoryTD[playerid][38], 0);
	PlayerTextDrawSetPreviewModel(playerid, InventoryTD[playerid][38], 356);
	PlayerTextDrawSetPreviewRot(playerid, InventoryTD[playerid][38], 0.0000, 360.0000, 195.0000, 1.8988);

	InventoryTD[playerid][39] = CreatePlayerTextDraw(playerid, 332.7846, 167.5330, ""); // ?????
	PlayerTextDrawTextSize(playerid, InventoryTD[playerid][39], 57.0000, 55.0000);
	PlayerTextDrawAlignment(playerid, InventoryTD[playerid][39], 1);
	PlayerTextDrawColor(playerid, InventoryTD[playerid][39], -1);
	PlayerTextDrawBackgroundColor(playerid, InventoryTD[playerid][39], 0x00000000);
	PlayerTextDrawFont(playerid, InventoryTD[playerid][39], 5);
	PlayerTextDrawSetProportional(playerid, InventoryTD[playerid][39], 0);
	PlayerTextDrawSetShadow(playerid, InventoryTD[playerid][39], 0);
	PlayerTextDrawSetPreviewModel(playerid, InventoryTD[playerid][39], 348);
	PlayerTextDrawSetPreviewRot(playerid, InventoryTD[playerid][39], 0.0000, 360.0000, 188.0000, 1.0000);

	InventoryTD[playerid][40] = CreatePlayerTextDraw(playerid, 373.0190, 176.0332, ""); // ?????
	PlayerTextDrawTextSize(playerid, InventoryTD[playerid][40], 45.0000, 42.0000);
	PlayerTextDrawAlignment(playerid, InventoryTD[playerid][40], 1);
	PlayerTextDrawColor(playerid, InventoryTD[playerid][40], -1);
	PlayerTextDrawBackgroundColor(playerid, InventoryTD[playerid][40], 0x00000000);
	PlayerTextDrawFont(playerid, InventoryTD[playerid][40], 5);
	PlayerTextDrawSetProportional(playerid, InventoryTD[playerid][40], 0);
	PlayerTextDrawSetShadow(playerid, InventoryTD[playerid][40], 0);
	PlayerTextDrawSetPreviewModel(playerid, InventoryTD[playerid][40], 353);
	PlayerTextDrawSetPreviewRot(playerid, InventoryTD[playerid][40], 0.0000, 360.0000, 188.0000, 1.0000);

	InventoryTD[playerid][47] = CreatePlayerTextDraw(playerid, 353.8818, 187.1999, ""); // ?????
	PlayerTextDrawTextSize(playerid, InventoryTD[playerid][47], 42.0000, 57.0000);
	PlayerTextDrawAlignment(playerid, InventoryTD[playerid][47], 1);
	PlayerTextDrawColor(playerid, InventoryTD[playerid][47], -1);
	PlayerTextDrawBackgroundColor(playerid, InventoryTD[playerid][47], 0x00000000);
	PlayerTextDrawFont(playerid, InventoryTD[playerid][47], 5);
	PlayerTextDrawSetProportional(playerid, InventoryTD[playerid][47], 0);
	PlayerTextDrawSetShadow(playerid, InventoryTD[playerid][47], 0);
	PlayerTextDrawSetPreviewModel(playerid, InventoryTD[playerid][47], 2768);
	PlayerTextDrawSetPreviewRot(playerid, InventoryTD[playerid][47], 0.0000, 360.0000, 118.0000, 1.0000);

	InventoryTD[playerid][41] = CreatePlayerTextDraw(playerid, 388.7525, 201.3999, ""); // ?????
	PlayerTextDrawTextSize(playerid, InventoryTD[playerid][41], 40.0000, 29.0000);
	PlayerTextDrawAlignment(playerid, InventoryTD[playerid][41], 1);
	PlayerTextDrawColor(playerid, InventoryTD[playerid][41], -1);
	PlayerTextDrawBackgroundColor(playerid, InventoryTD[playerid][41], 0x00000000);
	PlayerTextDrawFont(playerid, InventoryTD[playerid][41], 5);
	PlayerTextDrawSetProportional(playerid, InventoryTD[playerid][41], 0);
	PlayerTextDrawSetShadow(playerid, InventoryTD[playerid][41], 0);
	PlayerTextDrawSetPreviewModel(playerid, InventoryTD[playerid][41], 19563);
	PlayerTextDrawSetPreviewRot(playerid, InventoryTD[playerid][41], 0.0000, 360.0000, 0.0000, 1.0000);

	InventoryTD[playerid][42] = CreatePlayerTextDraw(playerid, 414.5581, 172.6000, "300"); // ?????
	PlayerTextDrawLetterSize(playerid, InventoryTD[playerid][42], 0.1247, 0.8008);
	PlayerTextDrawAlignment(playerid, InventoryTD[playerid][42], 1);
	PlayerTextDrawColor(playerid, InventoryTD[playerid][42], -1);
	PlayerTextDrawBackgroundColor(playerid, InventoryTD[playerid][42], 255);
	PlayerTextDrawFont(playerid, InventoryTD[playerid][42], 2);
	PlayerTextDrawSetProportional(playerid, InventoryTD[playerid][42], 1);
	PlayerTextDrawSetShadow(playerid, InventoryTD[playerid][42], 0);

	InventoryTD[playerid][43] = CreatePlayerTextDraw(playerid, 378.0133, 195.0500, "300"); // ?????
	PlayerTextDrawLetterSize(playerid, InventoryTD[playerid][43], 0.1247, 0.8008);
	PlayerTextDrawAlignment(playerid, InventoryTD[playerid][43], 1);
	PlayerTextDrawColor(playerid, InventoryTD[playerid][43], -1);
	PlayerTextDrawBackgroundColor(playerid, InventoryTD[playerid][43], 255);
	PlayerTextDrawFont(playerid, InventoryTD[playerid][43], 2);
	PlayerTextDrawSetProportional(playerid, InventoryTD[playerid][43], 1);
	PlayerTextDrawSetShadow(playerid, InventoryTD[playerid][43], 0);

	InventoryTD[playerid][44] = CreatePlayerTextDraw(playerid, 415.0213, 194.4002, "300"); // ?????
	PlayerTextDrawLetterSize(playerid, InventoryTD[playerid][44], 0.1247, 0.8008);
	PlayerTextDrawAlignment(playerid, InventoryTD[playerid][44], 1);
	PlayerTextDrawColor(playerid, InventoryTD[playerid][44], -1);
	PlayerTextDrawBackgroundColor(playerid, InventoryTD[playerid][44], 255);
	PlayerTextDrawFont(playerid, InventoryTD[playerid][44], 2);
	PlayerTextDrawSetProportional(playerid, InventoryTD[playerid][44], 1);
	PlayerTextDrawSetShadow(playerid, InventoryTD[playerid][44], 0);

	InventoryTD[playerid][45] = CreatePlayerTextDraw(playerid, 387.9523, 220.9169, "10"); // ?????
	PlayerTextDrawLetterSize(playerid, InventoryTD[playerid][45], 0.1247, 0.8008);
	PlayerTextDrawAlignment(playerid, InventoryTD[playerid][45], 1);
	PlayerTextDrawColor(playerid, InventoryTD[playerid][45], -1);
	PlayerTextDrawBackgroundColor(playerid, InventoryTD[playerid][45], 255);
	PlayerTextDrawFont(playerid, InventoryTD[playerid][45], 2);
	PlayerTextDrawSetProportional(playerid, InventoryTD[playerid][45], 1);
	PlayerTextDrawSetShadow(playerid, InventoryTD[playerid][45], 0);

	InventoryTD[playerid][46] = CreatePlayerTextDraw(playerid, 419.9323, 220.4335, "10"); // ?????
	PlayerTextDrawLetterSize(playerid, InventoryTD[playerid][46], 0.1247, 0.8008);
	PlayerTextDrawAlignment(playerid, InventoryTD[playerid][46], 1);
	PlayerTextDrawColor(playerid, InventoryTD[playerid][46], -1);
	PlayerTextDrawBackgroundColor(playerid, InventoryTD[playerid][46], 255);
	PlayerTextDrawFont(playerid, InventoryTD[playerid][46], 2);
	PlayerTextDrawSetProportional(playerid, InventoryTD[playerid][46], 1);
	PlayerTextDrawSetShadow(playerid, InventoryTD[playerid][46], 0);

