	InventoryFrame[playerid][0] = CreatePlayerTextDraw(playerid, 441.0000, 147.5625, ""); // ?????
	PlayerTextDrawTextSize(playerid, InventoryFrame[playerid][0], 33.0000, 31.0000);
	PlayerTextDrawAlignment(playerid, InventoryFrame[playerid][0], 1);
	PlayerTextDrawColor(playerid, InventoryFrame[playerid][0], -1);
	PlayerTextDrawBackgroundColor(playerid, InventoryFrame[playerid][0], 626095103);
	PlayerTextDrawFont(playerid, InventoryFrame[playerid][0], 5);
	PlayerTextDrawSetProportional(playerid, InventoryFrame[playerid][0], 0);
	PlayerTextDrawSetShadow(playerid, InventoryFrame[playerid][0], 0);
	PlayerTextDrawSetSelectable(playerid, InventoryFrame[playerid][0], true);
	PlayerTextDrawSetPreviewModel(playerid, InventoryFrame[playerid][0], 19475);
	PlayerTextDrawSetPreviewRot(playerid, InventoryFrame[playerid][0], 0.0000, 0.0000, 0.0000, 1.0000);

	InventoryFrame[playerid][1] = CreatePlayerTextDraw(playerid, 475.5021, 147.5625, ""); // ?????
	PlayerTextDrawTextSize(playerid, InventoryFrame[playerid][1], 33.0000, 31.0000);
	PlayerTextDrawAlignment(playerid, InventoryFrame[playerid][1], 1);
	PlayerTextDrawColor(playerid, InventoryFrame[playerid][1], -1);
	PlayerTextDrawBackgroundColor(playerid, InventoryFrame[playerid][1], 626095103);
	PlayerTextDrawFont(playerid, InventoryFrame[playerid][1], 5);
	PlayerTextDrawSetProportional(playerid, InventoryFrame[playerid][1], 0);
	PlayerTextDrawSetShadow(playerid, InventoryFrame[playerid][1], 0);
	PlayerTextDrawSetSelectable(playerid, InventoryFrame[playerid][1], true);
	PlayerTextDrawSetPreviewModel(playerid, InventoryFrame[playerid][1], 19475);
	PlayerTextDrawSetPreviewRot(playerid, InventoryFrame[playerid][1], 0.0000, 0.0000, 0.0000, 1.0000);

	InventoryFrame[playerid][2] = CreatePlayerTextDraw(playerid, 509.9042, 147.5625, ""); // ?????
	PlayerTextDrawTextSize(playerid, InventoryFrame[playerid][2], 33.0000, 31.0000);
	PlayerTextDrawAlignment(playerid, InventoryFrame[playerid][2], 1);
	PlayerTextDrawColor(playerid, InventoryFrame[playerid][2], -1);
	PlayerTextDrawBackgroundColor(playerid, InventoryFrame[playerid][2], 626095103);
	PlayerTextDrawFont(playerid, InventoryFrame[playerid][2], 5);
	PlayerTextDrawSetProportional(playerid, InventoryFrame[playerid][2], 0);
	PlayerTextDrawSetShadow(playerid, InventoryFrame[playerid][2], 0);
	PlayerTextDrawSetSelectable(playerid, InventoryFrame[playerid][2], true);
	PlayerTextDrawSetPreviewModel(playerid, InventoryFrame[playerid][2], 19475);
	PlayerTextDrawSetPreviewRot(playerid, InventoryFrame[playerid][2], 0.0000, 0.0000, 0.0000, 1.0000);

	InventoryFrame[playerid][3] = CreatePlayerTextDraw(playerid, 544.1964, 147.5625, ""); // ?????
	PlayerTextDrawTextSize(playerid, InventoryFrame[playerid][3], 33.0000, 31.0000);
	PlayerTextDrawAlignment(playerid, InventoryFrame[playerid][3], 1);
	PlayerTextDrawColor(playerid, InventoryFrame[playerid][3], -1);
	PlayerTextDrawBackgroundColor(playerid, InventoryFrame[playerid][3], 626095103);
	PlayerTextDrawFont(playerid, InventoryFrame[playerid][3], 5);
	PlayerTextDrawSetProportional(playerid, InventoryFrame[playerid][3], 0);
	PlayerTextDrawSetShadow(playerid, InventoryFrame[playerid][3], 0);
	PlayerTextDrawSetSelectable(playerid, InventoryFrame[playerid][3], true);
	PlayerTextDrawSetPreviewModel(playerid, InventoryFrame[playerid][3], 19475);
	PlayerTextDrawSetPreviewRot(playerid, InventoryFrame[playerid][3], 0.0000, 0.0000, 0.0000, 1.0000);

	InventoryFrame[playerid][4] = CreatePlayerTextDraw(playerid, 578.6879, 147.5625, ""); // ?????
	PlayerTextDrawTextSize(playerid, InventoryFrame[playerid][4], 33.0000, 31.0000);
	PlayerTextDrawAlignment(playerid, InventoryFrame[playerid][4], 1);
	PlayerTextDrawColor(playerid, InventoryFrame[playerid][4], -1);
	PlayerTextDrawBackgroundColor(playerid, InventoryFrame[playerid][4], 626095103);
	PlayerTextDrawFont(playerid, InventoryFrame[playerid][4], 5);
	PlayerTextDrawSetProportional(playerid, InventoryFrame[playerid][4], 0);
	PlayerTextDrawSetShadow(playerid, InventoryFrame[playerid][4], 0);
	PlayerTextDrawSetSelectable(playerid, InventoryFrame[playerid][4], true);
	PlayerTextDrawSetPreviewModel(playerid, InventoryFrame[playerid][4], 19475);
	PlayerTextDrawSetPreviewRot(playerid, InventoryFrame[playerid][4], 0.0000, 0.0000, 0.0000, 1.0000);

	InventoryFrame[playerid][5] = CreatePlayerTextDraw(playerid, 441.0000, 180.2644, ""); // ?????
	PlayerTextDrawTextSize(playerid, InventoryFrame[playerid][5], 33.0000, 31.0000);
	PlayerTextDrawAlignment(playerid, InventoryFrame[playerid][5], 1);
	PlayerTextDrawColor(playerid, InventoryFrame[playerid][5], -1);
	PlayerTextDrawBackgroundColor(playerid, InventoryFrame[playerid][5], 626095103);
	PlayerTextDrawFont(playerid, InventoryFrame[playerid][5], 5);
	PlayerTextDrawSetProportional(playerid, InventoryFrame[playerid][5], 0);
	PlayerTextDrawSetShadow(playerid, InventoryFrame[playerid][5], 0);
	PlayerTextDrawSetSelectable(playerid, InventoryFrame[playerid][5], true);
	PlayerTextDrawSetPreviewModel(playerid, InventoryFrame[playerid][5], 19475);
	PlayerTextDrawSetPreviewRot(playerid, InventoryFrame[playerid][5], 0.0000, 0.0000, 0.0000, 1.0000);

	InventoryFrame[playerid][6] = CreatePlayerTextDraw(playerid, 475.5021, 180.2644, ""); // ?????
	PlayerTextDrawTextSize(playerid, InventoryFrame[playerid][6], 33.0000, 31.0000);
	PlayerTextDrawAlignment(playerid, InventoryFrame[playerid][6], 1);
	PlayerTextDrawColor(playerid, InventoryFrame[playerid][6], -1);
	PlayerTextDrawBackgroundColor(playerid, InventoryFrame[playerid][6], 626095103);
	PlayerTextDrawFont(playerid, InventoryFrame[playerid][6], 5);
	PlayerTextDrawSetProportional(playerid, InventoryFrame[playerid][6], 0);
	PlayerTextDrawSetShadow(playerid, InventoryFrame[playerid][6], 0);
	PlayerTextDrawSetSelectable(playerid, InventoryFrame[playerid][6], true);
	PlayerTextDrawSetPreviewModel(playerid, InventoryFrame[playerid][6], 19475);
	PlayerTextDrawSetPreviewRot(playerid, InventoryFrame[playerid][6], 0.0000, 0.0000, 0.0000, 1.0000);

	InventoryFrame[playerid][7] = CreatePlayerTextDraw(playerid, 510.0042, 180.2644, ""); // ?????
	PlayerTextDrawTextSize(playerid, InventoryFrame[playerid][7], 33.0000, 31.0000);
	PlayerTextDrawAlignment(playerid, InventoryFrame[playerid][7], 1);
	PlayerTextDrawColor(playerid, InventoryFrame[playerid][7], -1);
	PlayerTextDrawBackgroundColor(playerid, InventoryFrame[playerid][7], 626095103);
	PlayerTextDrawFont(playerid, InventoryFrame[playerid][7], 5);
	PlayerTextDrawSetProportional(playerid, InventoryFrame[playerid][7], 0);
	PlayerTextDrawSetShadow(playerid, InventoryFrame[playerid][7], 0);
	PlayerTextDrawSetSelectable(playerid, InventoryFrame[playerid][7], true);
	PlayerTextDrawSetPreviewModel(playerid, InventoryFrame[playerid][7], 19475);
	PlayerTextDrawSetPreviewRot(playerid, InventoryFrame[playerid][7], 0.0000, 0.0000, 0.0000, 1.0000);

	InventoryFrame[playerid][8] = CreatePlayerTextDraw(playerid, 544.3964, 180.2644, ""); // ?????
	PlayerTextDrawTextSize(playerid, InventoryFrame[playerid][8], 33.0000, 31.0000);
	PlayerTextDrawAlignment(playerid, InventoryFrame[playerid][8], 1);
	PlayerTextDrawColor(playerid, InventoryFrame[playerid][8], -1);
	PlayerTextDrawBackgroundColor(playerid, InventoryFrame[playerid][8], 626095103);
	PlayerTextDrawFont(playerid, InventoryFrame[playerid][8], 5);
	PlayerTextDrawSetProportional(playerid, InventoryFrame[playerid][8], 0);
	PlayerTextDrawSetShadow(playerid, InventoryFrame[playerid][8], 0);
	PlayerTextDrawSetSelectable(playerid, InventoryFrame[playerid][8], true);
	PlayerTextDrawSetPreviewModel(playerid, InventoryFrame[playerid][8], 19475);
	PlayerTextDrawSetPreviewRot(playerid, InventoryFrame[playerid][8], 0.0000, 0.0000, 0.0000, 1.0000);

	InventoryFrame[playerid][9] = CreatePlayerTextDraw(playerid, 578.6879, 180.2644, ""); // ?????
	PlayerTextDrawTextSize(playerid, InventoryFrame[playerid][9], 33.0000, 31.0000);
	PlayerTextDrawAlignment(playerid, InventoryFrame[playerid][9], 1);
	PlayerTextDrawColor(playerid, InventoryFrame[playerid][9], -1);
	PlayerTextDrawBackgroundColor(playerid, InventoryFrame[playerid][9], 626095103);
	PlayerTextDrawFont(playerid, InventoryFrame[playerid][9], 5);
	PlayerTextDrawSetProportional(playerid, InventoryFrame[playerid][9], 0);
	PlayerTextDrawSetShadow(playerid, InventoryFrame[playerid][9], 0);
	PlayerTextDrawSetSelectable(playerid, InventoryFrame[playerid][9], true);
	PlayerTextDrawSetPreviewModel(playerid, InventoryFrame[playerid][9], 19475);
	PlayerTextDrawSetPreviewRot(playerid, InventoryFrame[playerid][9], 0.0000, 0.0000, 0.0000, 1.0000);

	InventoryFrame[playerid][10] = CreatePlayerTextDraw(playerid, 441.0000, 213.0664, ""); // ?????
	PlayerTextDrawTextSize(playerid, InventoryFrame[playerid][10], 33.0000, 31.0000);
	PlayerTextDrawAlignment(playerid, InventoryFrame[playerid][10], 1);
	PlayerTextDrawColor(playerid, InventoryFrame[playerid][10], -1);
	PlayerTextDrawBackgroundColor(playerid, InventoryFrame[playerid][10], 626095103);
	PlayerTextDrawFont(playerid, InventoryFrame[playerid][10], 5);
	PlayerTextDrawSetProportional(playerid, InventoryFrame[playerid][10], 0);
	PlayerTextDrawSetShadow(playerid, InventoryFrame[playerid][10], 0);
	PlayerTextDrawSetSelectable(playerid, InventoryFrame[playerid][10], true);
	PlayerTextDrawSetPreviewModel(playerid, InventoryFrame[playerid][10], 19475);
	PlayerTextDrawSetPreviewRot(playerid, InventoryFrame[playerid][10], 0.0000, 0.0000, 0.0000, 1.0000);

	InventoryFrame[playerid][11] = CreatePlayerTextDraw(playerid, 475.6021, 213.0664, ""); // ?????
	PlayerTextDrawTextSize(playerid, InventoryFrame[playerid][11], 33.0000, 31.0000);
	PlayerTextDrawAlignment(playerid, InventoryFrame[playerid][11], 1);
	PlayerTextDrawColor(playerid, InventoryFrame[playerid][11], -1);
	PlayerTextDrawBackgroundColor(playerid, InventoryFrame[playerid][11], 626095103);
	PlayerTextDrawFont(playerid, InventoryFrame[playerid][11], 5);
	PlayerTextDrawSetProportional(playerid, InventoryFrame[playerid][11], 0);
	PlayerTextDrawSetShadow(playerid, InventoryFrame[playerid][11], 0);
	PlayerTextDrawSetSelectable(playerid, InventoryFrame[playerid][11], true);
	PlayerTextDrawSetPreviewModel(playerid, InventoryFrame[playerid][11], 19475);
	PlayerTextDrawSetPreviewRot(playerid, InventoryFrame[playerid][11], 0.0000, 0.0000, 0.0000, 1.0000);

	InventoryFrame[playerid][12] = CreatePlayerTextDraw(playerid, 510.1040, 213.0664, ""); // ?????
	PlayerTextDrawTextSize(playerid, InventoryFrame[playerid][12], 33.0000, 31.0000);
	PlayerTextDrawAlignment(playerid, InventoryFrame[playerid][12], 1);
	PlayerTextDrawColor(playerid, InventoryFrame[playerid][12], -1);
	PlayerTextDrawBackgroundColor(playerid, InventoryFrame[playerid][12], 626095103);
	PlayerTextDrawFont(playerid, InventoryFrame[playerid][12], 5);
	PlayerTextDrawSetProportional(playerid, InventoryFrame[playerid][12], 0);
	PlayerTextDrawSetShadow(playerid, InventoryFrame[playerid][12], 0);
	PlayerTextDrawSetSelectable(playerid, InventoryFrame[playerid][12], true);
	PlayerTextDrawSetPreviewModel(playerid, InventoryFrame[playerid][12], 19475);
	PlayerTextDrawSetPreviewRot(playerid, InventoryFrame[playerid][12], 0.0000, 0.0000, 0.0000, 1.0000);

	InventoryFrame[playerid][13] = CreatePlayerTextDraw(playerid, 544.4962, 213.0664, ""); // ?????
	PlayerTextDrawTextSize(playerid, InventoryFrame[playerid][13], 33.0000, 31.0000);
	PlayerTextDrawAlignment(playerid, InventoryFrame[playerid][13], 1);
	PlayerTextDrawColor(playerid, InventoryFrame[playerid][13], -1);
	PlayerTextDrawBackgroundColor(playerid, InventoryFrame[playerid][13], 626095103);
	PlayerTextDrawFont(playerid, InventoryFrame[playerid][13], 5);
	PlayerTextDrawSetProportional(playerid, InventoryFrame[playerid][13], 0);
	PlayerTextDrawSetShadow(playerid, InventoryFrame[playerid][13], 0);
	PlayerTextDrawSetSelectable(playerid, InventoryFrame[playerid][13], true);
	PlayerTextDrawSetPreviewModel(playerid, InventoryFrame[playerid][13], 19475);
	PlayerTextDrawSetPreviewRot(playerid, InventoryFrame[playerid][13], 0.0000, 0.0000, 0.0000, 1.0000);

	InventoryFrame[playerid][14] = CreatePlayerTextDraw(playerid, 578.7880, 213.0664, ""); // ?????
	PlayerTextDrawTextSize(playerid, InventoryFrame[playerid][14], 33.0000, 31.0000);
	PlayerTextDrawAlignment(playerid, InventoryFrame[playerid][14], 1);
	PlayerTextDrawColor(playerid, InventoryFrame[playerid][14], -1);
	PlayerTextDrawBackgroundColor(playerid, InventoryFrame[playerid][14], 626095103);
	PlayerTextDrawFont(playerid, InventoryFrame[playerid][14], 5);
	PlayerTextDrawSetProportional(playerid, InventoryFrame[playerid][14], 0);
	PlayerTextDrawSetShadow(playerid, InventoryFrame[playerid][14], 0);
	PlayerTextDrawSetSelectable(playerid, InventoryFrame[playerid][14], true);
	PlayerTextDrawSetPreviewModel(playerid, InventoryFrame[playerid][14], 19475);
	PlayerTextDrawSetPreviewRot(playerid, InventoryFrame[playerid][14], 0.0000, 0.0000, 0.0000, 1.0000);

	InventoryFrame[playerid][15] = CreatePlayerTextDraw(playerid, 441.0000, 245.6683, ""); // ?????
	PlayerTextDrawTextSize(playerid, InventoryFrame[playerid][15], 33.0000, 31.0000);
	PlayerTextDrawAlignment(playerid, InventoryFrame[playerid][15], 1);
	PlayerTextDrawColor(playerid, InventoryFrame[playerid][15], -1);
	PlayerTextDrawBackgroundColor(playerid, InventoryFrame[playerid][15], 626095103);
	PlayerTextDrawFont(playerid, InventoryFrame[playerid][15], 5);
	PlayerTextDrawSetProportional(playerid, InventoryFrame[playerid][15], 0);
	PlayerTextDrawSetShadow(playerid, InventoryFrame[playerid][15], 0);
	PlayerTextDrawSetSelectable(playerid, InventoryFrame[playerid][15], true);
	PlayerTextDrawSetPreviewModel(playerid, InventoryFrame[playerid][15], 19475);
	PlayerTextDrawSetPreviewRot(playerid, InventoryFrame[playerid][15], 0.0000, 0.0000, 0.0000, 1.0000);

	InventoryFrame[playerid][16] = CreatePlayerTextDraw(playerid, 475.6021, 245.6683, ""); // ?????
	PlayerTextDrawTextSize(playerid, InventoryFrame[playerid][16], 33.0000, 31.0000);
	PlayerTextDrawAlignment(playerid, InventoryFrame[playerid][16], 1);
	PlayerTextDrawColor(playerid, InventoryFrame[playerid][16], -1);
	PlayerTextDrawBackgroundColor(playerid, InventoryFrame[playerid][16], 626095103);
	PlayerTextDrawFont(playerid, InventoryFrame[playerid][16], 5);
	PlayerTextDrawSetProportional(playerid, InventoryFrame[playerid][16], 0);
	PlayerTextDrawSetShadow(playerid, InventoryFrame[playerid][16], 0);
	PlayerTextDrawSetSelectable(playerid, InventoryFrame[playerid][16], true);
	PlayerTextDrawSetPreviewModel(playerid, InventoryFrame[playerid][16], 19475);
	PlayerTextDrawSetPreviewRot(playerid, InventoryFrame[playerid][16], 0.0000, 0.0000, 0.0000, 1.0000);

	InventoryFrame[playerid][17] = CreatePlayerTextDraw(playerid, 510.1040, 245.6683, ""); // ?????
	PlayerTextDrawTextSize(playerid, InventoryFrame[playerid][17], 33.0000, 31.0000);
	PlayerTextDrawAlignment(playerid, InventoryFrame[playerid][17], 1);
	PlayerTextDrawColor(playerid, InventoryFrame[playerid][17], -1);
	PlayerTextDrawBackgroundColor(playerid, InventoryFrame[playerid][17], 626095103);
	PlayerTextDrawFont(playerid, InventoryFrame[playerid][17], 5);
	PlayerTextDrawSetProportional(playerid, InventoryFrame[playerid][17], 0);
	PlayerTextDrawSetShadow(playerid, InventoryFrame[playerid][17], 0);
	PlayerTextDrawSetSelectable(playerid, InventoryFrame[playerid][17], true);
	PlayerTextDrawSetPreviewModel(playerid, InventoryFrame[playerid][17], 19475);
	PlayerTextDrawSetPreviewRot(playerid, InventoryFrame[playerid][17], 0.0000, 0.0000, 0.0000, 1.0000);

	InventoryFrame[playerid][18] = CreatePlayerTextDraw(playerid, 544.5963, 245.6683, ""); // ?????
	PlayerTextDrawTextSize(playerid, InventoryFrame[playerid][18], 33.0000, 31.0000);
	PlayerTextDrawAlignment(playerid, InventoryFrame[playerid][18], 1);
	PlayerTextDrawColor(playerid, InventoryFrame[playerid][18], -1);
	PlayerTextDrawBackgroundColor(playerid, InventoryFrame[playerid][18], 626095103);
	PlayerTextDrawFont(playerid, InventoryFrame[playerid][18], 5);
	PlayerTextDrawSetProportional(playerid, InventoryFrame[playerid][18], 0);
	PlayerTextDrawSetShadow(playerid, InventoryFrame[playerid][18], 0);
	PlayerTextDrawSetSelectable(playerid, InventoryFrame[playerid][18], true);
	PlayerTextDrawSetPreviewModel(playerid, InventoryFrame[playerid][18], 19475);
	PlayerTextDrawSetPreviewRot(playerid, InventoryFrame[playerid][18], 0.0000, 0.0000, 0.0000, 1.0000);

	InventoryFrame[playerid][19] = CreatePlayerTextDraw(playerid, 578.7880, 245.6683, ""); // ?????
	PlayerTextDrawTextSize(playerid, InventoryFrame[playerid][19], 33.0000, 31.0000);
	PlayerTextDrawAlignment(playerid, InventoryFrame[playerid][19], 1);
	PlayerTextDrawColor(playerid, InventoryFrame[playerid][19], -1);
	PlayerTextDrawBackgroundColor(playerid, InventoryFrame[playerid][19], 626095103);
	PlayerTextDrawFont(playerid, InventoryFrame[playerid][19], 5);
	PlayerTextDrawSetProportional(playerid, InventoryFrame[playerid][19], 0);
	PlayerTextDrawSetShadow(playerid, InventoryFrame[playerid][19], 0);
	PlayerTextDrawSetSelectable(playerid, InventoryFrame[playerid][19], true);
	PlayerTextDrawSetPreviewModel(playerid, InventoryFrame[playerid][19], 19475);
	PlayerTextDrawSetPreviewRot(playerid, InventoryFrame[playerid][19], 0.0000, 0.0000, 0.0000, 1.0000);

	InventoryFrame[playerid][20] = CreatePlayerTextDraw(playerid, 441.0000, 278.6701, ""); // ?????
	PlayerTextDrawTextSize(playerid, InventoryFrame[playerid][20], 33.0000, 31.0000);
	PlayerTextDrawAlignment(playerid, InventoryFrame[playerid][20], 1);
	PlayerTextDrawColor(playerid, InventoryFrame[playerid][20], -1);
	PlayerTextDrawBackgroundColor(playerid, InventoryFrame[playerid][20], 626095103);
	PlayerTextDrawFont(playerid, InventoryFrame[playerid][20], 5);
	PlayerTextDrawSetProportional(playerid, InventoryFrame[playerid][20], 0);
	PlayerTextDrawSetShadow(playerid, InventoryFrame[playerid][20], 0);
	PlayerTextDrawSetSelectable(playerid, InventoryFrame[playerid][20], true);
	PlayerTextDrawSetPreviewModel(playerid, InventoryFrame[playerid][20], 19475);
	PlayerTextDrawSetPreviewRot(playerid, InventoryFrame[playerid][20], 0.0000, 0.0000, 0.0000, 1.0000);

	InventoryFrame[playerid][21] = CreatePlayerTextDraw(playerid, 475.6021, 278.6701, ""); // ?????
	PlayerTextDrawTextSize(playerid, InventoryFrame[playerid][21], 33.0000, 31.0000);
	PlayerTextDrawAlignment(playerid, InventoryFrame[playerid][21], 1);
	PlayerTextDrawColor(playerid, InventoryFrame[playerid][21], -1);
	PlayerTextDrawBackgroundColor(playerid, InventoryFrame[playerid][21], 626095103);
	PlayerTextDrawFont(playerid, InventoryFrame[playerid][21], 5);
	PlayerTextDrawSetProportional(playerid, InventoryFrame[playerid][21], 0);
	PlayerTextDrawSetShadow(playerid, InventoryFrame[playerid][21], 0);
	PlayerTextDrawSetSelectable(playerid, InventoryFrame[playerid][21], true);
	PlayerTextDrawSetPreviewModel(playerid, InventoryFrame[playerid][21], 19475);
	PlayerTextDrawSetPreviewRot(playerid, InventoryFrame[playerid][21], 0.0000, 0.0000, 0.0000, 1.0000);

	InventoryFrame[playerid][22] = CreatePlayerTextDraw(playerid, 510.2041, 278.6701, ""); // ?????
	PlayerTextDrawTextSize(playerid, InventoryFrame[playerid][22], 33.0000, 31.0000);
	PlayerTextDrawAlignment(playerid, InventoryFrame[playerid][22], 1);
	PlayerTextDrawColor(playerid, InventoryFrame[playerid][22], -1);
	PlayerTextDrawBackgroundColor(playerid, InventoryFrame[playerid][22], 626095103);
	PlayerTextDrawFont(playerid, InventoryFrame[playerid][22], 5);
	PlayerTextDrawSetProportional(playerid, InventoryFrame[playerid][22], 0);
	PlayerTextDrawSetShadow(playerid, InventoryFrame[playerid][22], 0);
	PlayerTextDrawSetSelectable(playerid, InventoryFrame[playerid][22], true);
	PlayerTextDrawSetPreviewModel(playerid, InventoryFrame[playerid][22], 19475);
	PlayerTextDrawSetPreviewRot(playerid, InventoryFrame[playerid][22], 0.0000, 0.0000, 0.0000, 1.0000);

	InventoryFrame[playerid][23] = CreatePlayerTextDraw(playerid, 544.7963, 278.6701, ""); // ?????
	PlayerTextDrawTextSize(playerid, InventoryFrame[playerid][23], 33.0000, 31.0000);
	PlayerTextDrawAlignment(playerid, InventoryFrame[playerid][23], 1);
	PlayerTextDrawColor(playerid, InventoryFrame[playerid][23], -1);
	PlayerTextDrawBackgroundColor(playerid, InventoryFrame[playerid][23], 626095103);
	PlayerTextDrawFont(playerid, InventoryFrame[playerid][23], 5);
	PlayerTextDrawSetProportional(playerid, InventoryFrame[playerid][23], 0);
	PlayerTextDrawSetShadow(playerid, InventoryFrame[playerid][23], 0);
	PlayerTextDrawSetSelectable(playerid, InventoryFrame[playerid][23], true);
	PlayerTextDrawSetPreviewModel(playerid, InventoryFrame[playerid][23], 19475);
	PlayerTextDrawSetPreviewRot(playerid, InventoryFrame[playerid][23], 0.0000, 0.0000, 0.0000, 1.0000);

	InventoryFrame[playerid][24] = CreatePlayerTextDraw(playerid, 578.8880, 278.6701, ""); // ?????
	PlayerTextDrawTextSize(playerid, InventoryFrame[playerid][24], 33.0000, 31.0000);
	PlayerTextDrawAlignment(playerid, InventoryFrame[playerid][24], 1);
	PlayerTextDrawColor(playerid, InventoryFrame[playerid][24], -1);
	PlayerTextDrawBackgroundColor(playerid, InventoryFrame[playerid][24], 626095103);
	PlayerTextDrawFont(playerid, InventoryFrame[playerid][24], 5);
	PlayerTextDrawSetProportional(playerid, InventoryFrame[playerid][24], 0);
	PlayerTextDrawSetShadow(playerid, InventoryFrame[playerid][24], 0);
	PlayerTextDrawSetSelectable(playerid, InventoryFrame[playerid][24], true);
	PlayerTextDrawSetPreviewModel(playerid, InventoryFrame[playerid][24], 19475);
	PlayerTextDrawSetPreviewRot(playerid, InventoryFrame[playerid][24], 0.0000, 0.0000, 0.0000, 1.0000);
