GunWFood_PTD[playerid][0] = CreatePlayerTextDraw(playerid, 360.5270, 158.9568, "LD_SPAC:white"); // ?????
PlayerTextDrawTextSize(playerid, GunWFood_PTD[playerid][0], 65.0000, 21.0000);
PlayerTextDrawAlignment(playerid, GunWFood_PTD[playerid][0], 1);
PlayerTextDrawColor(playerid, GunWFood_PTD[playerid][0], 845713407);
PlayerTextDrawBackgroundColor(playerid, GunWFood_PTD[playerid][0], 255);
PlayerTextDrawFont(playerid, GunWFood_PTD[playerid][0], 4);
PlayerTextDrawSetProportional(playerid, GunWFood_PTD[playerid][0], 0);
PlayerTextDrawSetShadow(playerid, GunWFood_PTD[playerid][0], 0);
PlayerTextDrawSetSelectable(playerid, GunWFood_PTD[playerid][0], true);

GunWFood_PTD[playerid][1] = CreatePlayerTextDraw(playerid, 360.5270, 181.0581, "LD_SPAC:white"); // ?????
PlayerTextDrawTextSize(playerid, GunWFood_PTD[playerid][1], 27.5100, 21.8299);
PlayerTextDrawAlignment(playerid, GunWFood_PTD[playerid][1], 1);
PlayerTextDrawColor(playerid, GunWFood_PTD[playerid][1], 845713407);
PlayerTextDrawBackgroundColor(playerid, GunWFood_PTD[playerid][1], 255);
PlayerTextDrawFont(playerid, GunWFood_PTD[playerid][1], 4);
PlayerTextDrawSetProportional(playerid, GunWFood_PTD[playerid][1], 0);
PlayerTextDrawSetShadow(playerid, GunWFood_PTD[playerid][1], 0);
PlayerTextDrawSetSelectable(playerid, GunWFood_PTD[playerid][1], true);

GunWFood_PTD[playerid][2] = CreatePlayerTextDraw(playerid, 389.3287, 181.0581, "LD_SPAC:white"); // ?????
PlayerTextDrawTextSize(playerid, GunWFood_PTD[playerid][2], 36.1797, 21.4500);
PlayerTextDrawAlignment(playerid, GunWFood_PTD[playerid][2], 1);
PlayerTextDrawColor(playerid, GunWFood_PTD[playerid][2], 845713407);
PlayerTextDrawBackgroundColor(playerid, GunWFood_PTD[playerid][2], 255);
PlayerTextDrawFont(playerid, GunWFood_PTD[playerid][2], 4);
PlayerTextDrawSetProportional(playerid, GunWFood_PTD[playerid][2], 0);
PlayerTextDrawSetShadow(playerid, GunWFood_PTD[playerid][2], 0);
PlayerTextDrawSetSelectable(playerid, GunWFood_PTD[playerid][2], true);

GunWFood_PTD[playerid][3] = CreatePlayerTextDraw(playerid, 360.5857, 203.7415, "LD_SPAC:white"); // ?????
PlayerTextDrawTextSize(playerid, GunWFood_PTD[playerid][3], 32.6702, 23.8199);
PlayerTextDrawAlignment(playerid, GunWFood_PTD[playerid][3], 1);
PlayerTextDrawColor(playerid, GunWFood_PTD[playerid][3], 845713407);
PlayerTextDrawBackgroundColor(playerid, GunWFood_PTD[playerid][3], 255);
PlayerTextDrawFont(playerid, GunWFood_PTD[playerid][3], 4);
PlayerTextDrawSetProportional(playerid, GunWFood_PTD[playerid][3], 0);
PlayerTextDrawSetShadow(playerid, GunWFood_PTD[playerid][3], 0);
PlayerTextDrawSetSelectable(playerid, GunWFood_PTD[playerid][3], true);

GunWFood_PTD[playerid][4] = CreatePlayerTextDraw(playerid, 394.4877, 203.7415, "LD_SPAC:white"); // ?????
PlayerTextDrawTextSize(playerid, GunWFood_PTD[playerid][4], 31.1903, 23.8500);
PlayerTextDrawAlignment(playerid, GunWFood_PTD[playerid][4], 1);
PlayerTextDrawColor(playerid, GunWFood_PTD[playerid][4], 845713407);
PlayerTextDrawBackgroundColor(playerid, GunWFood_PTD[playerid][4], 255);
PlayerTextDrawFont(playerid, GunWFood_PTD[playerid][4], 4);
PlayerTextDrawSetProportional(playerid, GunWFood_PTD[playerid][4], 0);
PlayerTextDrawSetShadow(playerid, GunWFood_PTD[playerid][4], 0);
PlayerTextDrawSetSelectable(playerid, GunWFood_PTD[playerid][4], true);

GunWFood_PTD[playerid][5] = CreatePlayerTextDraw(playerid, 414.5582, 172.6000, "300"); // ?????
PlayerTextDrawLetterSize(playerid, GunWFood_PTD[playerid][5], 0.1248, 0.8008);
PlayerTextDrawAlignment(playerid, GunWFood_PTD[playerid][5], 1);
PlayerTextDrawColor(playerid, GunWFood_PTD[playerid][5], -1);
PlayerTextDrawBackgroundColor(playerid, GunWFood_PTD[playerid][5], 255);
PlayerTextDrawFont(playerid, GunWFood_PTD[playerid][5], 2);
PlayerTextDrawSetProportional(playerid, GunWFood_PTD[playerid][5], 1);
PlayerTextDrawSetShadow(playerid, GunWFood_PTD[playerid][5], 0);

GunWFood_PTD[playerid][6] = CreatePlayerTextDraw(playerid, 378.0133, 195.0500, "300"); // ?????
PlayerTextDrawLetterSize(playerid, GunWFood_PTD[playerid][6], 0.1248, 0.8008);
PlayerTextDrawAlignment(playerid, GunWFood_PTD[playerid][6], 1);
PlayerTextDrawColor(playerid, GunWFood_PTD[playerid][6], -1);
PlayerTextDrawBackgroundColor(playerid, GunWFood_PTD[playerid][6], 255);
PlayerTextDrawFont(playerid, GunWFood_PTD[playerid][6], 2);
PlayerTextDrawSetProportional(playerid, GunWFood_PTD[playerid][6], 1);
PlayerTextDrawSetShadow(playerid, GunWFood_PTD[playerid][6], 0);

GunWFood_PTD[playerid][7] = CreatePlayerTextDraw(playerid, 415.0213, 194.4002, "300"); // ?????
PlayerTextDrawLetterSize(playerid, GunWFood_PTD[playerid][7], 0.1248, 0.8008);
PlayerTextDrawAlignment(playerid, GunWFood_PTD[playerid][7], 1);
PlayerTextDrawColor(playerid, GunWFood_PTD[playerid][7], -1);
PlayerTextDrawBackgroundColor(playerid, GunWFood_PTD[playerid][7], 255);
PlayerTextDrawFont(playerid, GunWFood_PTD[playerid][7], 2);
PlayerTextDrawSetProportional(playerid, GunWFood_PTD[playerid][7], 1);
PlayerTextDrawSetShadow(playerid, GunWFood_PTD[playerid][7], 0);

GunWFood_PTD[playerid][8] = CreatePlayerTextDraw(playerid, 387.9523, 220.9169, "10"); // ?????
PlayerTextDrawLetterSize(playerid, GunWFood_PTD[playerid][8], 0.1248, 0.8008);
PlayerTextDrawAlignment(playerid, GunWFood_PTD[playerid][8], 1);
PlayerTextDrawColor(playerid, GunWFood_PTD[playerid][8], -1);
PlayerTextDrawBackgroundColor(playerid, GunWFood_PTD[playerid][8], 255);
PlayerTextDrawFont(playerid, GunWFood_PTD[playerid][8], 2);
PlayerTextDrawSetProportional(playerid, GunWFood_PTD[playerid][8], 1);
PlayerTextDrawSetShadow(playerid, GunWFood_PTD[playerid][8], 0);

GunWFood_PTD[playerid][9] = CreatePlayerTextDraw(playerid, 419.9323, 220.4335, "10"); // ?????
PlayerTextDrawLetterSize(playerid, GunWFood_PTD[playerid][9], 0.1248, 0.8008);
PlayerTextDrawAlignment(playerid, GunWFood_PTD[playerid][9], 1);
PlayerTextDrawColor(playerid, GunWFood_PTD[playerid][9], -1);
PlayerTextDrawBackgroundColor(playerid, GunWFood_PTD[playerid][9], 255);
PlayerTextDrawFont(playerid, GunWFood_PTD[playerid][9], 2);
PlayerTextDrawSetProportional(playerid, GunWFood_PTD[playerid][9], 1);
PlayerTextDrawSetShadow(playerid, GunWFood_PTD[playerid][9], 0);
