JetX_Player2[playerid] = CreatePlayerTextDraw(playerid,277.364562, 302.166687, "LD_SPAC:white");
PlayerTextDrawLetterSize(playerid,JetX_Player2[playerid], 0.000000, 0.000000);
PlayerTextDrawTextSize(playerid,JetX_Player2[playerid], 74.963378, 19.250000);
PlayerTextDrawAlignment(playerid,JetX_Player2[playerid], 1);
PlayerTextDrawColor(playerid,JetX_Player2[playerid], 8388863);
PlayerTextDrawSetShadow(playerid,JetX_Player2[playerid], 0);
PlayerTextDrawSetOutline(playerid,JetX_Player2[playerid], 0);
PlayerTextDrawFont(playerid,JetX_Player2[playerid], 4);
PlayerTextDrawSetSelectable(playerid,JetX_Player2[playerid], true);

JetX_Player0[playerid] = CreatePlayerTextDraw(playerid, 313.909332, 306.250000, "FSONIS DADEBA");
PlayerTextDrawLetterSize(playerid, JetX_Player0[playerid], 0.236822, 1.069165);
PlayerTextDrawAlignment(playerid, JetX_Player0[playerid], 2);
PlayerTextDrawColor(playerid, JetX_Player0[playerid], -1);
PlayerTextDrawSetShadow(playerid, JetX_Player0[playerid], 0);
PlayerTextDrawSetOutline(playerid, JetX_Player0[playerid], 0);
PlayerTextDrawBackgroundColor(playerid, JetX_Player0[playerid], 51);
PlayerTextDrawFont(playerid, JetX_Player0[playerid], 1);
PlayerTextDrawSetProportional(playerid, JetX_Player0[playerid], 1);

JetX_Player1[playerid] = CreatePlayerTextDraw(playerid, 313.909545, 287.583343, "FSONI: 0$");
PlayerTextDrawLetterSize(playerid, JetX_Player1[playerid], 0.204026, 1.279166);
PlayerTextDrawAlignment(playerid, JetX_Player1[playerid], 2);
PlayerTextDrawColor(playerid, JetX_Player1[playerid], -1);
PlayerTextDrawSetShadow(playerid, JetX_Player1[playerid], 0);
PlayerTextDrawSetOutline(playerid, JetX_Player1[playerid], 0);
PlayerTextDrawBackgroundColor(playerid, JetX_Player1[playerid], 51);
PlayerTextDrawFont(playerid, JetX_Player1[playerid], 2);
PlayerTextDrawSetProportional(playerid, JetX_Player1[playerid], 1);