	Lugage_PTD[playerid][0] = CreatePlayerTextDraw(playerid, 451.1711, 301.4165, "INFERNUS"); // ?????
	PlayerTextDrawLetterSize(playerid, Lugage_PTD[playerid][0], 0.2240, 1.0980);
	PlayerTextDrawAlignment(playerid, Lugage_PTD[playerid][0], 1);
	PlayerTextDrawColor(playerid, Lugage_PTD[playerid][0], -1);
	PlayerTextDrawBackgroundColor(playerid, Lugage_PTD[playerid][0], 255);
	PlayerTextDrawFont(playerid, Lugage_PTD[playerid][0], 2);
	PlayerTextDrawSetProportional(playerid, Lugage_PTD[playerid][0], 1);
	PlayerTextDrawSetShadow(playerid, Lugage_PTD[playerid][0], 0);

	Lugage_PTD[playerid][1] = CreatePlayerTextDraw(playerid, 424.6397, 311.9165, ""); // ?????
	PlayerTextDrawTextSize(playerid, Lugage_PTD[playerid][1], 90.0000, 90.0000);
	PlayerTextDrawAlignment(playerid, Lugage_PTD[playerid][1], 1);
	PlayerTextDrawColor(playerid, Lugage_PTD[playerid][1], -1);
	PlayerTextDrawBackgroundColor(playerid, Lugage_PTD[playerid][1], 0x00000000);
	PlayerTextDrawFont(playerid, Lugage_PTD[playerid][1], 5);
	PlayerTextDrawSetProportional(playerid, Lugage_PTD[playerid][1], 0);
	PlayerTextDrawSetShadow(playerid, Lugage_PTD[playerid][1], 0);
	PlayerTextDrawSetPreviewModel(playerid, Lugage_PTD[playerid][1], 411);
	PlayerTextDrawSetPreviewRot(playerid, Lugage_PTD[playerid][1], 360.0000, 360.0000, 49.0000, 1.0000);
	PlayerTextDrawSetPreviewVehCol(playerid, Lugage_PTD[playerid][1], 1, 1);

	Lugage_PTD[playerid][2] = CreatePlayerTextDraw(playerid, 607.6574, 340.2167, "3"); // ?????
	PlayerTextDrawLetterSize(playerid, Lugage_PTD[playerid][2], 0.1624, 0.9815);
	PlayerTextDrawAlignment(playerid, Lugage_PTD[playerid][2], 2);
	PlayerTextDrawColor(playerid, Lugage_PTD[playerid][2], -1);
	PlayerTextDrawBackgroundColor(playerid, Lugage_PTD[playerid][2], 255);
	PlayerTextDrawFont(playerid, Lugage_PTD[playerid][2], 2);
	PlayerTextDrawSetProportional(playerid, Lugage_PTD[playerid][2], 1);
	PlayerTextDrawSetShadow(playerid, Lugage_PTD[playerid][2], 0);

	Lugage_PTD[playerid][3] = CreatePlayerTextDraw(playerid, 543.3150, 314.8334, "1"); // ?????
	PlayerTextDrawLetterSize(playerid, Lugage_PTD[playerid][3], 0.1492, 0.8590);
	PlayerTextDrawAlignment(playerid, Lugage_PTD[playerid][3], 2);
	PlayerTextDrawColor(playerid, Lugage_PTD[playerid][3], -1);
	PlayerTextDrawBackgroundColor(playerid, Lugage_PTD[playerid][3], 255);
	PlayerTextDrawFont(playerid, Lugage_PTD[playerid][3], 2);
	PlayerTextDrawSetProportional(playerid, Lugage_PTD[playerid][3], 1);
	PlayerTextDrawSetShadow(playerid, Lugage_PTD[playerid][3], 0);

	Lugage_PTD[playerid][4] = CreatePlayerTextDraw(playerid, 606.5457, 314.8333, "2"); // ?????
	PlayerTextDrawLetterSize(playerid, Lugage_PTD[playerid][4], 0.1492, 0.8299);
	PlayerTextDrawAlignment(playerid, Lugage_PTD[playerid][4], 2);
	PlayerTextDrawColor(playerid, Lugage_PTD[playerid][4], -1);
	PlayerTextDrawBackgroundColor(playerid, Lugage_PTD[playerid][4], 255);
	PlayerTextDrawFont(playerid, Lugage_PTD[playerid][4], 2);
	PlayerTextDrawSetProportional(playerid, Lugage_PTD[playerid][4], 1);
	PlayerTextDrawSetShadow(playerid, Lugage_PTD[playerid][4], 0);

	Lugage_PTD[playerid][5] = CreatePlayerTextDraw(playerid, 533.3660, 376.6499, "5000000$"); // ?????
	PlayerTextDrawLetterSize(playerid, Lugage_PTD[playerid][5], 0.1366, 0.7947);
	PlayerTextDrawAlignment(playerid, Lugage_PTD[playerid][5], 2);
	PlayerTextDrawColor(playerid, Lugage_PTD[playerid][5], -1);
	PlayerTextDrawBackgroundColor(playerid, Lugage_PTD[playerid][5], 255);
	PlayerTextDrawFont(playerid, Lugage_PTD[playerid][5], 2);
	PlayerTextDrawSetProportional(playerid, Lugage_PTD[playerid][5], 1);
	PlayerTextDrawSetShadow(playerid, Lugage_PTD[playerid][5], 0);

	Lugage_PTD[playerid][6] = CreatePlayerTextDraw(playerid, 581.6453, 376.4833, "5"); // ?????
	PlayerTextDrawLetterSize(playerid, Lugage_PTD[playerid][6], 0.1976, 0.8883);
	PlayerTextDrawAlignment(playerid, Lugage_PTD[playerid][6], 2);
	PlayerTextDrawColor(playerid, Lugage_PTD[playerid][6], -1);
	PlayerTextDrawBackgroundColor(playerid, Lugage_PTD[playerid][6], 255);
	PlayerTextDrawFont(playerid, Lugage_PTD[playerid][6], 2);
	PlayerTextDrawSetProportional(playerid, Lugage_PTD[playerid][6], 1);
	PlayerTextDrawSetShadow(playerid, Lugage_PTD[playerid][6], 0);

	Lugage_PTD[playerid][7] = CreatePlayerTextDraw(playerid, 607.2144, 377.6163, "6"); // ?????
	PlayerTextDrawLetterSize(playerid, Lugage_PTD[playerid][7], 0.1727, 0.7832);
	PlayerTextDrawAlignment(playerid, Lugage_PTD[playerid][7], 2);
	PlayerTextDrawColor(playerid, Lugage_PTD[playerid][7], -1);
	PlayerTextDrawBackgroundColor(playerid, Lugage_PTD[playerid][7], 255);
	PlayerTextDrawFont(playerid, Lugage_PTD[playerid][7], 2);
	PlayerTextDrawSetProportional(playerid, Lugage_PTD[playerid][7], 1);
	PlayerTextDrawSetShadow(playerid, Lugage_PTD[playerid][7], 0);