stock CreateMM(playerid)
{
 GenuineMenu[playerid][0] = CreatePlayerTextDraw(playerid, 184.0950, 114.9067, "Box"); // ?????
	PlayerTextDrawLetterSize(playerid, GenuineMenu[playerid][0], 0.0000, 19.5739);
	PlayerTextDrawTextSize(playerid, GenuineMenu[playerid][0], 423.0000, 0.0000);
	PlayerTextDrawAlignment(playerid, GenuineMenu[playerid][0], 1);
	PlayerTextDrawColor(playerid, GenuineMenu[playerid][0], -1);
	PlayerTextDrawUseBox(playerid, GenuineMenu[playerid][0], 1);
	PlayerTextDrawBoxColor(playerid, GenuineMenu[playerid][0], 150);
	PlayerTextDrawFont(playerid, GenuineMenu[playerid][0], 1);
	PlayerTextDrawSetProportional(playerid, GenuineMenu[playerid][0], 1);
	PlayerTextDrawSetShadow(playerid, GenuineMenu[playerid][0], 0);

	GenuineMenu[playerid][1] = CreatePlayerTextDraw(playerid, 184.0953, 87.5998, "Box"); // ?????
	PlayerTextDrawLetterSize(playerid, GenuineMenu[playerid][1], -0.0015, 2.6486);
	PlayerTextDrawTextSize(playerid, GenuineMenu[playerid][1], 423.0000, 0.0000);
	PlayerTextDrawAlignment(playerid, GenuineMenu[playerid][1], 1);
	PlayerTextDrawColor(playerid, GenuineMenu[playerid][1], -1);
	PlayerTextDrawUseBox(playerid, GenuineMenu[playerid][1], 1);
	PlayerTextDrawBoxColor(playerid, GenuineMenu[playerid][1], -1523963137);
	PlayerTextDrawBackgroundColor(playerid, GenuineMenu[playerid][1], 255);
	PlayerTextDrawFont(playerid, GenuineMenu[playerid][1], 1);
	PlayerTextDrawSetProportional(playerid, GenuineMenu[playerid][1], 1);
	PlayerTextDrawSetShadow(playerid, GenuineMenu[playerid][1], 0);

	GenuineMenu[playerid][2] = CreatePlayerTextDraw(playerid, 187.9048, 91.4396, "GENUINE_ROLE_PLAY_-_MAINMENU"); // ?????
	PlayerTextDrawLetterSize(playerid, GenuineMenu[playerid][2], 0.4277, 1.7962);
	PlayerTextDrawAlignment(playerid, GenuineMenu[playerid][2], 1);
	PlayerTextDrawColor(playerid, GenuineMenu[playerid][2], -1);
	PlayerTextDrawBackgroundColor(playerid, GenuineMenu[playerid][2], 255);
	PlayerTextDrawFont(playerid, GenuineMenu[playerid][2], 1);
	PlayerTextDrawSetProportional(playerid, GenuineMenu[playerid][2], 1);
	PlayerTextDrawSetShadow(playerid, GenuineMenu[playerid][2], 1);

	GenuineMenu[playerid][3] = CreatePlayerTextDraw(playerid, 188.2857, 120.8796, "Box"); // ?????
	PlayerTextDrawLetterSize(playerid, GenuineMenu[playerid][3], 0.0006, 0.7163);
	PlayerTextDrawTextSize(playerid, GenuineMenu[playerid][3], 259.0000, 0.0000);
	PlayerTextDrawAlignment(playerid, GenuineMenu[playerid][3], 1);
	PlayerTextDrawColor(playerid, GenuineMenu[playerid][3], -1);
	PlayerTextDrawUseBox(playerid, GenuineMenu[playerid][3], 1);
	PlayerTextDrawBoxColor(playerid, GenuineMenu[playerid][3], -1523963137);
	PlayerTextDrawBackgroundColor(playerid, GenuineMenu[playerid][3], 255);
	PlayerTextDrawFont(playerid, GenuineMenu[playerid][3], 1);
	PlayerTextDrawSetProportional(playerid, GenuineMenu[playerid][3], 1);
	PlayerTextDrawSetShadow(playerid, GenuineMenu[playerid][3], 0);

	GenuineMenu[playerid][4] = CreatePlayerTextDraw(playerid, 189.0476, 118.5198, "Aleksandre_Kinkladze"); // ?????
	PlayerTextDrawLetterSize(playerid, GenuineMenu[playerid][4], 0.1976, 1.1093);
	PlayerTextDrawAlignment(playerid, GenuineMenu[playerid][4], 1);
	PlayerTextDrawColor(playerid, GenuineMenu[playerid][4], -1);
	PlayerTextDrawBackgroundColor(playerid, GenuineMenu[playerid][4], 255);
	PlayerTextDrawFont(playerid, GenuineMenu[playerid][4], 1);
	PlayerTextDrawSetProportional(playerid, GenuineMenu[playerid][4], 1);
	PlayerTextDrawSetShadow(playerid, GenuineMenu[playerid][4], 0);

	GenuineMenu[playerid][5] = CreatePlayerTextDraw(playerid, 169.7619, 125.0999, ""); // ?????
	PlayerTextDrawTextSize(playerid, GenuineMenu[playerid][5], 105.0000, 99.0000);
	PlayerTextDrawAlignment(playerid, GenuineMenu[playerid][5], 1);
	PlayerTextDrawColor(playerid, GenuineMenu[playerid][5], -1);
	PlayerTextDrawFont(playerid, GenuineMenu[playerid][5], 5);
	PlayerTextDrawSetProportional(playerid, GenuineMenu[playerid][5], 0);
	PlayerTextDrawSetShadow(playerid, GenuineMenu[playerid][5], 0);
  	PlayerTextDrawBoxColor(playerid, GenuineMenu[playerid][5], 0x00000000);
	PlayerTextDrawBackgroundColor(playerid, GenuineMenu[playerid][5], 0x00000000);
	PlayerTextDrawSetPreviewModel(playerid, GenuineMenu[playerid][5], 0);
	PlayerTextDrawSetPreviewRot(playerid, GenuineMenu[playerid][5], 0.0000, 0.0000, 0.0000, 1.0000);

	GenuineMenu[playerid][6] = CreatePlayerTextDraw(playerid, 185.7619, 230.2338, "LD_BEAT:chit"); // ?????
	PlayerTextDrawTextSize(playerid, GenuineMenu[playerid][6], 77.0000, 6.0000);
	PlayerTextDrawAlignment(playerid, GenuineMenu[playerid][6], 1);
	PlayerTextDrawColor(playerid, GenuineMenu[playerid][6], -86);
	PlayerTextDrawBackgroundColor(playerid, GenuineMenu[playerid][6], 255);
	PlayerTextDrawFont(playerid, GenuineMenu[playerid][6], 4);
	PlayerTextDrawSetProportional(playerid, GenuineMenu[playerid][6], 0);
	PlayerTextDrawSetShadow(playerid, GenuineMenu[playerid][6], 0);

	GenuineMenu[playerid][7] = CreatePlayerTextDraw(playerid, 188.6665, 242.2203, "Box"); // ?????
	PlayerTextDrawLetterSize(playerid, GenuineMenu[playerid][7], 0.0003, -0.3366);
	PlayerTextDrawTextSize(playerid, GenuineMenu[playerid][7], 259.0000, 0.0000);
	PlayerTextDrawAlignment(playerid, GenuineMenu[playerid][7], 1);
	PlayerTextDrawColor(playerid, GenuineMenu[playerid][7], -1);
	PlayerTextDrawUseBox(playerid, GenuineMenu[playerid][7], 1);
	PlayerTextDrawBoxColor(playerid, GenuineMenu[playerid][7], -1);
	PlayerTextDrawBackgroundColor(playerid, GenuineMenu[playerid][7], 255);
	PlayerTextDrawFont(playerid, GenuineMenu[playerid][7], 1);
	PlayerTextDrawSetProportional(playerid, GenuineMenu[playerid][7], 1);
	PlayerTextDrawSetShadow(playerid, GenuineMenu[playerid][7], 0);

	GenuineMenu[playerid][8] = CreatePlayerTextDraw(playerid, 186.8047, 248.6005, "LD_OTB2:butnA"); // ?????
	PlayerTextDrawTextSize(playerid, GenuineMenu[playerid][8], 74.0000, 19.0000);
	PlayerTextDrawAlignment(playerid, GenuineMenu[playerid][8], 1);
	PlayerTextDrawColor(playerid, GenuineMenu[playerid][8], -1356783105);
	PlayerTextDrawBackgroundColor(playerid, GenuineMenu[playerid][8], 255);
	PlayerTextDrawFont(playerid, GenuineMenu[playerid][8], 4);
	PlayerTextDrawSetProportional(playerid, GenuineMenu[playerid][8], 0);
	PlayerTextDrawSetShadow(playerid, GenuineMenu[playerid][8], 0);
	PlayerTextDrawSetSelectable(playerid, GenuineMenu[playerid][8], true);

	GenuineMenu[playerid][9] = CreatePlayerTextDraw(playerid, 190.8526, 248.0604, "PROMOCODE"); // ?????
	PlayerTextDrawLetterSize(playerid, GenuineMenu[playerid][9], 0.2712, 1.5146);
	PlayerTextDrawAlignment(playerid, GenuineMenu[playerid][9], 1);
	PlayerTextDrawColor(playerid, GenuineMenu[playerid][9], -1);
	PlayerTextDrawBackgroundColor(playerid, GenuineMenu[playerid][9], 255);
	PlayerTextDrawFont(playerid, GenuineMenu[playerid][9], 2);
	PlayerTextDrawSetProportional(playerid, GenuineMenu[playerid][9], 1);
	PlayerTextDrawSetShadow(playerid, GenuineMenu[playerid][9], 1);

	GenuineMenu[playerid][10] = CreatePlayerTextDraw(playerid, 186.8237, 272.2812, "LD_OTB2:butnA"); // ?????
	PlayerTextDrawTextSize(playerid, GenuineMenu[playerid][10], 74.0000, 19.0000);
	PlayerTextDrawAlignment(playerid, GenuineMenu[playerid][10], 1);
	PlayerTextDrawColor(playerid, GenuineMenu[playerid][10], -1356783105);
	PlayerTextDrawBackgroundColor(playerid, GenuineMenu[playerid][10], 255);
	PlayerTextDrawFont(playerid, GenuineMenu[playerid][10], 4);
	PlayerTextDrawSetProportional(playerid, GenuineMenu[playerid][10], 0);
	PlayerTextDrawSetShadow(playerid, GenuineMenu[playerid][10], 0);
	PlayerTextDrawSetSelectable(playerid, GenuineMenu[playerid][10], true);

	GenuineMenu[playerid][11] = CreatePlayerTextDraw(playerid, 201.4857, 271.1604, "DONATE"); // ?????
	PlayerTextDrawLetterSize(playerid, GenuineMenu[playerid][11], 0.2712, 1.5146);
	PlayerTextDrawAlignment(playerid, GenuineMenu[playerid][11], 1);
	PlayerTextDrawColor(playerid, GenuineMenu[playerid][11], -1);
	PlayerTextDrawBackgroundColor(playerid, GenuineMenu[playerid][11], 255);
	PlayerTextDrawFont(playerid, GenuineMenu[playerid][11], 2);
	PlayerTextDrawSetProportional(playerid, GenuineMenu[playerid][11], 1);
	PlayerTextDrawSetShadow(playerid, GenuineMenu[playerid][11], 1);

	GenuineMenu[playerid][12] = CreatePlayerTextDraw(playerid, 327.7978, 118.2874, "LD_OTB2:butnA"); // ?????
	PlayerTextDrawTextSize(playerid, GenuineMenu[playerid][12], 87.0000, 21.0000);
	PlayerTextDrawAlignment(playerid, GenuineMenu[playerid][12], 1);
	PlayerTextDrawColor(playerid, GenuineMenu[playerid][12], -1356783105);
	PlayerTextDrawBackgroundColor(playerid, GenuineMenu[playerid][12], 255);
	PlayerTextDrawFont(playerid, GenuineMenu[playerid][12], 4);
	PlayerTextDrawSetProportional(playerid, GenuineMenu[playerid][12], 0);
	PlayerTextDrawSetShadow(playerid, GenuineMenu[playerid][12], 0);
	PlayerTextDrawSetSelectable(playerid, GenuineMenu[playerid][12], true);

	GenuineMenu[playerid][13] = CreatePlayerTextDraw(playerid, 331.4617, 117.7933, "MAIN_ACCOUNT"); // ?????
	PlayerTextDrawLetterSize(playerid, GenuineMenu[playerid][13], 0.2716, 1.6000);
	PlayerTextDrawAlignment(playerid, GenuineMenu[playerid][13], 1);
	PlayerTextDrawColor(playerid, GenuineMenu[playerid][13], -1);
	PlayerTextDrawBackgroundColor(playerid, GenuineMenu[playerid][13], 255);
	PlayerTextDrawFont(playerid, GenuineMenu[playerid][13], 2);
	PlayerTextDrawSetProportional(playerid, GenuineMenu[playerid][13], 1);
	PlayerTextDrawSetShadow(playerid, GenuineMenu[playerid][13], 1);

	GenuineMenu[playerid][14] = CreatePlayerTextDraw(playerid, 327.8953, 139.5080, "LD_OTB2:butnA"); // ?????
	PlayerTextDrawTextSize(playerid, GenuineMenu[playerid][14], 87.0000, 21.0000);
	PlayerTextDrawAlignment(playerid, GenuineMenu[playerid][14], 1);
	PlayerTextDrawColor(playerid, GenuineMenu[playerid][14], -1356783105);
	PlayerTextDrawBackgroundColor(playerid, GenuineMenu[playerid][14], 255);
	PlayerTextDrawFont(playerid, GenuineMenu[playerid][14], 4);
	PlayerTextDrawSetProportional(playerid, GenuineMenu[playerid][14], 0);
	PlayerTextDrawSetShadow(playerid, GenuineMenu[playerid][14], 0);
	PlayerTextDrawSetSelectable(playerid, GenuineMenu[playerid][14], true);

	GenuineMenu[playerid][15] = CreatePlayerTextDraw(playerid, 336.7668, 139.1463, "Settings"); // ?????
	PlayerTextDrawLetterSize(playerid, GenuineMenu[playerid][15], 0.3561, 1.5957);
	PlayerTextDrawAlignment(playerid, GenuineMenu[playerid][15], 1);
	PlayerTextDrawColor(playerid, GenuineMenu[playerid][15], -1);
	PlayerTextDrawBackgroundColor(playerid, GenuineMenu[playerid][15], 255);
	PlayerTextDrawFont(playerid, GenuineMenu[playerid][15], 2);
	PlayerTextDrawSetProportional(playerid, GenuineMenu[playerid][15], 1);
	PlayerTextDrawSetShadow(playerid, GenuineMenu[playerid][15], 1);

	GenuineMenu[playerid][16] = CreatePlayerTextDraw(playerid, 327.9192, 161.3683, "LD_OTB2:butnA"); // ?????
	PlayerTextDrawTextSize(playerid, GenuineMenu[playerid][16], 87.0000, 22.0000);
	PlayerTextDrawAlignment(playerid, GenuineMenu[playerid][16], 1);
	PlayerTextDrawColor(playerid, GenuineMenu[playerid][16], -1356783105);
	PlayerTextDrawBackgroundColor(playerid, GenuineMenu[playerid][16], 255);
	PlayerTextDrawFont(playerid, GenuineMenu[playerid][16], 4);
	PlayerTextDrawSetProportional(playerid, GenuineMenu[playerid][16], 0);
	PlayerTextDrawSetShadow(playerid, GenuineMenu[playerid][16], 0);
	PlayerTextDrawSetSelectable(playerid, GenuineMenu[playerid][16], true);

	GenuineMenu[playerid][17] = CreatePlayerTextDraw(playerid, 338.8999, 161.6465, "Security"); // ?????
	PlayerTextDrawLetterSize(playerid, GenuineMenu[playerid][17], 0.3527, 1.5317);
	PlayerTextDrawAlignment(playerid, GenuineMenu[playerid][17], 1);
	PlayerTextDrawColor(playerid, GenuineMenu[playerid][17], -1);
	PlayerTextDrawBackgroundColor(playerid, GenuineMenu[playerid][17], 255);
	PlayerTextDrawFont(playerid, GenuineMenu[playerid][17], 2);
	PlayerTextDrawSetProportional(playerid, GenuineMenu[playerid][17], 1);
	PlayerTextDrawSetShadow(playerid, GenuineMenu[playerid][17], 1);

	GenuineMenu[playerid][18] = CreatePlayerTextDraw(playerid, 327.9764, 183.8697, "LD_OTB2:butnA"); // ?????
	PlayerTextDrawTextSize(playerid, GenuineMenu[playerid][18], 87.0000, 21.0000);
	PlayerTextDrawAlignment(playerid, GenuineMenu[playerid][18], 1);
	PlayerTextDrawColor(playerid, GenuineMenu[playerid][18], -1356783105);
	PlayerTextDrawBackgroundColor(playerid, GenuineMenu[playerid][18], 255);
	PlayerTextDrawFont(playerid, GenuineMenu[playerid][18], 4);
	PlayerTextDrawSetProportional(playerid, GenuineMenu[playerid][18], 0);
	PlayerTextDrawSetShadow(playerid, GenuineMenu[playerid][18], 0);
	PlayerTextDrawSetSelectable(playerid, GenuineMenu[playerid][18], true);

	GenuineMenu[playerid][19] = CreatePlayerTextDraw(playerid, 334.8424, 183.8610, "COMMANDS"); // ?????
	PlayerTextDrawLetterSize(playerid, GenuineMenu[playerid][19], 0.3279, 1.5232);
	PlayerTextDrawAlignment(playerid, GenuineMenu[playerid][19], 1);
	PlayerTextDrawColor(playerid, GenuineMenu[playerid][19], -1);
	PlayerTextDrawBackgroundColor(playerid, GenuineMenu[playerid][19], 255);
	PlayerTextDrawFont(playerid, GenuineMenu[playerid][19], 2);
	PlayerTextDrawSetProportional(playerid, GenuineMenu[playerid][19], 1);
	PlayerTextDrawSetShadow(playerid, GenuineMenu[playerid][19], 1);

	GenuineMenu[playerid][20] = CreatePlayerTextDraw(playerid, 327.6145, 205.4108, "LD_OTB2:butnA"); // ?????
	PlayerTextDrawTextSize(playerid, GenuineMenu[playerid][20], 87.0000, 22.0000);
	PlayerTextDrawAlignment(playerid, GenuineMenu[playerid][20], 1);
	PlayerTextDrawColor(playerid, GenuineMenu[playerid][20], -1356783105);
	PlayerTextDrawBackgroundColor(playerid, GenuineMenu[playerid][20], 255);
	PlayerTextDrawFont(playerid, GenuineMenu[playerid][20], 4);
	PlayerTextDrawSetProportional(playerid, GenuineMenu[playerid][20], 0);
	PlayerTextDrawSetShadow(playerid, GenuineMenu[playerid][20], 0);
	PlayerTextDrawSetSelectable(playerid, GenuineMenu[playerid][20], true);

	GenuineMenu[playerid][21] = CreatePlayerTextDraw(playerid, 330.8902, 205.3558, "Accessorie"); // ?????
	PlayerTextDrawLetterSize(playerid, GenuineMenu[playerid][21], 0.3241, 1.5488);
	PlayerTextDrawAlignment(playerid, GenuineMenu[playerid][21], 1);
	PlayerTextDrawColor(playerid, GenuineMenu[playerid][21], -1);
	PlayerTextDrawBackgroundColor(playerid, GenuineMenu[playerid][21], 255);
	PlayerTextDrawFont(playerid, GenuineMenu[playerid][21], 2);
	PlayerTextDrawSetProportional(playerid, GenuineMenu[playerid][21], 1);
	PlayerTextDrawSetShadow(playerid, GenuineMenu[playerid][21], 1);

	GenuineMenu[playerid][22] = CreatePlayerTextDraw(playerid, 327.5526, 227.7654, "LD_OTB2:butnA"); // ?????
	PlayerTextDrawTextSize(playerid, GenuineMenu[playerid][22], 87.0000, 21.0000);
	PlayerTextDrawAlignment(playerid, GenuineMenu[playerid][22], 1);
	PlayerTextDrawColor(playerid, GenuineMenu[playerid][22], -1356783105);
	PlayerTextDrawBackgroundColor(playerid, GenuineMenu[playerid][22], 255);
	PlayerTextDrawFont(playerid, GenuineMenu[playerid][22], 4);
	PlayerTextDrawSetProportional(playerid, GenuineMenu[playerid][22], 0);
	PlayerTextDrawSetShadow(playerid, GenuineMenu[playerid][22], 0);
	PlayerTextDrawSetSelectable(playerid, GenuineMenu[playerid][22], true);

	GenuineMenu[playerid][23] = CreatePlayerTextDraw(playerid, 344.0188, 227.4505, "REPORT"); // ?????
	PlayerTextDrawLetterSize(playerid, GenuineMenu[playerid][23], 0.3546, 1.5744);
	PlayerTextDrawAlignment(playerid, GenuineMenu[playerid][23], 1);
	PlayerTextDrawColor(playerid, GenuineMenu[playerid][23], -1);
	PlayerTextDrawBackgroundColor(playerid, GenuineMenu[playerid][23], 255);
	PlayerTextDrawFont(playerid, GenuineMenu[playerid][23], 2);
	PlayerTextDrawSetProportional(playerid, GenuineMenu[playerid][23], 1);
	PlayerTextDrawSetShadow(playerid, GenuineMenu[playerid][23], 1);

	GenuineMenu[playerid][24] = CreatePlayerTextDraw(playerid, 327.8573, 249.0294, "LD_OTB2:butnA"); // ?????
	PlayerTextDrawTextSize(playerid, GenuineMenu[playerid][24], 87.0000, 20.0000);
	PlayerTextDrawAlignment(playerid, GenuineMenu[playerid][24], 1);
	PlayerTextDrawColor(playerid, GenuineMenu[playerid][24], -1356783105);
	PlayerTextDrawBackgroundColor(playerid, GenuineMenu[playerid][24], 255);
	PlayerTextDrawFont(playerid, GenuineMenu[playerid][24], 4);
	PlayerTextDrawSetProportional(playerid, GenuineMenu[playerid][24], 0);
	PlayerTextDrawSetShadow(playerid, GenuineMenu[playerid][24], 0);
	PlayerTextDrawSetSelectable(playerid, GenuineMenu[playerid][24], true);

	GenuineMenu[playerid][25] = CreatePlayerTextDraw(playerid, 329.9856, 248.3719, "Modificate_Skins"); // ?????
	PlayerTextDrawLetterSize(playerid, GenuineMenu[playerid][25], 0.2224, 1.6384);
	PlayerTextDrawAlignment(playerid, GenuineMenu[playerid][25], 1);
	PlayerTextDrawColor(playerid, GenuineMenu[playerid][25], -1);
	PlayerTextDrawBackgroundColor(playerid, GenuineMenu[playerid][25], 255);
	PlayerTextDrawFont(playerid, GenuineMenu[playerid][25], 2);
	PlayerTextDrawSetProportional(playerid, GenuineMenu[playerid][25], 1);
	PlayerTextDrawSetShadow(playerid, GenuineMenu[playerid][25], 1);

	GenuineMenu[playerid][26] = CreatePlayerTextDraw(playerid, 327.6144, 270.3217, "LD_OTB2:butnA"); // ?????
	PlayerTextDrawTextSize(playerid, GenuineMenu[playerid][26], 87.0000, 21.0000);
	PlayerTextDrawAlignment(playerid, GenuineMenu[playerid][26], 1);
	PlayerTextDrawColor(playerid, GenuineMenu[playerid][26], -1356783105);
	PlayerTextDrawBackgroundColor(playerid, GenuineMenu[playerid][26], 255);
	PlayerTextDrawFont(playerid, GenuineMenu[playerid][26], 4);
	PlayerTextDrawSetProportional(playerid, GenuineMenu[playerid][26], 0);
	PlayerTextDrawSetShadow(playerid, GenuineMenu[playerid][26], 0);
	PlayerTextDrawSetSelectable(playerid, GenuineMenu[playerid][26], true);

	GenuineMenu[playerid][27] = CreatePlayerTextDraw(playerid, 330.7999, 268.8399, "SPIN_ROULETTE"); // ?????
	PlayerTextDrawLetterSize(playerid, GenuineMenu[playerid][27], 0.2605, 1.7791);
	PlayerTextDrawTextSize(playerid, GenuineMenu[playerid][27], -11.0000, 0.0000);
	PlayerTextDrawAlignment(playerid, GenuineMenu[playerid][27], 1);
	PlayerTextDrawColor(playerid, GenuineMenu[playerid][27], -1);
	PlayerTextDrawBackgroundColor(playerid, GenuineMenu[playerid][27], 255);
	PlayerTextDrawFont(playerid, GenuineMenu[playerid][27], 2);
	PlayerTextDrawSetProportional(playerid, GenuineMenu[playerid][27], 1);
	PlayerTextDrawSetShadow(playerid, GenuineMenu[playerid][27], 1);

	GenuineMenu[playerid][28] = CreatePlayerTextDraw(playerid, 184.1762, 114.8800, "Box"); // ?????
	PlayerTextDrawLetterSize(playerid, GenuineMenu[playerid][28], 0.0000, 19.5619);
	PlayerTextDrawTextSize(playerid, GenuineMenu[playerid][28], 182.0000, 0.0000);
	PlayerTextDrawAlignment(playerid, GenuineMenu[playerid][28], 1);
	PlayerTextDrawColor(playerid, GenuineMenu[playerid][28], -1);
	PlayerTextDrawUseBox(playerid, GenuineMenu[playerid][28], 1);
	PlayerTextDrawBoxColor(playerid, GenuineMenu[playerid][28], -1);
	PlayerTextDrawBackgroundColor(playerid, GenuineMenu[playerid][28], 255);
	PlayerTextDrawFont(playerid, GenuineMenu[playerid][28], 1);
	PlayerTextDrawSetProportional(playerid, GenuineMenu[playerid][28], 1);
	PlayerTextDrawSetShadow(playerid, GenuineMenu[playerid][28], 0);

	GenuineMenu[playerid][29] = CreatePlayerTextDraw(playerid, 184.4953, 293.6799, "Box"); // ?????
	PlayerTextDrawLetterSize(playerid, GenuineMenu[playerid][29], -0.0019, -0.2899);
	PlayerTextDrawTextSize(playerid, GenuineMenu[playerid][29], 423.0000, 0.0000);
	PlayerTextDrawAlignment(playerid, GenuineMenu[playerid][29], 1);
	PlayerTextDrawColor(playerid, GenuineMenu[playerid][29], -1);
	PlayerTextDrawUseBox(playerid, GenuineMenu[playerid][29], 1);
	PlayerTextDrawBoxColor(playerid, GenuineMenu[playerid][29], -1);
	PlayerTextDrawBackgroundColor(playerid, GenuineMenu[playerid][29], 255);
	PlayerTextDrawFont(playerid, GenuineMenu[playerid][29], 1);
	PlayerTextDrawSetProportional(playerid, GenuineMenu[playerid][29], 1);
	PlayerTextDrawSetShadow(playerid, GenuineMenu[playerid][29], 0);

	GenuineMenu[playerid][30] = CreatePlayerTextDraw(playerid, 425.2380, 115.5533, "Box"); // ?????
	PlayerTextDrawLetterSize(playerid, GenuineMenu[playerid][30], -0.0003, 19.5097);
	PlayerTextDrawTextSize(playerid, GenuineMenu[playerid][30], 423.0000, 0.0000);
	PlayerTextDrawAlignment(playerid, GenuineMenu[playerid][30], 1);
	PlayerTextDrawColor(playerid, GenuineMenu[playerid][30], -1);
	PlayerTextDrawUseBox(playerid, GenuineMenu[playerid][30], 1);
	PlayerTextDrawBoxColor(playerid, GenuineMenu[playerid][30], -1);
	PlayerTextDrawBackgroundColor(playerid, GenuineMenu[playerid][30], 255);
	PlayerTextDrawFont(playerid, GenuineMenu[playerid][30], 1);
	PlayerTextDrawSetProportional(playerid, GenuineMenu[playerid][30], 1);
	PlayerTextDrawSetShadow(playerid, GenuineMenu[playerid][30], 0);

	GenuineMenu[playerid][31] = CreatePlayerTextDraw(playerid, 184.8571, 114.9067, "Box"); // ?????
	PlayerTextDrawLetterSize(playerid, GenuineMenu[playerid][31], 0.0000, -0.2476);
	PlayerTextDrawTextSize(playerid, GenuineMenu[playerid][31], 423.0000, 0.0000);
	PlayerTextDrawAlignment(playerid, GenuineMenu[playerid][31], 1);
	PlayerTextDrawColor(playerid, GenuineMenu[playerid][31], -1);
	PlayerTextDrawUseBox(playerid, GenuineMenu[playerid][31], 1);
	PlayerTextDrawBoxColor(playerid, GenuineMenu[playerid][31], -1);
	PlayerTextDrawBackgroundColor(playerid, GenuineMenu[playerid][31], 255);
	PlayerTextDrawFont(playerid, GenuineMenu[playerid][31], 1);
	PlayerTextDrawSetProportional(playerid, GenuineMenu[playerid][31], 1);
	PlayerTextDrawSetShadow(playerid, GenuineMenu[playerid][31], 0);
}