Bank_PTD[playerid][0] = CreatePlayerTextDraw(playerid, 510.9740, 217.9999, "LD_SPAC:white"); // ?????
PlayerTextDrawTextSize(playerid, Bank_PTD[playerid][0], 115.0000, 64.0000);
PlayerTextDrawAlignment(playerid, Bank_PTD[playerid][0], 1);
PlayerTextDrawColor(playerid, Bank_PTD[playerid][0], 0x4C9F82FF);
PlayerTextDrawBackgroundColor(playerid, Bank_PTD[playerid][0], 255);
PlayerTextDrawFont(playerid, Bank_PTD[playerid][0], 4);
PlayerTextDrawSetProportional(playerid, Bank_PTD[playerid][0], 0);
PlayerTextDrawSetShadow(playerid, Bank_PTD[playerid][0], 0);

Bank_PTD[playerid][1] = CreatePlayerTextDraw(playerid,515.1909, 212.7499, "LD_SPAC:white"); // ?????
PlayerTextDrawTextSize(playerid, Bank_PTD[playerid][1], 107.0000, 75.0000);
PlayerTextDrawAlignment(playerid, Bank_PTD[playerid][1], 1);
PlayerTextDrawColor(playerid, Bank_PTD[playerid][1], 0x4C9F82FF);
PlayerTextDrawBackgroundColor(playerid, Bank_PTD[playerid][1], 255);
PlayerTextDrawFont(playerid, Bank_PTD[playerid][1], 4);
PlayerTextDrawSetProportional(playerid, Bank_PTD[playerid][1], 0);
PlayerTextDrawSetShadow(playerid, Bank_PTD[playerid][1], 0);

Bank_PTD[playerid][2] = CreatePlayerTextDraw(playerid,615.9232, 210.4166, "LD_BEAT:chit"); // ?????
PlayerTextDrawTextSize(playerid, Bank_PTD[playerid][2], 12.0000, 15.0000);
PlayerTextDrawAlignment(playerid, Bank_PTD[playerid][2], 1);
PlayerTextDrawColor(playerid, Bank_PTD[playerid][2], 0x4C9F82FF);
PlayerTextDrawBackgroundColor(playerid, Bank_PTD[playerid][2], 255);
PlayerTextDrawFont(playerid, Bank_PTD[playerid][2], 4);
PlayerTextDrawSetProportional(playerid, Bank_PTD[playerid][2], 0);
PlayerTextDrawSetShadow(playerid, Bank_PTD[playerid][2], 0);

Bank_PTD[playerid][3] = CreatePlayerTextDraw(playerid,615.9232, 275.1669, "LD_BEAT:chit"); // ?????
PlayerTextDrawTextSize(playerid, Bank_PTD[playerid][3], 12.0000, 15.0000);
PlayerTextDrawAlignment(playerid, Bank_PTD[playerid][3], 1);
PlayerTextDrawColor(playerid, Bank_PTD[playerid][3], 0x4C9F82FF);
PlayerTextDrawBackgroundColor(playerid, Bank_PTD[playerid][3], 255);
PlayerTextDrawFont(playerid, Bank_PTD[playerid][3], 4);
PlayerTextDrawSetProportional(playerid, Bank_PTD[playerid][3], 0);
PlayerTextDrawSetShadow(playerid, Bank_PTD[playerid][3], 0);

Bank_PTD[playerid][4] = CreatePlayerTextDraw(playerid,509.1000, 210.4166, "LD_BEAT:chit"); // ?????
PlayerTextDrawTextSize(playerid, Bank_PTD[playerid][4], 12.0000, 15.0000);
PlayerTextDrawAlignment(playerid, Bank_PTD[playerid][4], 1);
PlayerTextDrawColor(playerid, Bank_PTD[playerid][4], 0x4C9F82FF);
PlayerTextDrawBackgroundColor(playerid, Bank_PTD[playerid][4], 255);
PlayerTextDrawFont(playerid, Bank_PTD[playerid][4], 4);
PlayerTextDrawSetProportional(playerid, Bank_PTD[playerid][4], 0);
PlayerTextDrawSetShadow(playerid, Bank_PTD[playerid][4], 0);

Bank_PTD[playerid][5] = CreatePlayerTextDraw(playerid,509.1000, 275.1668, "LD_BEAT:chit"); // ?????
PlayerTextDrawTextSize(playerid, Bank_PTD[playerid][5], 12.0000, 15.0000);
PlayerTextDrawAlignment(playerid, Bank_PTD[playerid][5], 1);
PlayerTextDrawColor(playerid, Bank_PTD[playerid][5], 0x4C9F82FF);
PlayerTextDrawBackgroundColor(playerid, Bank_PTD[playerid][5], 255);
PlayerTextDrawFont(playerid, Bank_PTD[playerid][5], 4);
PlayerTextDrawSetProportional(playerid, Bank_PTD[playerid][5], 0);
PlayerTextDrawSetShadow(playerid, Bank_PTD[playerid][5], 0);

Bank_PTD[playerid][6] = CreatePlayerTextDraw(playerid,519.1075, 217.4166, "G"); // ?????
PlayerTextDrawLetterSize(playerid, Bank_PTD[playerid][6], 0.4651, 1.8975);
PlayerTextDrawTextSize(playerid, Bank_PTD[playerid][6], 18.0000, 0.0000);
PlayerTextDrawAlignment(playerid, Bank_PTD[playerid][6], 1);
PlayerTextDrawColor(playerid, Bank_PTD[playerid][6], -1);
PlayerTextDrawBackgroundColor(playerid, Bank_PTD[playerid][6], 255);
PlayerTextDrawFont(playerid, Bank_PTD[playerid][6], 1);
PlayerTextDrawSetProportional(playerid, Bank_PTD[playerid][6], 1);
PlayerTextDrawSetShadow(playerid, Bank_PTD[playerid][6], 0);

Bank_PTD[playerid][7] = CreatePlayerTextDraw(playerid,518.4706, 234.3333, "LD_SPAC:white"); // ?????
PlayerTextDrawTextSize(playerid, Bank_PTD[playerid][7], 11.0000, 1.0000);
PlayerTextDrawAlignment(playerid, Bank_PTD[playerid][7], 1);
PlayerTextDrawColor(playerid, Bank_PTD[playerid][7], -1);
PlayerTextDrawBackgroundColor(playerid, Bank_PTD[playerid][7], 255);
PlayerTextDrawFont(playerid, Bank_PTD[playerid][7], 4);
PlayerTextDrawSetProportional(playerid, Bank_PTD[playerid][7], 0);
PlayerTextDrawSetShadow(playerid, Bank_PTD[playerid][7], 0);

Bank_PTD[playerid][8] = CreatePlayerTextDraw(playerid,528.9464, 224.4165, " enuine-Bank"); // ?????
PlayerTextDrawLetterSize(playerid, Bank_PTD[playerid][8], 0.1877, 0.9000);
PlayerTextDrawAlignment(playerid, Bank_PTD[playerid][8], 1);
PlayerTextDrawColor(playerid, Bank_PTD[playerid][8], -1);
PlayerTextDrawBackgroundColor(playerid, Bank_PTD[playerid][8], 255);
PlayerTextDrawFont(playerid, Bank_PTD[playerid][8], 1);
PlayerTextDrawSetProportional(playerid, Bank_PTD[playerid][8], 1);
PlayerTextDrawSetShadow(playerid, Bank_PTD[playerid][8], 0);

Bank_PTD[playerid][9] = CreatePlayerTextDraw(playerid,586.5749, 222.6666, "Visa_Platinum"); // ?????
PlayerTextDrawLetterSize(playerid, Bank_PTD[playerid][9], 0.1952, 0.8708);
PlayerTextDrawAlignment(playerid, Bank_PTD[playerid][9], 1);
PlayerTextDrawColor(playerid, Bank_PTD[playerid][9], -1);
PlayerTextDrawBackgroundColor(playerid, Bank_PTD[playerid][9], 255);
PlayerTextDrawFont(playerid, Bank_PTD[playerid][9], 0);
PlayerTextDrawSetProportional(playerid, Bank_PTD[playerid][9], 1);
PlayerTextDrawSetShadow(playerid, Bank_PTD[playerid][9], 0);

Bank_PTD[playerid][10] = CreatePlayerTextDraw(playerid,617.4974, 234.3333, ")"); // ?????
PlayerTextDrawLetterSize(playerid, Bank_PTD[playerid][10], 0.2781, 1.7808);
PlayerTextDrawAlignment(playerid, Bank_PTD[playerid][10], 1);
PlayerTextDrawColor(playerid, Bank_PTD[playerid][10], -1);
PlayerTextDrawBackgroundColor(playerid, Bank_PTD[playerid][10], 255);
PlayerTextDrawFont(playerid, Bank_PTD[playerid][10], 1);
PlayerTextDrawSetProportional(playerid, Bank_PTD[playerid][10], 1);
PlayerTextDrawSetShadow(playerid, Bank_PTD[playerid][10], 0);

Bank_PTD[playerid][11] = CreatePlayerTextDraw(playerid,615.6234, 236.6666, ")"); // ?????
PlayerTextDrawLetterSize(playerid, Bank_PTD[playerid][11], 0.2674, 1.3666);
PlayerTextDrawAlignment(playerid, Bank_PTD[playerid][11], 1);
PlayerTextDrawColor(playerid, Bank_PTD[playerid][11], -1);
PlayerTextDrawBackgroundColor(playerid, Bank_PTD[playerid][11], 255);
PlayerTextDrawFont(playerid, Bank_PTD[playerid][11], 1);
PlayerTextDrawSetProportional(playerid, Bank_PTD[playerid][11], 1);
PlayerTextDrawSetShadow(playerid, Bank_PTD[playerid][11], 0);

Bank_PTD[playerid][12] = CreatePlayerTextDraw(playerid,614.2177, 238.9999, ")"); // ?????
PlayerTextDrawLetterSize(playerid, Bank_PTD[playerid][12], 0.2135, 0.9583);
PlayerTextDrawAlignment(playerid, Bank_PTD[playerid][12], 1);
PlayerTextDrawColor(playerid, Bank_PTD[playerid][12], -1);
PlayerTextDrawBackgroundColor(playerid, Bank_PTD[playerid][12], 255);
PlayerTextDrawFont(playerid, Bank_PTD[playerid][12], 1);
PlayerTextDrawSetProportional(playerid, Bank_PTD[playerid][12], 1);
PlayerTextDrawSetShadow(playerid, Bank_PTD[playerid][12], 0);

Bank_PTD[playerid][13] = CreatePlayerTextDraw(playerid,612.8121, 240.7499, ")"); // ?????
PlayerTextDrawLetterSize(playerid, Bank_PTD[playerid][13], 0.1840, 0.6491);
PlayerTextDrawAlignment(playerid, Bank_PTD[playerid][13], 1);
PlayerTextDrawColor(playerid, Bank_PTD[playerid][13], -1);
PlayerTextDrawBackgroundColor(playerid, Bank_PTD[playerid][13], 255);
PlayerTextDrawFont(playerid, Bank_PTD[playerid][13], 1);
PlayerTextDrawSetProportional(playerid, Bank_PTD[playerid][13], 1);
PlayerTextDrawSetShadow(playerid, Bank_PTD[playerid][13], 0);

Bank_PTD[playerid][14] = CreatePlayerTextDraw(playerid,564.0862, 252.4165, "0000__0000__0000__0000"); // ?????
PlayerTextDrawLetterSize(playerid, Bank_PTD[playerid][14], 0.1872, 1.3316);
PlayerTextDrawAlignment(playerid, Bank_PTD[playerid][14], 2);
PlayerTextDrawColor(playerid, Bank_PTD[playerid][14], -1);
PlayerTextDrawBackgroundColor(playerid, Bank_PTD[playerid][14], 255);
PlayerTextDrawFont(playerid, Bank_PTD[playerid][14], 2);
PlayerTextDrawSetProportional(playerid, Bank_PTD[playerid][14], 1);
PlayerTextDrawSetShadow(playerid, Bank_PTD[playerid][14], 0);

Bank_PTD[playerid][15] = CreatePlayerTextDraw(playerid,596.4141, 272.2500, "VISA"); // ?????
PlayerTextDrawLetterSize(playerid, Bank_PTD[playerid][15], 0.3292, 1.2791);
PlayerTextDrawAlignment(playerid, Bank_PTD[playerid][15], 1);
PlayerTextDrawColor(playerid, Bank_PTD[playerid][15], -1);
PlayerTextDrawBackgroundColor(playerid, Bank_PTD[playerid][15], 255);
PlayerTextDrawFont(playerid, Bank_PTD[playerid][15], 1);
PlayerTextDrawSetProportional(playerid, Bank_PTD[playerid][15], 1);
PlayerTextDrawSetShadow(playerid, Bank_PTD[playerid][15], 0);

Bank_PTD[playerid][16] = CreatePlayerTextDraw(playerid,522.2186, 239.5832, "LD_SPAC:white"); // ?????
PlayerTextDrawTextSize(playerid, Bank_PTD[playerid][16], 10.0000, 14.0000);
PlayerTextDrawAlignment(playerid, Bank_PTD[playerid][16], 1);
PlayerTextDrawColor(playerid, Bank_PTD[playerid][16], -1);
PlayerTextDrawBackgroundColor(playerid, Bank_PTD[playerid][16], 255);
PlayerTextDrawFont(playerid, Bank_PTD[playerid][16], 4);
PlayerTextDrawSetProportional(playerid, Bank_PTD[playerid][16], 0);
PlayerTextDrawSetShadow(playerid, Bank_PTD[playerid][16], 0);

Bank_PTD[playerid][17] = CreatePlayerTextDraw(playerid,520.3446, 241.3332, "LD_SPAC:white"); // ?????
PlayerTextDrawTextSize(playerid, Bank_PTD[playerid][17], 13.0000, 10.0000);
PlayerTextDrawAlignment(playerid, Bank_PTD[playerid][17], 1);
PlayerTextDrawColor(playerid, Bank_PTD[playerid][17], -1);
PlayerTextDrawBackgroundColor(playerid, Bank_PTD[playerid][17], 255);
PlayerTextDrawFont(playerid, Bank_PTD[playerid][17], 4);
PlayerTextDrawSetProportional(playerid, Bank_PTD[playerid][17], 0);
PlayerTextDrawSetShadow(playerid, Bank_PTD[playerid][17], 0);

Bank_PTD[playerid][18] = CreatePlayerTextDraw(playerid,519.4077, 248.3332, "LD_BEAT:chit"); // ?????
PlayerTextDrawTextSize(playerid, Bank_PTD[playerid][18], 5.0000, 6.0000);
PlayerTextDrawAlignment(playerid, Bank_PTD[playerid][18], 1);
PlayerTextDrawColor(playerid, Bank_PTD[playerid][18], -1);
PlayerTextDrawBackgroundColor(playerid, Bank_PTD[playerid][18], 255);
PlayerTextDrawFont(playerid, Bank_PTD[playerid][18], 4);
PlayerTextDrawSetProportional(playerid, Bank_PTD[playerid][18], 0);
PlayerTextDrawSetShadow(playerid, Bank_PTD[playerid][18], 0);

Bank_PTD[playerid][19] = CreatePlayerTextDraw(playerid,529.2467, 248.3332, "LD_BEAT:chit"); // ?????
PlayerTextDrawTextSize(playerid, Bank_PTD[playerid][19], 5.0000, 6.0000);
PlayerTextDrawAlignment(playerid, Bank_PTD[playerid][19], 1);
PlayerTextDrawColor(playerid, Bank_PTD[playerid][19], -1);
PlayerTextDrawBackgroundColor(playerid, Bank_PTD[playerid][19], 255);
PlayerTextDrawFont(playerid, Bank_PTD[playerid][19], 4);
PlayerTextDrawSetProportional(playerid, Bank_PTD[playerid][19], 0);
PlayerTextDrawSetShadow(playerid, Bank_PTD[playerid][19], 0);

Bank_PTD[playerid][20] = CreatePlayerTextDraw(playerid,519.4077, 238.4166, "LD_BEAT:chit"); // ?????
PlayerTextDrawTextSize(playerid, Bank_PTD[playerid][20], 5.0000, 6.0000);
PlayerTextDrawAlignment(playerid, Bank_PTD[playerid][20], 1);
PlayerTextDrawColor(playerid, Bank_PTD[playerid][20], -1);
PlayerTextDrawBackgroundColor(playerid, Bank_PTD[playerid][20], 255);
PlayerTextDrawFont(playerid, Bank_PTD[playerid][20], 4);
PlayerTextDrawSetProportional(playerid, Bank_PTD[playerid][20], 0);
PlayerTextDrawSetShadow(playerid, Bank_PTD[playerid][20], 0);

Bank_PTD[playerid][21] = CreatePlayerTextDraw(playerid,529.2467, 238.4166, "LD_BEAT:chit"); // ?????
PlayerTextDrawTextSize(playerid, Bank_PTD[playerid][21], 5.0000, 6.0000);
PlayerTextDrawAlignment(playerid, Bank_PTD[playerid][21], 1);
PlayerTextDrawColor(playerid, Bank_PTD[playerid][21], -1);
PlayerTextDrawBackgroundColor(playerid, Bank_PTD[playerid][21], 255);
PlayerTextDrawFont(playerid, Bank_PTD[playerid][21], 4);
PlayerTextDrawSetProportional(playerid, Bank_PTD[playerid][21], 0);
PlayerTextDrawSetShadow(playerid, Bank_PTD[playerid][21], 0);

Bank_PTD[playerid][22] = CreatePlayerTextDraw(playerid,522.6873, 240.1666, "LD_SPAC:white"); // ?????
PlayerTextDrawTextSize(playerid, Bank_PTD[playerid][22], 9.0000, 13.0000);
PlayerTextDrawAlignment(playerid, Bank_PTD[playerid][22], 1);
PlayerTextDrawColor(playerid, Bank_PTD[playerid][22], 1263225855);
PlayerTextDrawBackgroundColor(playerid, Bank_PTD[playerid][22], 255);
PlayerTextDrawFont(playerid, Bank_PTD[playerid][22], 4);
PlayerTextDrawSetProportional(playerid, Bank_PTD[playerid][22], 0);
PlayerTextDrawSetShadow(playerid, Bank_PTD[playerid][22], 0);

Bank_PTD[playerid][23] = CreatePlayerTextDraw(playerid,520.8131, 241.9166, "LD_SPAC:white"); // ?????
PlayerTextDrawTextSize(playerid, Bank_PTD[playerid][23], 12.0000, 9.0000);
PlayerTextDrawAlignment(playerid, Bank_PTD[playerid][23], 1);
PlayerTextDrawColor(playerid, Bank_PTD[playerid][23], 1263225855);
PlayerTextDrawBackgroundColor(playerid, Bank_PTD[playerid][23], 255);
PlayerTextDrawFont(playerid, Bank_PTD[playerid][23], 4);
PlayerTextDrawSetProportional(playerid, Bank_PTD[playerid][23], 0);
PlayerTextDrawSetShadow(playerid, Bank_PTD[playerid][23], 0);

Bank_PTD[playerid][24] = CreatePlayerTextDraw(playerid,519.8762, 247.7499, "LD_BEAT:chit"); // ?????
PlayerTextDrawTextSize(playerid, Bank_PTD[playerid][24], 5.0000, 6.0000);
PlayerTextDrawAlignment(playerid, Bank_PTD[playerid][24], 1);
PlayerTextDrawColor(playerid, Bank_PTD[playerid][24], 1263225855);
PlayerTextDrawBackgroundColor(playerid, Bank_PTD[playerid][24], 255);
PlayerTextDrawFont(playerid, Bank_PTD[playerid][24], 4);
PlayerTextDrawSetProportional(playerid, Bank_PTD[playerid][24], 0);
PlayerTextDrawSetShadow(playerid, Bank_PTD[playerid][24], 0);

Bank_PTD[playerid][25] = CreatePlayerTextDraw(playerid,528.7781, 247.7499, "LD_BEAT:chit"); // ?????
PlayerTextDrawTextSize(playerid, Bank_PTD[playerid][25], 5.0000, 6.0000);
PlayerTextDrawAlignment(playerid, Bank_PTD[playerid][25], 1);
PlayerTextDrawColor(playerid, Bank_PTD[playerid][25], 1263225855);
PlayerTextDrawBackgroundColor(playerid, Bank_PTD[playerid][25], 255);
PlayerTextDrawFont(playerid, Bank_PTD[playerid][25], 4);
PlayerTextDrawSetProportional(playerid, Bank_PTD[playerid][25], 0);
PlayerTextDrawSetShadow(playerid, Bank_PTD[playerid][25], 0);

Bank_PTD[playerid][26] = CreatePlayerTextDraw(playerid,519.8762, 238.9999, "LD_BEAT:chit"); // ?????
PlayerTextDrawTextSize(playerid, Bank_PTD[playerid][26], 5.0000, 6.0000);
PlayerTextDrawAlignment(playerid, Bank_PTD[playerid][26], 1);
PlayerTextDrawColor(playerid, Bank_PTD[playerid][26], 1263225855);
PlayerTextDrawBackgroundColor(playerid, Bank_PTD[playerid][26], 255);
PlayerTextDrawFont(playerid, Bank_PTD[playerid][26], 4);
PlayerTextDrawSetProportional(playerid, Bank_PTD[playerid][26], 0);
PlayerTextDrawSetShadow(playerid, Bank_PTD[playerid][26], 0);

Bank_PTD[playerid][27] = CreatePlayerTextDraw(playerid,528.7781, 238.9999, "LD_BEAT:chit"); // ?????
PlayerTextDrawTextSize(playerid, Bank_PTD[playerid][27], 5.0000, 6.0000);
PlayerTextDrawAlignment(playerid, Bank_PTD[playerid][27], 1);
PlayerTextDrawColor(playerid, Bank_PTD[playerid][27], 1263225855);
PlayerTextDrawBackgroundColor(playerid, Bank_PTD[playerid][27], 255);
PlayerTextDrawFont(playerid, Bank_PTD[playerid][27], 4);
PlayerTextDrawSetProportional(playerid, Bank_PTD[playerid][27], 0);
PlayerTextDrawSetShadow(playerid, Bank_PTD[playerid][27], 0);

Bank_PTD[playerid][28] = CreatePlayerTextDraw(playerid,523.3240, 236.6666, "!"); // ?????
PlayerTextDrawLetterSize(playerid, Bank_PTD[playerid][28], 0.0992, 2.1016);
PlayerTextDrawAlignment(playerid, Bank_PTD[playerid][28], 1);
PlayerTextDrawColor(playerid, Bank_PTD[playerid][28], -1);
PlayerTextDrawBackgroundColor(playerid, Bank_PTD[playerid][28], 255);
PlayerTextDrawFont(playerid, Bank_PTD[playerid][28], 3);
PlayerTextDrawSetProportional(playerid, Bank_PTD[playerid][28], 1);
PlayerTextDrawSetShadow(playerid, Bank_PTD[playerid][28], 0);

Bank_PTD[playerid][29] = CreatePlayerTextDraw(playerid,528.4779, 241.9166, "!"); // ?????
PlayerTextDrawLetterSize(playerid, Bank_PTD[playerid][29], 0.1010, 1.4599);
PlayerTextDrawAlignment(playerid, Bank_PTD[playerid][29], 1);
PlayerTextDrawColor(playerid, Bank_PTD[playerid][29], -1);
PlayerTextDrawBackgroundColor(playerid, Bank_PTD[playerid][29], 255);
PlayerTextDrawFont(playerid, Bank_PTD[playerid][29], 3);
PlayerTextDrawSetProportional(playerid, Bank_PTD[playerid][29], 1);
PlayerTextDrawSetShadow(playerid, Bank_PTD[playerid][29], 0);

Bank_PTD[playerid][30] = CreatePlayerTextDraw(playerid,520.5130, 247.1666, "-"); // ?????
PlayerTextDrawLetterSize(playerid, Bank_PTD[playerid][30], 0.3573, 0.4625);
PlayerTextDrawAlignment(playerid, Bank_PTD[playerid][30], 1);
PlayerTextDrawColor(playerid, Bank_PTD[playerid][30], -1);
PlayerTextDrawBackgroundColor(playerid, Bank_PTD[playerid][30], 255);
PlayerTextDrawFont(playerid, Bank_PTD[playerid][30], 1);
PlayerTextDrawSetProportional(playerid, Bank_PTD[playerid][30], 1);
PlayerTextDrawSetShadow(playerid, Bank_PTD[playerid][30], 0);

Bank_PTD[playerid][31] = CreatePlayerTextDraw(playerid,520.0444, 241.9166, "-"); // ?????
PlayerTextDrawLetterSize(playerid, Bank_PTD[playerid][31], 0.3573, 0.4625);
PlayerTextDrawAlignment(playerid, Bank_PTD[playerid][31], 1);
PlayerTextDrawColor(playerid, Bank_PTD[playerid][31], -1);
PlayerTextDrawBackgroundColor(playerid, Bank_PTD[playerid][31], 255);
PlayerTextDrawFont(playerid, Bank_PTD[playerid][31], 1);
PlayerTextDrawSetProportional(playerid, Bank_PTD[playerid][31], 1);
PlayerTextDrawSetShadow(playerid, Bank_PTD[playerid][31], 0);

Bank_PTD[playerid][32] = CreatePlayerTextDraw(playerid,528.4779, 241.9166, "-"); // ?????
PlayerTextDrawLetterSize(playerid, Bank_PTD[playerid][32], 0.3948, 0.4741);
PlayerTextDrawAlignment(playerid, Bank_PTD[playerid][32], 1);
PlayerTextDrawColor(playerid, Bank_PTD[playerid][32], -1);
PlayerTextDrawBackgroundColor(playerid, Bank_PTD[playerid][32], 255);
PlayerTextDrawFont(playerid, Bank_PTD[playerid][32], 1);
PlayerTextDrawSetProportional(playerid, Bank_PTD[playerid][32], 1);
PlayerTextDrawSetShadow(playerid, Bank_PTD[playerid][32], 0);

Bank_PTD[playerid][33] = CreatePlayerTextDraw(playerid,528.9464, 247.1667, "-"); // ?????
PlayerTextDrawLetterSize(playerid, Bank_PTD[playerid][33], 0.3704, 0.4566);
PlayerTextDrawAlignment(playerid, Bank_PTD[playerid][33], 1);
PlayerTextDrawColor(playerid, Bank_PTD[playerid][33], -1);
PlayerTextDrawBackgroundColor(playerid, Bank_PTD[playerid][33], 255);
PlayerTextDrawFont(playerid, Bank_PTD[playerid][33], 1);
PlayerTextDrawSetProportional(playerid, Bank_PTD[playerid][33], 1);
PlayerTextDrawSetShadow(playerid, Bank_PTD[playerid][33], 0);

Bank_PTD[playerid][34] = CreatePlayerTextDraw(playerid,520.9815, 274.0000, "cardholder_name"); // ?????
PlayerTextDrawLetterSize(playerid, Bank_PTD[playerid][34], 0.1385, 1.0341);
PlayerTextDrawAlignment(playerid, Bank_PTD[playerid][34], 1);
PlayerTextDrawColor(playerid, Bank_PTD[playerid][34], -1);
PlayerTextDrawBackgroundColor(playerid, Bank_PTD[playerid][34], 255);
PlayerTextDrawFont(playerid, Bank_PTD[playerid][34], 2);
PlayerTextDrawSetProportional(playerid, Bank_PTD[playerid][34], 1);
PlayerTextDrawSetShadow(playerid, Bank_PTD[playerid][34], 0);

Bank_PTD[playerid][35] = CreatePlayerTextDraw(playerid,564.0862, 265.8333, "00/00"); // ?????
PlayerTextDrawLetterSize(playerid, Bank_PTD[playerid][35], 0.1118, 0.9816);
PlayerTextDrawAlignment(playerid, Bank_PTD[playerid][35], 1);
PlayerTextDrawColor(playerid, Bank_PTD[playerid][35], -1);
PlayerTextDrawBackgroundColor(playerid, Bank_PTD[playerid][35], 255);
PlayerTextDrawFont(playerid, Bank_PTD[playerid][35], 2);
PlayerTextDrawSetProportional(playerid, Bank_PTD[playerid][35], 1);
PlayerTextDrawSetShadow(playerid, Bank_PTD[playerid][35], 0);
