    Mofsma_PTD[playerid][0] = CreatePlayerTextDraw(playerid, -0.1828, 436.6330, "LD_SPAC:white"); // ?????
	PlayerTextDrawTextSize(playerid, Mofsma_PTD[playerid][0], 2.0000, 27.0000);
	PlayerTextDrawAlignment(playerid, Mofsma_PTD[playerid][0], 1);
	PlayerTextDrawColor(playerid, Mofsma_PTD[playerid][0], -45569);
	PlayerTextDrawBackgroundColor(playerid, Mofsma_PTD[playerid][0], 255);
	PlayerTextDrawFont(playerid, Mofsma_PTD[playerid][0], 4);
	PlayerTextDrawSetProportional(playerid, Mofsma_PTD[playerid][0], 0);
	PlayerTextDrawSetShadow(playerid, Mofsma_PTD[playerid][0], 0);